### ISSUE TITLE
Composer contraints can't be satisfied on PHP 7.1 

### ISSUE THREAD

**Issue by oleg-andreyev** [sonata-project/SonataDoctrineORMAdminBundle#1021]
PHP 7.1

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sonata-project/core-bundle 3.18.0 requires php ^7.2 -> your PHP version (7.1.28) does not satisfy that requirement.
    - sonata-project/admin-bundle 3.63.0 requires sonata-project/core-bundle ^3.18.0 -> satisfiable by sonata-project/core-bundle[3.18.0].
    - Installation request for sonata-project/admin-bundle ^3.63 -> satisfiable by sonata-project/admin-bundle[3.63.0].

```

triggered by #1017

**Comment by oleg-andreyev** [comment]
Looks like admin-bundle needs to downgrade to 3.58.0 because 3.59 will require core-bundle (^3.18.0) which requires ^7.2

```zsh
❯ composer why-not sonata-project/admin-bundle:3.59
                                                                        
sonata-project/admin-bundle               3.59.0   requires  sonata-project/core-bundle (^3.18.0)      
sonata-project/doctrine-orm-admin-bundle  3.x-dev  requires  sonata-project/core-bundle (^3.14,<3.18)  

❯
```

**Comment by core23** [comment]
Sorry, but we don't support dead PHP versions: https://www.php.net/supported-versions.php

Also please have a look at: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/CONTRIBUTING.md#dependency-changes

**Comment by oleg-andreyev** [comment]
@core23 but in this case PHP version should be bumped to ^7.2 otherwise it's a disinformation https://packagist.org/packages/sonata-project/doctrine-orm-admin-bundle says that 7.1 is supported.

**Comment by greg0ire** [comment]
Please send a PR

**Comment by VincentLanglet** [comment]
I created a PR for this https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1022
