### ISSUE TITLE
Have an option to set the default route name of associations link

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataDoctrineORMAdminBundle#1160]
Concerning those templates: https://github.com/sonata-project/SonataAdminBundle/tree/1a46603f9d4cf44edab5b73d49751f1848630fb0/src/Resources/views/CRUD/Association

And maybe the old ones from ORM/ODM bundles.

The default route name for association links is `edit`.

First, that does not really make sens to show the entity form when you click on a link from the list, but why not.

Second, there is no way to have the route set to `show` as default, except filling the option on each field of each admin class.

It would be great to have an option for that, maybe on configuration.

Note: I was sure to already open an issue like this, but I can't retrieve it.

**Comment by VincentLanglet** [comment]
`show` will be the default behavior in 4.0. But an option is still interesting.
