### ISSUE TITLE
Using Paginator instead of Pager

### ISSUE THREAD

**Issue by kirya-dev** [sonata-project/SonataDoctrineORMAdminBundle#1181]
## Feature Request

Pager cannot works when using group by in queries.

class of Paginator is
\Doctrine\ORM\Tools\Pagination\Paginator

**Comment by VincentLanglet** [comment]
Is this enough @kirya-dev https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Datagrid/Pager.php#L199 ?

**Comment by kirya-dev** [comment]
When im wrote this issue latest version was 3.26.0 of this package.

Here not yet using doctrine Paginator.
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.26.0/src/Datagrid/Pager.php

You are fixed this issue in another PR some hours ago.
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1268

This issue can be closed. Thanks
