### ISSUE TITLE
[Next Major] Close API

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataDoctrineORMAdminBundle#1187]
- [x] Add `final` modifier
- [x] Reduce visibility to `private` if possible

**Comment by dmaicher** [comment]
@VincentLanglet is there anything left to do for this one?

**Comment by VincentLanglet** [comment]
For instance: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/src/Block/AuditBlockService.php#L31 can be private

That's all I found
