### ISSUE TITLE
Overriding doctrine_orm.xml

### ISSUE THREAD

**Issue by francofallica** [sonata-project/SonataDoctrineORMAdminBundle#12]
Hi, 

I tried to integrate SonataAdminBundle with SonataDoctrineORMAdminBundle to my project. 
Everything worked quite well. But now I'm stuck. 

doctrine_orm.xml defines sonata.admin.manager.orm with the entity manager to use. Now my problem is that I do not whant to use the default manager. Because I didn't find a config param to set the entitymanager I copied the file to my bundle and added

imports:
    - { resource: "@MyBundle/Resources/config/doctrine_orm.xml" }

but when I do this I'll get the following error: 

annot import resource "XXX/Symfony/app/config/." from "XXX/Symfony/app/config/routing.yml".

when I change the name of the entity manager in the original doctrine_orm.xml in the sonataDoctrineOrmAdminBundle then it works. 

So my question is how can I define the entity manager the bundle will use. Or how can I properly override the sonata.admin.manager.orm service. 

Thanks already, any hints appreciated. 
franco

**Comment by chakib-lah** [comment]
I have the same problem and I do not know how I do it for inject setModelManager and how I can do the configuration, can you explain a little more or add a code that explains how to have 2 entity manager for sonataAdmin
