### ISSUE TITLE
This project is using methods which does not exist in ProxyQueryInterface without exposing a custom interface

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataDoctrineORMAdminBundle#1216]
Related to the discussion: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1199#issuecomment-732333757

When methods have `ProxyQueryInterface` param, we're using them like it was always a `ProxyQuery`.
We should add a type-check before.

Currently the `ProxyQuery` is not final, so
```
$query instanceof ProxyQuery
```
Can do the job, but exposing an interface `DoctrineProxyQueryInterface extends ProxyQueryInterface` could be better in order to declare `ProxyQuery` as final and allow others implementation.

The main issue with the DoctrineProxyQueryInterface (which should basically be ProxyQueryInterface + QueryBuilder) are:
- There is no QueryBuilderInterface we can extends.
- If we declare our DoctrineProxyQueryInterface with all the methods from the QueryBuilder, we'll have to add them to our ProxyQuery since __call is not enough to implement an Interface.

**Comment by phansys** [comment]
I think we must declare any missing interface.

>If we declare our DoctrineProxyQueryInterface with all the methods from the QueryBuilder, we'll have to add them to our ProxyQuery since __call is not enough to implement an Interface.

Then, we should explicitly declare the missing methods and call the decorated service.

**Comment by VincentLanglet** [comment]
> I think we must declare any missing interface.
> 
> > If we declare our DoctrineProxyQueryInterface with all the methods from the QueryBuilder, we'll have to add them to our ProxyQuery since __call is not enough to implement an Interface.
> 
> Then, we should explicitly declare the missing methods and call the decorated service.

A simpler way should be to not rely on the `__call` implementation. And use `getQueryBuilder()->...`.
I'm on a PR for this.
