### ISSUE TITLE
Order by computedField

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataDoctrineORMAdminBundle#1225]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.81.1 3.82.0 The missing Symfony Admin Generator
sonata-project/block-bundle              4.4.0  4.4.0  Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/doctrine-extensions       1.10.1 1.10.1 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.26.0 3.26.0 Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.4.1  2.4.1  Lightweight Exporter library
sonata-project/form-extensions           1.7.1  1.7.1  Symfony form extensions
sonata-project/twig-extensions           1.4.1  1.4.1  Sonata twig extensions
```

## Subject

I would like to order the list by a computed sql field
```php
    protected function configureQuery(ProxyQueryInterface $query): ProxyQueryInterface
    {
        $query = parent::configureQuery($query);

        $alias = $query->getRootAlias()[0];
        $query->leftJoin("$alias.children", 'child');
        $query->leftJoin("$alias.dogs", 'dog');
        $query->addSelect('GREATEST(MAX(dog.age), MAX(child.age)) as HIDDEN maxAge');
        $query->addOrderBy('maxAge', 'DESC');

        return $query;
    }
```

This query is working well when I tried the SQL by myself.
But, it doesn't work in the Datagrid.

The issue is introduced by the `getFixedQueryBuilder()` method.https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/71ea5138cfc443a42aa0b8c692b98bee11001743/src/Datagrid/ProxyQuery.php#L366

Firstly, my hidden field is lost because it overrides the select:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/71ea5138cfc443a42aa0b8c692b98bee11001743/src/Datagrid/ProxyQuery.php#L393
If I add manually `$queryBuilderId->addSelect(...)` it works better.

Secondly, I don't have 32 results by page because of the `distinct`https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/71ea5138cfc443a42aa0b8c692b98bee11001743/src/Datagrid/ProxyQuery.php#L396
If I replace 
```php
$queryBuilderId->distinct($this->isDistinct());
```
by
```php
$queryBuilderId->groupBy('o.id');
```
It works like a charm.

Is there a way to add a generic way to support my case ? It required
- rework the `select` part to add extra (hidden ?) fields.
- Use groupBy instead of distinct.

I'm more blocked by my doctrine-knowledge than my sonata-knowledge here.
Maybe you could help me @greg0ire ?

**Comment by greg0ire** [comment]
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/71ea5138cfc443a42aa0b8c692b98bee11001743/src/Datagrid/ProxyQuery.php#L360-L366

That method has a really vague name and the comment above does not help much understanding the purpose (or even make any sense :sweat_smile: ) . If you ever understand what it is about, please improve the comment :pray:

**Comment by VincentLanglet** [comment]
> https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/71ea5138cfc443a42aa0b8c692b98bee11001743/src/Datagrid/ProxyQuery.php#L360-L366
> 
> That method has a really vague name and the comment above does not help much understanding the purpose (or even make any sense 😅 ) . If you ever figure out what the purpose of this method is, please improve the comment 🙏

This method is overriding the `select` in order to only select the id of the wanted object.
And then, it remove the offset and the limite and add a "andWhere id is in the id I just found".

I should try to stop using it.
