### ISSUE TITLE
ModelManager::addIdentifiersToQuery will not order items correctly

### ISSUE THREAD

**Issue by matjaz321** [sonata-project/SonataDoctrineORMAdminBundle#1233]
#### Sonata packages
<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.83.0 3.83.0 The missing Symfony Admin Generator
sonata-project/block-bundle              4.4.0  4.4.0  Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/doctrine-extensions       1.10.1 1.10.1 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.26.0 3.26.0 Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.4.1  2.4.1  Lightweight Exporter library
sonata-project/form-extensions           1.7.1  1.7.1  Symfony form extensions
sonata-project/twig-extensions           1.4.2  1.4.2  Sonata twig extensions
```

</p>
</details>

#### Symfony packages
<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
symfony/asset                      v4.4.17 v4.4.17 Symfony Asset Component
symfony/browser-kit                v4.4.17 v4.4.17 Symfony BrowserKit Component
symfony/cache                      v4.4.10 v4.4.17 Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts            v2.2.0  v2.2.0  Generic abstractions related to caching
symfony/config                     v4.4.17 v4.4.17 Symfony Config Component
symfony/console                    v4.4.17 v4.4.17 Symfony Console Component
symfony/css-selector               v4.4.17 v4.4.17 Symfony CssSelector Component
symfony/debug                      v4.4.17 v4.4.17 Symfony Debug Component
symfony/debug-bundle               v4.4.17 v4.4.17 Symfony DebugBundle
symfony/dependency-injection       v4.4.17 v4.4.17 Symfony DependencyInjection Component
symfony/deprecation-contracts      v2.2.0  v2.2.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v4.4.17 v4.4.17 Symfony Doctrine Bridge
symfony/dom-crawler                v4.4.17 v4.4.17 Symfony DomCrawler Component
symfony/error-handler              v4.4.17 v4.4.17 Symfony ErrorHandler Component
symfony/event-dispatcher           v4.4.17 v4.4.17 Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v1.1.9  v2.2.0  Generic abstractions related to dispatching event
symfony/expression-language        v4.4.17 v4.4.17 Symfony ExpressionLanguage Component
symfony/filesystem                 v4.4.17 v4.4.17 Symfony Filesystem Component
symfony/finder                     v4.4.17 v4.4.17 Symfony Finder Component
symfony/form                       v4.4.17 v4.4.17 Symfony Form Component
symfony/framework-bundle           v4.4.17 v4.4.17 Symfony FrameworkBundle
symfony/http-client-contracts      v2.3.1  v2.3.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v4.4.17 v4.4.17 Symfony HttpFoundation Component
symfony/http-kernel                v4.4.17 v4.4.17 Symfony HttpKernel Component
symfony/inflector                  v4.4.17 v4.4.17 Symfony Inflector Component
symfony/intl                       v4.4.17 v4.4.17 A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/mime                       v4.4.17 v4.4.17 A library to manipulate MIME messages
symfony/monolog-bridge             v4.4.17 v4.4.17 Symfony Monolog Bridge
symfony/monolog-bundle             v3.6.0  v3.6.0  Symfony MonologBundle
symfony/options-resolver           v4.4.17 v4.4.17 Symfony OptionsResolver Component
symfony/phpunit-bridge             v5.2.0  v5.2.0  Symfony PHPUnit Bridge
symfony/polyfill-ctype             v1.20.0 v1.20.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     v1.20.0 v1.20.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-idn          v1.20.0 v1.20.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.20.0 v1.20.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-php80             v1.20.0 v1.20.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                    v4.4.17 v4.4.17 Symfony Process Component
symfony/property-access            v4.4.17 v4.4.17 Symfony PropertyAccess Component
symfony/property-info              v4.4.17 v4.4.17 Symfony Property Info Component
symfony/proxy-manager-bridge       v4.4.17 v4.4.17 Symfony ProxyManager Bridge
symfony/psr-http-message-bridge    v2.0.2  v2.0.2  PSR HTTP message bridge
symfony/routing                    v4.4.17 v4.4.17 Symfony Routing Component
symfony/security                   v4.4.17 v4.4.17 Symfony Security Component
symfony/security-acl               v3.1.0  v3.1.0  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v4.4.17 v4.4.17 Symfony SecurityBundle
symfony/serializer                 v4.4.17 v4.4.17 Symfony Serializer Component
symfony/service-contracts          v2.2.0  v2.2.0  Generic abstractions related to writing services
symfony/stopwatch                  v4.4.17 v4.4.17 Symfony Stopwatch Component
symfony/string                     v5.2.0  v5.2.0  Symfony String component
symfony/swiftmailer-bundle         v3.2.4  v3.5.1  Symfony SwiftmailerBundle
symfony/templating                 v4.4.17 v4.4.17 Symfony Templating Component
symfony/translation                v4.4.17 v4.4.17 Symfony Translation Component
symfony/translation-contracts      v2.3.0  v2.3.0  Generic abstractions related to translation
symfony/twig-bridge                v4.4.17 v4.4.17 Symfony Twig Bridge
symfony/twig-bundle                v4.4.17 v4.4.17 Symfony TwigBundle
symfony/validator                  v4.4.17 v4.4.17 Symfony Validator Component
symfony/var-dumper                 v4.4.17 v4.4.17 Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter               v4.4.17 v4.4.17 A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-profiler-bundle        v4.4.17 v4.4.17 Symfony WebProfilerBundle
symfony/webpack-encore-bundle      v1.8.0  v1.8.0  Integration with your Symfony app & Webpack Encore!
symfony/yaml                       v4.4.17 v4.4.17 Symfony Yaml Component
```

</p>
</details>

#### PHP version

```
$ php -v
PHP 7.4.13 (cli) (built: Nov 30 2020 20:40:09) ( NTS )
```

## Steps to reproduce
- Create queryBuilder and use `ModelManager::addIdentifiersToQuery`.
- I have for example in the database entities with ids: `[2, 8, 13, 20]`, but those identifiers are passed in this method exactly in this order: `[20, 8, 13, 2]`.
- Then just run the query and you will see that items are not ordered correctly. (they are by default ordered by ASC).
- I can mention that this method is used in another sonata admin project ([link](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Form/DataTransformer/ModelToIdPropertyTransformer.php#L120)).
## Expected results
- When `ModelManager::addIdentifiersToQuery` is used the entities should be ordered by the same order as the entity identifiers were passed in.
## Actual results
- If I understand correctly this [method](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Model/ModelManager.php#L506) is suppose to keep the exact same order of the items that were passed in in the parameter `array $idx`, but they are not...
- If you pass in the array of ids for example `[20, 8, 13, 2]`, the outcome of this queryBuilder is going to be: `[2, 8, 13, 20]`

### The root of this issue
- So [AutcompleteType](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Form/Type/ModelAutocompleteType.php#L41) is using model transformer [ModelToIdPropertyTransformer](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Form/Type/ModelAutocompleteType.php#L41)
- When the [transform](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Form/DataTransformer/ModelToIdPropertyTransformer.php#L133) is called the entities can come in whatever order and everything is fine here.
- Before the form is submitted the [reverseTransform](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Form/DataTransformer/ModelToIdPropertyTransformer.php#L91) is called. So this method will call `addIdentifiersToQuery` and it will pass in array of identifiers, which will then after the query is executed return collection of entities (which are not ordered correctly).
- The AutcompleteType also adds [event listener](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Form/Type/ModelAutocompleteType.php#L56) that's coming from symfony/form
- So on the submit event listener will call `$event->getData()` and this data will be incorrectly ordered collection of entities. That was due to the ModeldtoPropertyTransformer::reverseTransform (because the items are not sorted correctly).
- Then this listener will not remove incorrect items [link](https://github.com/symfony/form/blob/5.x/Extension/Core/EventListener/ResizeFormListener.php#L153)

### Solution
- By adding this small code snippet, the ordering is then working as expected.
- If this solution is correct I can quickly create a new PR
 ``` php

 $qb->addOrderBy(
      sprintf('FIELD(%s.%s, %s)', current($qb->getRootAliases()), $name, implode(',', $idx))
 );

```

**Comment by matjaz321** [comment]
Please just let me know if mentioned solution is appropriate, so I can create a new PR quickly...

**Comment by VincentLanglet** [comment]
> Please just let me know if mentioned solution is appropriate, so I can create a new PR quickly...

The best way to know is
- to test this on your project
- to create the PR with tests.

**Comment by franmomu** [comment]
interesting, never used `FIELD` function, AFAIK is not available in `doctrine/orm`, is is going to work for any database?

**Comment by matjaz321** [comment]
> interesting, never used `FIELD` function, AFAIK is not available in `doctrine/orm`, is is going to work for any database?

Ah you are right it's only available in mysql...

**Comment by franmomu** [comment]
Would [this](https://stackoverflow.com/a/1310188) work? I remember using `CASE` in `SELECT` in doctrine, but not in `ORDER BY`.

**Comment by matjaz321** [comment]
> Would [this](https://stackoverflow.com/a/1310188) work? I remember using `CASE` in `SELECT` in doctrine, but not in `ORDER BY`.

Yeah probably will try it

**Comment by VincentLanglet** [comment]
> > Would [this](https://stackoverflow.com/a/1310188) work? I remember using `CASE` in `SELECT` in doctrine, but not in `ORDER BY`.
> 
> Yeah will try it

Hi @matjaz321 

Does it work ? Can you provide a PR ? :)
