### ISSUE TITLE
Please merge `countResult()` into master

### ISSUE THREAD

**Issue by michanismus** [sonata-project/SonataDoctrineORMAdminBundle#1261]
Could you please merge the updates into master branch?

I have to use master because I am using Symfony 5.x.

Master branch has missing `countResult()` method.

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/commit/de58c309aeefaaf33518ebdffc24b78026e710ad

**Comment by dmaicher** [comment]
Will look into creating a PR that merges 3.x into master today.

But generally you are using unreleased versions :wink: So expect more of those issues to come.

Maybe you should reference a fixed commit of 4.x-dev/master with compose to have more control over updates.

**Comment by michanismus** [comment]
I would really appreciate that 👍 
Unfortunately I have to use the `4.x-dev` branches because I use Symfony 5.2 and the `3.x` branches conflicts my  composer requirements...

I will create a fork as temporary solution...

**Comment by VincentLanglet** [comment]
You also can open the PR by yourself @michanismus

**Comment by michanismus** [comment]
If I had the time to dive into the Pager changes I would...
Just created an simple workaround in my fork.

**Comment by dmaicher** [comment]
That would be even better 👍

**Comment by michanismus** [comment]
@dmaicher @VincentLanglet 
Could you please review my changes?
https://github.com/michanismus/SonataDoctrineORMAdminBundle/blob/master/src/Datagrid/Pager.php

If it looks fine for you I will rebase and create a PR.

**Comment by VincentLanglet** [comment]
> If I had the time to dive into the Pager changes I would...
> Just created an simple workaround in my fork.

You can also use an older commit of SonataAdmin.

**Comment by michanismus** [comment]
> > If I had the time to dive into the Pager changes I would...
> > Just created an simple workaround in my fork.
> 
> You can also use an older commit of SonataAdmin.

Nope, conflicts with my composer requirements...

**Comment by michanismus** [comment]
@VincentLanglet I see that `getCountColumn()` is deprecated as well... so 4.x will only use `countSinglePrimaryKey`?

**Comment by michanismus** [comment]
So I have to use my fork until you merged the PR mentioned by @dmaicher. No problem 👍 
But its kind of weird that you introduced changes for 4.x, added compatibility to 3.x branch before they were added to the target 4.x-dev branch.

Anyway, thanks for your great work!

**Comment by VincentLanglet** [comment]
> added compatibility to 3.x branch before they were added to the target 4.x-dev branch.

It's the normal way to always fix the oldest branch first and then merge to the recent branch.
You can merge 3.x into 4.x. You can't merge 4.x into 3.x.

Look at symfony repository, bugFix are made on 4.4 branch and then merged into 5.x ones.

**Comment by michanismus** [comment]
Yes but the changes are not bugfixes. These changes are BC.
Symfony 4.4 is the current LTS version. BC 5.x changes wont never merged into 4.4...

**Comment by VincentLanglet** [comment]
> Yes but the changes are not bugfixes. These changes are BC.
> Symfony 4.4 is the current LTS version. BC 5.x changes wont never merged into 4.4...

There is no breaking change here. It's just about adding compatibility.

**Comment by michanismus** [comment]
> There is no breaking change here. It's just about adding compatibility.

Ok, then I got something wrong.
