### ISSUE TITLE
Twig requirements

### ISSUE THREAD

**Issue by malutanpetronel** [sonata-project/SonataDoctrineORMAdminBundle#1302]
Are you sure it needs 
twig/twig: ^2.10 || ^3.0 ?

I have a 4.4 project and 

whenever I do
composer require sonata-project/doctrine-orm-admin-bundle
this will
- Unconfiguring symfony/web-profiler-bundle (>=3.3): From github.com/symfony/recipes:master
I am wondering how to make both work as I need them in my project ? 

An I beleive is because Twig requirements ?

**Comment by greg0ire** [comment]
Is `symfony/web-profiler-bundle` required in your `composer.json`?
