### ISSUE TITLE
PHP 8 & Symfony 5.x support

### ISSUE THREAD

**Issue by DavidGarciaCat** [sonata-project/SonataDoctrineORMAdminBundle#1305]
## Feature Request

Dear Sonata team,

I want to install Sonata on a server running PHP 8. Although the Admin Bundle seems to offer this option on its current version ([3.88.0](https://packagist.org/packages/sonata-project/admin-bundle#3.88.0)), it looks like this ORM Bundle doesn't support it (not even on the [dev-master](https://packagist.org/packages/sonata-project/doctrine-orm-admin-bundle#dev-master) dependency).

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/119357371858141df56757d76a7530885672cb8a/composer.json#L28

There is also a mix of Symfony 4 or Symfony 4|5 packages, meaning that it blocks me to upgrade the Symfony version too:

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/119357371858141df56757d76a7530885672cb8a/composer.json#L35-L44

Is there any chance of getting an update soon that could cover both updates?

Is there any way to help expedite the update for someone who never contributed to this repo or in the sonata project?

Thank you,

**Comment by VincentLanglet** [comment]
See https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1285 for the support for php8 

For Symfony 5, it will be supported in the next major version. We're working on the 4.0 milestone.

**Comment by jordisala1991** [comment]
This can be closed, on master there is support for sf5, and on 3.x for php 8.0
