### ISSUE TITLE
doctrine_orm_choice filter doesn't work for many-to-many related entities

### ISSUE THREAD

**Issue by thomas2411** [sonata-project/SonataDoctrineORMAdminBundle#133]
When using doctrine_orm_choice as a filter for a field which is related with many-to-many, gives this error:

```
[Semantical Error] line 0, col 123 near 'autor = :aut': Error: Invalid PathExpression. StateFieldPathExpression or SingleValuedAssociationField expected. 
```

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
