### ISSUE TITLE
Add FieldDescriptionFactory + resolve TypeGuesser deprecations

### ISSUE THREAD

**Issue by dmaicher** [sonata-project/SonataDoctrineORMAdminBundle#1348]
We need this for releasing 4.0.

See https://github.com/sonata-project/SonataAdminBundle/pull/6854

Related ODM PR: https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/531

@franmomu are you looking into this? Let me know if you need any help

**Comment by VincentLanglet** [comment]
This could be started on 3.x after the 3.92 release
