### ISSUE TITLE
StringFilter does not escape % (percent sign) or _ (underscore)

### ISSUE THREAD

**Issue by franek** [sonata-project/SonataDoctrineORMAdminBundle#138]
It seems that Sonata\DoctrineORMAdminBundle\Filter\StringFilter does not filter % or _

I have tried something this : 

``` php
if ($data['type'] == ChoiceType::TYPE_EQUAL) {
    $this->applyWhere($queryBuilder, sprintf('%s.%s %s :%s', $alias, $field, $operator, $parameterName));
    $queryBuilder->setParameter($parameterName, $data['value']);
} else {
    if ($data['type'] == ChoiceType::TYPE_CONTAINS) {
        $where = $queryBuilder->expr()->like(sprintf('%s.%s', $alias, $field), sprintf(':%s', $parameterName));
    } else if ($data['type'] == ChoiceType::TYPE_NOT_CONTAINS) {
        $where = $queryBuilder->expr()->not($queryBuilder->expr()->like(sprintf('%s.%s', $alias, $field), sprintf(':%s', $parameterName)));
    }
    $this->applyWhere($queryBuilder, $where);
    $queryBuilder->setParameter($parameterName, sprintf($this->getOption('format'), $queryBuilder->expr()->literal($data['value'], 'string')));
}
```

This example uses : 
- use expr()->like to create the like
- use expr()->literal to escape _, %
  but literal does not work with the oci8 driver that I use.

Any idea ?

**Comment by core23** [comment]
Bug still exists

**Comment by eugenekurasov** [comment]
Hi,
Literal does not escaping chars("%", "_").
https://github.com/doctrine/doctrine2/blob/2.5/lib/Doctrine/ORM/Query/Expr.php#L611
I think we should add slash to this chars.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
