### ISSUE TITLE
Introduce "force_case_insensitivity" option and deprecate "case_sensitive"

### ISSUE THREAD

**Issue by phansys** [sonata-project/SonataDoctrineORMAdminBundle#1415]
## RFC

Recap from https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1402#issuecomment-817048349 and https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/1387#issuecomment-812917465.

I think changing the name of this option to `force_case_insensitivity` (deprecating `case_sensitive`) to make clearer its real behavior will be simpler than adding more specific checks for each RDBMS and its possible scenarios (column collations, extensions availability, etc).
I think it reflects its purpose in a better way.
With this approach I think we could keep the current logic for all the RDBMSs with no extra checks (just inversing the check against this new option), using `true` when we want to force the matching to ignore the case sensitivity, and leaving it unset or using `false` when we want the RDBMS to use its default behavior.

By instance, in order to have a concrete idea if the comparisons are case sensitive or not in MySQL, currently we should detect if the compared columns are using the collation utf8mb4_0900_as_cs or utf8mb4_bin, otherwise we have to detect if the `DoctrineExtensions\Query\Mysql\Binary` (`BINARY()`) DQL function is registered under the "binary" name, to allow the comparison to use that function.
A similar case is present here in SQLite, where the `PRAGMA case_sensitive_like` directive controls the behavior.
I haven't more evidence about other RDMSs, but I guess those examples are enough to bring a clear idea about the problem.

**Comment by VincentLanglet** [comment]
Since the `case_sensitive: true` doesn't work well, I think it's a good solution.
