### ISSUE TITLE
Simple pager crashes on large datasets

### ISSUE THREAD

**Issue by alfabetagama** [sonata-project/SonataDoctrineORMAdminBundle#1443]
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'

sonata-project/admin-bundle              3.99.0 3.99.0 The missing Symfony Admin Generator
sonata-project/block-bundle              4.5.3  4.5.3  Symfony SonataBlockBundle
sonata-project/cache                     2.1.1  2.1.1  Cache library
sonata-project/doctrine-extensions       1.12.0 1.12.0 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.31.0 3.34.0 Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.6.2  2.6.2  Lightweight Exporter library
sonata-project/form-extensions           1.9.0  1.9.0  Symfony form extensions
sonata-project/twig-extensions           1.5.1  1.5.1  Sonata twig extensions
vagrant@ubuntu2004:~/apps/api-paztir$
sonata-project/block-bundle              4.5.3  4.5.3  Symfony SonataBlockBundle
sonata-project/cache                     2.1.1  2.1.1  Cache library
sonata-project/doctrine-extensions       1.12.0 1.12.0 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.31.0 3.34.0 Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.6.2  2.6.2  Lightweight Exporter library
sonata-project/form-extensions           1.9.0  1.9.0  Symfony form extensions
sonata-project/twig-extensions           1.5.1  1.5.1  Sonata twig extensions

```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
symfony/contracts                v1.1.10 v2.4.0  A set of abstractions extracted out of the Symfony components
symfony/deprecation-contracts    v2.4.0  v2.4.0  A generic function and convention to trigger deprecation notices
symfony/monolog-bundle           v3.7.0  v3.7.0  Symfony MonologBundle
symfony/phpunit-bridge           v5.2.7  v5.2.7  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-ctype           v1.22.1 v1.22.1 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme   v1.22.1 v1.22.1 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu        v1.22.1 v1.22.1 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn        v1.22.1 v1.22.1 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer v1.22.1 v1.22.1 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring        v1.22.1 v1.22.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72           v1.22.1 v1.22.1 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73           v1.22.1 v1.22.1 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80           v1.22.1 v1.22.1 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/psr-http-message-bridge  v2.1.0  v2.1.0  PSR HTTP message bridge
symfony/security-acl             v3.1.2  v3.1.2  Symfony Security Component - ACL (Access Control List)
symfony/string                   v5.2.6  v5.2.6  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points a...
symfony/symfony                  v4.4.22 v5.2.7  The Symfony PHP framework

```

</p>
</details>

#### PHP version

```
$ php -v
PHP 7.4.18 (cli) (built: May  3 2021 11:27:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.18, Copyright (c), by Zend Technologies

```

## Minimal repository with the bug
3.34

## Expected results
should take less than 3 ms

                                                         QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.44..198.90 rows=251 width=1602)
   ->  Group  (cost=0.44..13921690.63 rows=17606664 width=1602)
         Group Key: id
         ->  Index Scan Backward using lock_message_pkey on log c0_  (cost=0.44..13877673.97 rows=17606664 width=1602)

## Actual results

takes 100seconds
                                                       QUERY PLAN
-------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=9115117.69..9115119.57 rows=251 width=16)
   ->  Unique  (cost=9115117.69..9247167.67 rows=17606664 width=16)
         ->  Sort  (cost=9115117.69..9159134.35 rows=17606664 width=16)
               Sort Key: (min(dctrn_result.sclr_21)), dctrn_result.id_0
               ->  GroupAggregate  (cost=6511832.11..6819948.73 rows=17606664 width=16)
                     Group Key: dctrn_result.id_0
                     ->  Sort  (cost=6511832.11..6555848.77 rows=17606664 width=16)
                           Sort Key: dctrn_result.id_0
                           ->  Subquery Scan on dctrn_result  (cost=3732479.90..4216663.16 rows=17606664 width=16)
                                 ->  WindowAgg  (cost=3732479.90..4040596.52 rows=17606664 width=2248)
                                       ->  Sort  (cost=3732479.90..3776496.56 rows=17606664 width=8)
                                             Sort Key: c0_.id DESC
                                             ->  Seq Scan on log c0_  (cost=0.00..1472558.64 rows=17606664 width=8)

**Comment by alfabetagama** [comment]
1. sonata-project/admin-bundle              3.99.0 3.99.0 The missing Symfony Admin Generator
2. I get timeout on nginx, but this is because script takes so long, because of query
3. 17.000.000
4. It takes as much on 3.31.

**Comment by VincentLanglet** [comment]
Do you use a custom query ? 
I'm not sure why there is a `ROW_NUMBER()`.

The `executeQuery` has the following code 
```
         $query = $this->getDoctrineQuery();

         $identifierFieldNames = $this
            ->getQueryBuilder()
            ->getEntityManager()
            ->getMetadataFactory()
            ->getMetadataFor(current($this->getQueryBuilder()->getRootEntities()))
            ->getIdentifierFieldNames();

        return new Paginator($query, 1 === \count($identifierFieldNames));
```
And the `getDoctrineQuery` only add some sortBy and orderBy.

So we're relying on the Paginator: https://github.com/doctrine/orm/blob/2.8.x/lib/Doctrine/ORM/Tools/Pagination/Paginator.php

Does those big query works for you if you're executing them manually ? With dql and paginator ?
It seems more to be a database/doctrine issue rather than a sonata one.

**Comment by alfabetagama** [comment]
No custom query. It is standard admin with pager_type: 'simple'. I tested versions from 3.31 up and this behaviour was introduced in 3.34. I checked and doctrine/orm was fixed at 2.8.4 for all tested SonataDoctrineORMAdminBundle versions. 


This is a major issue for us, since all admin list performances are a bit degraded, depending on dataset size, for large datasets they are not usable.

**Comment by VincentLanglet** [comment]
> I tested versions from 3.31 up and this behaviour was introduced in 3.34.

Yes, but if I understand correctly, it doesn't work in 3.31 and it doesn't work for 3.34 so it's not a regression.

> This is a major issue for us, since all admin list performances are a bit degraded, depending on dataset size, for large datasets they are not usable.

Major issue or not, what I'm trying to understand is
- is it a regression (did it work before ?): I understand that this is not a regression.
- is it related to Sonata or Doctrine/Database: At first sight, it doesn't seem related to the sonata code directly

If the query is taking too much time, I assume doctrine provide some ways to improve the execution time.
I know that @franmomu is using fetch join for example.

**Comment by alfabetagama** [comment]
It does work in 3.33 and prior. 
It does not work in 3.34

It is a regression- it did work before.

**Comment by VincentLanglet** [comment]
@alfabetagama Did you try both 3.33 and 3.34 with the same other SonataAdmin version ? (3.99)
I want to be sure it's related to the 3.34 version.

Is it possible for you to try directly using commit of SonataDoctrineORM.
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/commits/3.x
Especially those:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/commit/7df241b051e526dd7b5192204d4c616acf306474
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/commit/ae31060db367ec84b31b6634516f96cdb431a008
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/commit/45550026d42de438fd5f1631fb1337cfb3afd7ce

I'd like to try to find which one is causing an issue.

Previously the Pager was doing
```
\count($paginator);
```
for the count.

Now it does 
```
\count($paginator->getIterator());
```
Maybe it's because of this.

**Comment by alfabetagama** [comment]
I will try to dig in and find out when exactly this was introduced.

In the mean time:

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/dbcfbba63e17f767adf6fd75d9f646a838b2a755/src/Datagrid/ProxyQuery.php#L223

I tested setting $fetchJoinCollection to false.  Results in much simpler query and normal response time.

`return new Paginator($query, false);`

Maybe this could be set to  false when using Simple Pager?

**Comment by VincentLanglet** [comment]
> In the mean time:
> 
> https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/dbcfbba63e17f767adf6fd75d9f646a838b2a755/src/Datagrid/ProxyQuery.php#L223
> 
> I tested setting $fetchJoinCollection to false. Results in much simpler query and normal response time.
> 
> `return new Paginator($query, false);`
> 
> Maybe this could be set to false when using Simple Pager?

You will lose the ability to use `fetch join` with simple pager. See https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/1403
That was what we were trying to fix in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1425

Prior to this fix, the Paginator were used for the `getCurrentResult` but not for the `countResult` ; and your issue seems like to be related to the count query.

Maybe @greg0ire @franmomu can help on this.
Seems like `new Paginator($query, true);` have worst performance than `new Paginator($query, false);` even if you don't use fetch join.

**Comment by VincentLanglet** [comment]
> In 3.34 it is a single query as follows:
> SELECT DISTINCT id_0, MIN(sclr_21) AS dctrn_minrownum FROM (SELECT c0_.id AS id_0 ......... c0_.duplicate AS duplicate_20, ROW_NUMBER() OVER(ORDER BY c0_.id DESC) AS sclr_21 FROM log c0_) dctrn_result GROUP BY id_0 ORDER BY dctrn_minrownum ASC LIMIT 251

@alfabetagama You're saying this query is taking too much time ?
What is the query you get in 3.33 ? I'd like to compare, since you're saying it works.

**Comment by alfabetagama** [comment]
Yes, i guess it would be best if user could decide to use fetch-join or not.

There is another related bug: 

https://github.com/sonata-project/SonataAdminBundle/blob/4c8311fc44affb6cd7170e42da741de94cf1231c/src/Datagrid/Pager.php#L236

haveToPaginate() for SimplePager always returns false so Paging interface is never shown.

**Comment by VincentLanglet** [comment]
Can you try https://github.com/sonata-project/SonataAdminBundle/pull/7181 @alfabetagama ?

**Comment by dmaicher** [comment]
I can confirm both issues.

@VincentLanglet https://github.com/sonata-project/SonataAdminBundle/pull/7181 fixes the pagination issue for me.

One of my apps is also affected by the performance issues since 3.34.0.

Loading the second page in the pagination takes 27sec on 3.34.0 and only 100ms on 3.33.0 due to the more complex query. For me the table holds roughly 10 million records.

So I think opting out of this should be possible to keep performance for large tables.

**Comment by alfabetagama** [comment]
@VincentLanglet I would argue that for SimplePager fetch-join should be set to false by default. I believe that for large datasets using simple pager was most popular way to keep UI responsive. If this changes and is overlooked by the users QA it may cause systems to become unresponsive and ultimately crash.

**Comment by VincentLanglet** [comment]
This post gives some informations https://github.com/EasyCorp/EasyAdminBundle/issues/1506#issuecomment-278590819
Also https://github.com/doctrine/orm/issues/8278#issue-705517756 is pretty useful.

We might try to improve the performance by checking for join, having, ... like EasyAdmin ; but it seems better to make the PR directly in doctrine.
