### ISSUE TITLE
Stop using DoctrineTestHelper in tests.

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataDoctrineORMAdminBundle#1460]
Since Symfony 5.3, the class `DoctrineTestHelper` is deprecated.
https://github.com/symfony/symfony/pull/39696

We should stop using it. Any idea how @sonata-project/contributors ?

**Comment by dmaicher** [comment]
Should be straightforward I think to remove the usages. I can take a look in the coming days
