### ISSUE TITLE
Composite keys and big table

### ISSUE THREAD

**Issue by hgfischer** [sonata-project/SonataDoctrineORMAdminBundle#153]
Hi,

I use Sonata Admin as framework for one website administration and I'm having problem in the list view of a new entity. We use Doctrine ORM with MySQL.

The entity is something like this: http://pastie.org/private/sgqzexzaaghnj33ty1fuw

Currently the table in MySQL has more than 100k rows and it's optimized for our use (composite index bucket+checksum).

When I open the Sonata Admin's list view for the entity, it keeps loading forever. Looks like it's trying to load the entire table in memory, even if I set maxPerPage to 10 in the admin class.

I looked into the logs and the last query in the log is to select ALL rows in the table's entity, without limits.

How can I fix this? Does Sonata Admin have some proper idiom to solve this kind of problem?

thanks!

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
