### ISSUE TITLE
Small contribution: JsonListFilter

### ISSUE THREAD

**Issue by lukepass** [sonata-project/SonataDoctrineORMAdminBundle#1596]
## Feature Request

Hello, yesterday I needed a filter to use with a JSON field (instead of a simple Doctrine array), something like this:

```
    /** @var string[] */
    #[ORM\Column(type: 'json')]
    protected array $roles = [];
```

I implemented it using JSON functions: https://packagist.org/packages/scienta/doctrine-json-functions

```
<?php

declare(strict_types=1);

namespace App\Filter;

use Sonata\AdminBundle\Filter\Model\FilterData;
use Sonata\AdminBundle\Form\Type\Filter\ChoiceType;
use Sonata\AdminBundle\Form\Type\Operator\ContainsOperatorType;
use Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQueryInterface;
use Sonata\DoctrineORMAdminBundle\Filter\Filter;

final class JsonListFilter extends Filter
{
    public function filter(ProxyQueryInterface $query, string $alias, string $field, FilterData $data): void
    {
        if (!$data->hasValue()) {
            return;
        }

        $value = $data->getValue();

        if (!\is_array($value)) {
            $data = $data->changeValue([$value]);
        }

        $operator = $data->isType(ContainsOperatorType::TYPE_NOT_CONTAINS) ? 'NOT ' : '';

        $andConditions = $query->getQueryBuilder()->expr()->andX();

        $parameterName = $this->getNewParameterName($query);
        $andConditions->add(sprintf('%sJSON_CONTAINS(%s.%s, JSON_ARRAY(:%s)) = 1', $operator, $alias, $field, $parameterName));

        $query->getQueryBuilder()->setParameter($parameterName, $value);

        if ($data->isType(ContainsOperatorType::TYPE_EQUAL)) {
            $parameterName = $this->getNewParameterName($query);
            $andConditions->add(sprintf('JSON_LENGTH(%s.%s) = :%s', $alias, $field, $parameterName));

            $query->getQueryBuilder()->setParameter($parameterName, \count($data->getValue()));
        }

        $this->applyWhere($query, $andConditions);
    }

    public function getDefaultOptions(): array
    {
        return [];
    }

    public function getRenderSettings(): array
    {
        return [ChoiceType::class, [
            'field_type' => $this->getFieldType(),
            'field_options' => $this->getFieldOptions(),
            'label' => $this->getLabel(),
        ]];
    }
}
```

What do you think?

Thanks.

**Comment by VincentLanglet** [comment]
Moving this to SonataDoctrineORMAdminBundle.

I would say any generic/simple filter is welcomed with appropriate tests if you want to make a PR :)

**Comment by jordisala1991** [comment]
The problem would be to add a dependency only for this filter. I would make it dev dependency and not register the filter unless it is present. Also we should take care of what dependencies we introduce... it has enough maintenance? or it will become a nightmare to maintain on the next 2 years?

Take into account that those json functions do not work on all databases. check the readme for compatibility.

**Comment by lukepass** [comment]
Yes, @jordisala1991 adding a new dependency could be a problem. What about adding a new part in the doc about creating a custom filter?

**Comment by jordisala1991** [comment]
That would be awesome, docs are always welcome :)

**Comment by lukepass** [comment]
Hello @jordisala1991 I added a pull request for the doc, please let me know if it's all ok!

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/compare/4.x...lukepass:patch-1

**Comment by VincentLanglet** [comment]
> Hello @jordisala1991 I added a pull request for the doc, please let me know if it's all ok!
> 
> [4.x...lukepass:patch-1](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/compare/4.x...lukepass:patch-1)

Hi @lukepass, seems like the PR is not opened

**Comment by lukepass** [comment]
Sorry I opened it :)
