### ISSUE TITLE
Error "No entity manager defined for class Doctrine\ORM\PersistentCollection"

### ISSUE THREAD

**Issue by mweimerskirch** [sonata-project/SonataDoctrineORMAdminBundle#160]
I have an entity with a OneToMany relation:

```
/**
 * @ORM\OneToMany(targetEntity="Time", mappedBy="version")
 */
public $times;
```

Adding it to an admin form using the default type works, so the relation is defined correctly.

However, adding it using type "sonata_type_model_list" is broken:

```
$formMapper->add('times', 'sonata_type_model_list')
```

I get the following error:

```
No entity manager defined for class Doctrine\ORM\PersistentCollection
```

Does anybody have an idea where this error comes from and how to solve it?

**Comment by y2keeper** [comment]
If it helps - you can now simply set multiple to true as pointed out here: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/164#issuecomment-42845727

**Comment by n-vlad** [comment]
> If it helps - you can now simply set multiple to true as pointed out here: [#164 (comment)](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/164#issuecomment-42845727)

With": 
`        "sonata-project/admin-bundle": "3.56",
        "sonata-project/doctrine-orm-admin-bundle": "3.12"`

This is no longer applicable, setting 'multiple' will end with an error:

`An error has occurred resolving the options of the form "Sonata\AdminBundle\Form\Type\ModelListType": The option "multiple" does not exist.`
