### ISSUE TITLE
doctrine_orm_date NOT NULL is not working properly

### ISSUE THREAD

**Issue by robertdolca** [sonata-project/SonataDoctrineORMAdminBundle#162]
doctrine_orm_date has an option 'is not empty'. That is not working (is ignored) if there is no date selected in the right side. Is this a bug?

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
