### ISSUE TITLE
No entity manager defined for class Doctrine\Common\Collections\ArrayCollection 

### ISSUE THREAD

**Issue by Raulken** [sonata-project/SonataDoctrineORMAdminBundle#164]
i try to use this tutorial of docrineadminbundle
http://sonata-project.org/bundles/doctrine-orm-admin/master/doc/tutorial/creating_your_first_admin_class/defining_admin_class.html

but return this error
No entity manager defined for class Doctrine\Common\Collections\ArrayCollection 

I did everything the same
why?

**Comment by Agroscopic** [comment]
Is this a normal behavior ? With @ihsanfaisal config I get a normal sonata_type_model and the button related to the sonata_type_model_list behavior. 
<img width="481" alt="capture d ecran 2015-09-08 a 10 13 27" src="https://cloud.githubusercontent.com/assets/13981509/9729793/4e100cd2-5612-11e5-928d-93c556499a7e.png">

If it is, then is it possible to 
1. Click add button and add a new user
2. Update the choices in the list to have the new user (Ajax request ?)
3. Automatically select the new user into the select list ?

Sorry if my english isn't good and if it's not the best place to ask that question :)
