### ISSUE TITLE
Unexpected token "name" of value "with" in form_admin_fields.html.twig

### ISSUE THREAD

**Issue by waiting-for-dev** [sonata-project/SonataDoctrineORMAdminBundle#166]
After upgrading to HEAD in symfony, following exception is thrown when rendering an edit form template:

    Unexpected token "name" of value "with" ("end of statement block" expected) in SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig at line 60

**Comment by Polo0032** [comment]
Thanks

**Comment by Soullivaneuh** [comment]
Fixed in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/commit/f184d9904a31e7046d1473859213e905418edcc8#diff-5f5bda65cf9656f611fe23e5e0f6beb8R60.

Closing.
