### ISSUE TITLE
Advanced filter is not working in 4.3.1

### ISSUE THREAD

**Issue by ggabrovski** [sonata-project/SonataDoctrineORMAdminBundle#1675]
After update from 4.3.0 to 4.3.1 the advanced filter option is not working.

**Comment by davidromani** [comment]
@ggabrovski check this https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1674

**Comment by VincentLanglet** [comment]
Can you try 4.3.2 ?

**Comment by ggabrovski** [comment]
ModelFilter and DateRangeFilter are working, but other like StringFilter or NumberFilter not show the advanced filter options. 

<img width="1175" alt="Screenshot 2022-07-21 at 23 28 56" src="https://user-images.githubusercontent.com/24413349/180310325-8bf3bc19-298e-440e-91bb-4ffa929141fe.png">

**Comment by VincentLanglet** [comment]
Oh, we only fixed DateFilters. 
Can you try https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1677 ?

**Comment by ggabrovski** [comment]
Thanks @VincentLanglet  I test it and is working as expected.
