### ISSUE TITLE
Doctrine ORM 3 support

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataDoctrineORMAdminBundle#1774]
Hi folks!

You may have noticed a couple beta releases of `doctrine/orm` :tada: 

https://github.com/doctrine/orm/releases/tag/3.0.0-beta2

We'd love to get feedback from you on this, please let us know if you encounter any difficulties integrating this with Sonata.

**Comment by VincentLanglet** [comment]
Friendly ping @sonata-project/core 

Do you still use this lib @dmaicher ?
I know you tried to start support for ORM 3 https://github.com/sonata-project/sonata-doctrine-extensions/pull/494

**Comment by dmaicher** [comment]
yes I will take a look 👍

**Comment by dmaicher** [comment]
Needs https://github.com/sonata-project/EntityAuditBundle/issues/591 and https://github.com/sonata-project/sonata-doctrine-extensions/pull/494 first

**Comment by dmaicher** [comment]
See https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1796#issuecomment-1962893002
