### ISSUE TITLE
ClassFilter has no possibility to change choice_translation_domain

### ISSUE THREAD

**Issue by BA-JBI** [sonata-project/SonataDoctrineORMAdminBundle#1779]
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/80f7b0e6281010b7587d5242c950b33357497e98/src/Filter/ClassFilter.php#L56-L68

There is no possibility to change choice_translation_domain in filter to any other domain than 'messages'

Thanks to making class final there isn't even a possibilty to override this
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/80f7b0e6281010b7587d5242c950b33357497e98/src/Filter/ClassFilter.php#L21

The ony chance i see is copy pasting stuff ... not cool

---

Could you think of making it possible to pass default field_options to the class or make them overridable?

**Comment by VincentLanglet** [comment]
Why specificly ClassFilter ; you don't have the issue with other filters ?

**Comment by VincentLanglet** [comment]
You should be able to pass

**Comment by VincentLanglet** [comment]
Hi @BA-JBI, I think https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1805 would solve your issue

**Comment by BA-JBI** [comment]
Hi @VincentLanglet 
Nice - thank you. 

> I think https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1805 would solve your issue

YES it does
