### ISSUE TITLE
doctrine_orm_date_range filter doesn't support 'single_text'

### ISSUE THREAD

**Issue by grichards** [sonata-project/SonataDoctrineORMAdminBundle#179]
nevermind, just noticed the 5th argument, sry

**Comment by webdevilopers** [comment]
Should be a problem again by now since the widget was removed:
https://github.com/sonata-project/SonataAdminBundle/issues/2148

Or how did your solution look like @grichards ?

**Comment by webdevilopers** [comment]
@grichards ?
