### ISSUE TITLE
Not useable with entities with constructor

### ISSUE THREAD

**Issue by KingCrunch** [sonata-project/SonataDoctrineORMAdminBundle#200]
Because of `Model\ModelManager:397` it is not possible to use it with entities, that have constructors with arguments

    public function getModelInstance($class)
    {
        return new $class;
    }

This should be possible somehow, because entities are a independent, that should be allowed to have a arbitrary constructor.

**Comment by aderuwe** [comment]
I would actually like a solution where we get complete control over entity creation - I really don't think that should be abstracted.

**Comment by GromNaN** [comment]
Have you tried overwriting the method `Admin::getNewInstance()` ?
https://github.com/sonata-project/SonataAdminBundle/blob/master/Admin/Admin.php#L1304-L1312

**Comment by aderuwe** [comment]
@GromNaN in my case, I need to pass to the constructor of the entity a field that is selected in the form for the entity (it's an immutable field and I'm trying to model that as closely as possible) - ```Admin::getNewInstance()``` happens way before the form is bound to the request.

**Comment by jsampedro77** [comment]
I have the same problem, and I am trying to solve it with the 'empty_data' option in the form. This way the object construction is delegated to the form.

[Symfony cookbook](http://symfony.com/doc/master/cookbook/form/use_empty_data.html#option-2-provide-a-closure)

My entity needs 3 arguments (code, name and start_at) in the constructor, and those values come from the form

So In my Admin class I add

```php
    public function getNewInstance()
    {
        return null;
    }

    public function getFormBuilder()
    {
        $this->formOptions['empty_data'] = function (FormInterface $form) {
            $class = $this->getClass();

            return new $class(
                null,
                $form->get('code')->getData(),
                $form->get('name')->getData(),
                $form->get('start_at')->getData(),
            );
        };

        return parent::getFormBuilder();
    }
```

At this point, there is a problem in CRUDController:createAction, because $object will be persisted, but its value will be null, so, in line 604 I have to set $object value this way

    $object = $form->getData();


I am still experimenting with this solution, because I expect some side efect with returning null in getNewInstance, but at this moment this is working and may be a base to support this behaviour.

**Comment by rande** [comment]
You can also check if the request is available in the Admin Instance and retrieve raw values from it. 

Tips: use ``$this->getUniqId`` to get the correct input value.

**Comment by jsampedro77** [comment]
That would be a good solution so getNewInstance will really do its job and return an object instance. I'll try that way and let you know.

**Comment by rande** [comment]
Closing this issue for now.

**Comment by ctrl-f5** [comment]
Returning null on `Admin::getNewInstance()` breaks the associations in the forms with the following error:

>An exception has been thrown during the rendering of a template ("Invalid argument, object or null required") in SonataDoctrineORMAdminBundle:CRUD:edit_orm_many_association_script.html.twig at line 255"

The template tries to access the subject's properties.

**Comment by aderuwe** [comment]
In an ideal world, ```Admin::getNewInstance()``` would actually be ```Admin::getNewInstance(FormInterface $form)``` and be abstract in ```Sonata\AdminBundle\Admin\Admin```. 
Sonata really shouldn't make assumptions about how our domain models are built.

**Comment by aderuwe** [comment]
@rande Looking in the request from ```Admin::getNewInstance()``` would bypass validation though, right? Although I guess if it still runs at a later point it should be ok ...

**Comment by oxidmod** [comment]
Any solution?

**Comment by core23** [comment]
Feel free to provide a fix for this @oxidmod 

ATM no one is working on this. This issue is closed

**Comment by torreytsui** [comment]
@core23 Do you think this can be an acceptable approach? If we are happy with it, I can create a PR with a proper solution.

```php
class FactorisedModelManager extends \Sonata\DoctrineORMAdminBundle\Model\ModelManager
{
    private $factoryByClass = [];

    public function addFactory($class, callable $factory)
    {
        $this->factoryByClass[$class] = $factory;
    }

    public function getModelInstance($class)
    {
        if ($factory = $this->factoryByClass[$class] ?? null) {
            return call_user_func($factory);
        } else {
            return parent::getModelInstance($class);
        }
    }
}
```

```xml
<service id="FactorisedModelManager" class="FactorisedModelManager">
    <call method="addFactory">
        <argument key="$class" type="string">EntityWithAParameterisedConstructor</argument>
        <argument key="$factory" type="expression">[ service('EntityWithAParameterisedConstructorFactory'), 'create' ]</argument>
    </call>
</service>
<service id="EntityWithAParameterisedConstructorFactory" class="EntityWithAParameterisedConstructorFactory" public=true">...</service>
```

**Comment by core23** [comment]
So, you need a special factory for every entity class? I'm not sure if this is a good solution.

You could use data mappers for entity creation: https://sonata-project.org/bundles/admin/3-x/doc/cookbook/recipe_data_mapper.html
The sensio labs team is also working on a general solution: https://github.com/sensiolabs-de/rich-model-forms-bundle
