### ISSUE TITLE
sonata_type_collection doesn't pick up "class" attr

### ISSUE THREAD

**Issue by tiagojsag** [sonata-project/SonataDoctrineORMAdminBundle#205]
Hi,

I have several sonata_type_collection fields in a single admin form, and I need different classes in it. I tried using the usual 'attr' => array('class' => 'foo') but it's not being rendered by the corresponding twig from SonataDoctrineORMAdmin

cheers

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.

**Comment by Mattabile** [comment]
The issue already exists :  "sonata-project/admin-bundle": "^3.4",
