### ISSUE TITLE
Error when I try to add sonata_type_model_list

### ISSUE THREAD

**Issue by spolischook** [sonata-project/SonataDoctrineORMAdminBundle#222]
Impossible to invoke a method ("id") on a NULL variable ("") in SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig at line 60

**Comment by nrodriguez-tupaca** [comment]
I have a similar problem here when using inherited classes that have ManyToOne relations to Media (from media bundle), so it already has an Admin class too.
Any workaround?

**Comment by Soullivaneuh** [comment]
This issue is old and not well filled.

Closing this one.

If the bug appear again on 3.x, feel free to open a new one.

**Comment by gvizquel** [comment]
Hello everyone. At this point I'm having the same problem using symfony 3 and sonata admin-bundle 3. Could anyone fix this? Thank you
