### ISSUE TITLE
sonata_type_model_list: Impossible to invoke a method ("id") on a NULL variable ("")

### ISSUE THREAD

**Issue by sandermarechal** [sonata-project/SonataDoctrineORMAdminBundle#252]
This may be related to #222.

I have a couple of entities with inheritance set up like so:

```
class My\Base

class My\Foo extends My\Base
    var $bar: Doctrine ORM many-to-one to My\Bar

class My\Bar
```

I have an Admin class that uses `setSubClasses` so I can manage all entities that extend `Base` using the same Admin class:

``` xml
    <service id="sonata.admin.myBase" class="My\BaseAdmin">
        <argument />
        <argument>My\Base</argument>
        <argument>SonataAdminBundle:CRUD</argument>
        <tag name="sonata.admin" manager_type="orm" />
        <call method="setSubClasses">
            <argument type="collection">
                <argument key="myFoo">My\Foo</argument>
                <argument key="myQuu">My\Quu</argument>
                <!-- ... -->
            </argument>
        </call>
    </service>
```

In my BaseAdmin I generate a form like this:

``` php
    protected function configureFormFields(FormMapper $formMapper)
    {
        // Add fields from My\Base
        // ...

        // Add fields from My\Foo
        if ($this->getSubject() instanceof MyFoo) {
            $formMapper->add('bar', 'sonata_type_model_list');
        }
    }
```

Now, when I create or edit an entity I get the following error:

```
Impossible to invoke a method ("id") on a NULL variable ("")
```

If I use a `sonata_type_model` instead of a `sonata_type_model_list` then it works. Also, if I move the `bar` property from My\Foo to My\Base it also works correctly. The error only appears when I use a model_list type for a relation that only exists in a subclass.

**Comment by nrodriguez-tupaca** [comment]
3 years later, I have the same issue here!
in reply to johannes85, my "Bar" entity is Media (from sonata-media-bundle), so it already has an admin class.

Did anyone solve this?

**Comment by Soullivaneuh** [comment]
> 3 years later, I have the same issue here!

Being sarcastic would not help at all.

Do you get this error with the 3.x version of this bundle? 2.x is not maintained anymore.

**Comment by gvizquel** [comment]
Hello everyone. At this point I'm having the same problem using symfony 3 and sonata admin-bundle 3. Could anyone fix this? Thank you

**Comment by quentinboudet** [comment]
Hi everyone, if it can help I had the same bug on symfony4 and resolved it simply by defining the 'admin_code' like this :
`
            $formMapper->add('lastFormResponse', ModelListType::class, [
                'class' => FormResponse::class,
            ], [
                'admin_code' => 'admin.form_response',
            ]);`

So it seems the Admin guesser of ModelListType doesn't work with complex relations, the only difference in my code is that 'lastFormResponse' get the last occurrence in an ArrayCollection.

ModelType maybe suffer the same bug, because the select work but the add button disappear, but not sure because 'admin_code' doesn't work this time.

**Comment by abouross** [comment]
if your target entity is "Media" then do not forget to specify "db_driver: doctrine_orm" in the configuration
