### ISSUE TITLE
Extremely slow performance on the pager

### ISSUE THREAD

**Issue by AndrewStarlike** [sonata-project/SonataDoctrineORMAdminBundle#297]
At this namespace Sonata\DoctrineORMAdminBundle\Datagrid there is a class "Pager". This class is responsible for the query that is used to create the pagination in Sonata Admin Bundle. We can see at line 38 this code: $countQuery->select(sprintf('count(DISTINCT %s.%s) as cnt', $countQuery->getRootAlias(), current($this->getCountColumn())));

The problem is that the word DISTINCT is used in building the query. If i remove DISTINCT the page loads twice as fast on a table with just a little above 300k rows. What is the need for DISTINCT in that query?

Please fix this massive performance issue or at least tell me a way to override the method that performs this query so i will still be able to use SonataDoctrineORMAdminBundle in my project.

Thank you.

**Comment by jdchmiel** [comment]
I found this very helpful to solve an issue where my admin entity was basically a shared primary key for relation tables.  The one to many + adding a group_concat doctrine extension and the required group by killed the pager. @zhil posted the exact solution I needed up above.
