### ISSUE TITLE
sonata_type_model_list not working

### ISSUE THREAD

**Issue by jontorrado** [sonata-project/SonataDoctrineORMAdminBundle#329]
Since the last commit, all my sonata_type_model_list fields appear empty when editing an entity. I just changed doctrine orm admin bundle to an older version and it started to work again. Something is not going good, can you check it? I think it has something to do with the "getEntityManager" change of the last commit.

**Comment by AlexL5** [comment]
I've got the same problem with 2.3.1. Work well from 2.2.7

**Comment by kunicmarko20** [comment]
Doesn't seem to be a problem:

![screenshot from 2018-02-25 19-50-35](https://user-images.githubusercontent.com/13528674/36645180-39cf9412-1a65-11e8-94b2-867f42459550.png)

Closing, ping me if still relevant.
