### ISSUE TITLE
proposal: case insensitive search on postgres

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataDoctrineORMAdminBundle#334]
for now, we do this:
https://gist.github.com/dbu/9524776#file-caseinsensitivestringfilter-php-L40

doctrine_orm_filter_types.xml add an option to configure the default
behaviour for sonata.admin.orm.filter.type.string
additionally, we could add an option to the filter to set it per case
(who knows, maybe i have one field where i really want case sensitive
filtering).

btw, one can achieve the opposite, make mysql case sensitive for likes
with  "column COLLATE utf8_bin LIKE :value" (resp = or NOT LIKE)

not sure how this is best modeled. if we don't care about BC, i would
say postgres should by default start to compare case insensitive. but
this would be very surprising for existing applications that rely on the
behaviour.

having 2 more ChoiceType options sounds like a bad idea too, it will
overkill for the admin user most of the time.

interested in a PR to add an option to the DI configuration to explicitly set case sensitivity (with 3 states: default, case-sensitive, case-insensitive), plus a per-filter option.

i don't know about other db than postgres + mysql, so i would throw an exception that this is not supported if an explicit option is set, so that people at least know something is not working.

**Comment by baptistedonaux** [comment]
+1

**Comment by mCzolko** [comment]
+1

**Comment by ruscon** [comment]
+1

**Comment by Nadrshin** [comment]
+1

**Comment by braianj** [comment]
+1

**Comment by kunicmarko20** [comment]
+1

**Comment by kunicmarko20** [comment]
@braianj @Nadrshin @ruscon @mCzolko @baptistedonaux instead of writing +1 what about providing a PR.

**Comment by braianj** [comment]
I have no idea how to do it, I'm new with sonata and got a lot of problems at the moment that I'm trying to solve. Make a +1 to get alive this issue. Thanks anyway

**Comment by greg0ire** [comment]
@braianj on one hand, don't do that please, but on the other hand: https://stackoverflow.com/questions/16247684/apply-custom-doctrine-output-walker-by-default-to-all-queries

**Comment by Nadrshin** [comment]
`case_sensitive` option in `StringFilter` works good. It is a pity that it is not possible to set default value `false` in global config.

**Comment by greg0ire** [comment]
@Nadrshin we accept PRs.
