### ISSUE TITLE
exception thrown when displaying a DateTime property of a related entity

### ISSUE THREAD

**Issue by xmak** [sonata-project/SonataDoctrineORMAdminBundle#347]
When trying to display a property of a related entity that is of type DateTime, a ContextErrorException is thrown:

``` PHP
Catchable Fatal Error: Object of class DateTime could not be converted to string in
```

The problem is that the template used for displaying the property (in my case `list_orm_one_to_one.html.twig`) uses the render_relation_element() operator which just returns the property and doesn't check its datatype.

The solution would be to use the teplates from SonataIntlBundle when available, like here:

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/2.0/DependencyInjection/SonataDoctrineORMAdminExtension.php#L114

In fact it would be better to render properties of related entities the same way as the properties of the main entity.

**Comment by cmanon** [comment]
I just ran into this issue @xmak have you solved it yet?

**Comment by chrisp1001** [comment]
Same thing here with Symfony 2.7 and latest SonataIntlBundle installed:

`An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class DateTime could not be converted to string") in SonataAdminBundle:CRUD:base_list.html.twig at line 30. `

Any ideas how to fix?

**Comment by Soullivaneuh** [comment]
@cmanon @chrisp1001 Which version of sonata bundles are you using? Could you please provide the result of `composer show sonata-project/*`?

Also the related admin and entity classes are needed to investigate.

**Comment by cmanon** [comment]
@Soullivaneuh I solved the issue it was actually an error on the entity I wanted to be edited here are the details [here](https://github.com/sonata-project/SonataAdminBundle/issues/3956).

**Comment by chrisp1001** [comment]
I also solved it by using this code snippet:

`->add('timestamp', 'datetime', array(
                'pattern' => 'yyyy-MM-dd HH:mm:ss',
                'locale' => 'en',
                ))`

This, however, will result in the error above:

`->add('timestamp', 'datetime')`

**Comment by jordisala1991** [comment]
Solved.
