### ISSUE TITLE
Pager computeNbResult $countQuery creates incorrect query

### ISSUE THREAD

**Issue by sleavitt** [sonata-project/SonataDoctrineORMAdminBundle#353]
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Datagrid/Pager.php#L38 reads currently:

$countQuery->select(sprintf('count(DISTINCT %s.%s) as cnt', $countQuery->getRootAlias(), current($this->getCountColumn())));

Should it not read instead as follows?:
$countQuery->select(sprintf('count(DISTINCT %s.%s) as cnt', $countQuery->getRootAlias(), current($this->getCountColumn())))->resetDQLPart('orderBy');

If the original query has an orderBy part attached to it, the resulting SQL generated for SQLite might look something like the following:

SELECT count(DISTINCT n0_.id) AS sclr0 FROM news__post n0_ LEFT JOIN news__post_tag n2_ ON n0_.id = n2_.post_id LEFT JOIN classification__tag c1_ ON c1_.id = n2_.tag_id AND (c1_.enabled = 1) LEFT JOIN fos_user_user f3_ ON n0_.author_id = f3_.id AND (f3_.enabled = 1) LEFT JOIN news__post_sites n5_ ON n0_.id = n5_.post_id LEFT JOIN page__site p4_ ON p4_.id = n5_.site_id AND (p4_.enabled = 1) WHERE (n0_.enabled = ? AND p4_.id IN (2)) AND n0_.type IN ('news') ORDER BY n0_.publication_date_start DESC

The SQLite query completes without any problem.

However, for SQL Server, it might look something like the following:

SELECT count(DISTINCT n0_.id) AS sclr0 FROM news__post n0_ WITH (NOLOCK) LEFT JOIN news__post_tag n2_ ON n0_.id = n2_.post_id LEFT JOIN classification__tag c1_ ON c1_.id = n2_.tag_id AND (c1_.enabled = 1) LEFT JOIN fos_user_user f3_ ON n0_.author_id = f3_.id AND (f3_.enabled = 1) LEFT JOIN news__post_sites n5_ ON n0_.id = n5_.post_id LEFT JOIN page__site p4_ ON p4_.id = n5_.site_id AND (p4_.enabled = 1) WHERE (n0_.enabled = 1 AND p4_.id IN (2)) AND n0_.type IN ('news') ORDER BY n0_.publication_date_start DESC;

And that yields the following error which is hardly useful:

SQLSTATE[HY000]: General error: 8127 General SQL Server error: Check messages from the SQL Server [8127](severity 16) [(null)]

However, when you run that query in SQL Server Management Studio against the database, you get the root cause of the problem:

Column "news__post.publication_date_start" is invalid in the ORDER BY clause because it is not contained in either an aggregate function or the GROUP BY clause.

And allowing an ORDER BY clause on a SELECT count(DISTINCT ...) query doesn't make sense to me anyways, so I think it's appropriate to reset it on the countQuery to prevent that error from occurring. I don't know what the SQL Standard mandates as being the correct behavior, but it is clear that SQLite and SQL Server handle that condition differently.

Let me know if it is desirable to have a PR, and I will see what I can do about it, but I wanted to raise awareness of it to see if it is in fact an issue.

Thanks!

**Comment by haydenk** [comment]
In addition to this, I am having a similar issue when using `HAVING` in the query.

```php
return $countQuery->resetDQLPart('orderBy')->getQuery()->getSingleScalarResult();
```

I noticed in the 2.3.0 tag, this was added for orderBy and when I tried doing

```php
$countQuery->resetDQLPart('having');
```

Just before the return, my query was able to work properly.

**Comment by jordisala1991** [comment]
This was fixed in: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/356

Closing.
