### ISSUE TITLE
Docs Improvement: adding choices to doctrine_orm_choice from ModelManager on DatagridFilters

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataDoctrineORMAdminBundle#381]
As an improvement to the docs here:

should I add an example how to populate choices from any Entity e.g.:

``` php
protected function configureDatagridFilters(DatagridMapper $datagridMapper)
{
    $builder = $this->getModelManager()->getEntityManager('MyBundle\Entity\Company')->createQueryBuilder();
    $companyResults = $builder->select('PARTIAL c.{id, name}')
        ->from("MyBundle\Entity\Company", 'c')
        ->getQuery()
        ->getArrayResult();

    $companyChoices = array();
    foreach ($companyResults as $companyRow) {
        $companyChoices[$companyRow['id']] = $companyRow['name'];
    }

    $datagridMapper
        ->add('company', 'doctrine_orm_choice', array(),
        'choice',
        array('choices' => $companyChoices)
        )
    ;
}
```

?

Mentioning that Array Hydration is recommended while `PARTIAL`s are optional

In addition we could an example of how to get the `Repository` of an `Entity`.
Something that was asked here:
- http://stackoverflow.com/questions/19857022/how-to-access-getdoctrine-in-call-backs-symfony2/25788155#25788155

Related:
- https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/145

**Comment by cassianotartari** [comment]
You can do:

```php

$choides[$company_id] = $company_name;
//....

->add('company', 'doctrine_orm_choice', array(
    'field_options' => array(
        'choices' => $choices,
        'required' => false,
        'multiple' => true,
        'expanded' => false,
    ),
    'field_type' => 'choice',
))
```

**Comment by core23** [comment]
Can't we pass a `QueryBuilder` to a filter instead of converting it to an array first? @webdevilopers

**Comment by kunicmarko20** [comment]
As there was no reply recently I will close it, feel free to open PR and improve docs.

**Comment by Zec2703** [comment]
@cassianotartari
Super ! It's exactly what I searched ! => **The parameter "field_options" for "datagripMapper"** !
On the official doc of "Symfony" (https://sonata-project.org/bundles/doctrine-orm-admin/3-x/doc/tutorial/creating_your_first_admin_class/defining_admin_class.html), it's just displayed :
protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('title')
            ->add('enabled')
            ->add('tags', null, ['field_options' => ['expanded' => true, 'multiple' => true]]);
    }

There are noting by default in the parameter 'field_options' !
I hate the official doc 👎

**Comment by kunicmarko20** [comment]
Instead of hating our official doc, maybe make a PR and improve them? :slightly_smiling_face:
