### ISSUE TITLE
Improvement: Allow mixed results for custom scalar values in list view

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataDoctrineORMAdminBundle#399]
As @rande mentioned answering a question by @tworzenieweb 
https://github.com/sonata-project/SonataAdminBundle/issues/1438
it is not possible to add aggregate columns to the `listView` by manipulating the `createQuery` method.

I've been thinking about this.

In issue https://github.com/sonata-project/SonataAdminBundle/issues/2334 I posted the following example:

``` php
    public function createQuery($context = 'list')
    {
        $query = parent::createQuery($context);

        $builder = $this->getModelManager()->getEntityManager('Sps\Bundle\BaseBundle\Entity\OfferStatusHistory')->createQueryBuilder();
        $builder->select($query->expr()->max('osh.createdAt'))
                ->from('Sps\Bundle\BaseBundle\Entity\OfferStatusHistory', 'osh')
                ->where('osh.offer = ' . $query->getRootAlias() . '.id');
        $currentStatusDql = $builder->getDql();

        $query->addSelect(
                'PARTIAL ' . $query->getRootAlias() . '.{id, number, date, name}',
                'PARTIAL sh.{id, createdAt}',
                'PARTIAL pqr.{id}',
                'c',
                'a',
                '(' . $currentStatusDql . ') AS current_state'
            )
            ->join($query->getRootAlias() . '.statusHistories', 'sh')
            ->leftJoin($query->getRootAlias() . '.priceQuoteRequest', 'pqr')
            ->leftJoin($query->getRootAlias() . '.customer', 'c')
            ->leftJoin('c.address', 'a')
         ;
    }
```

Which creates the following DQL:

``` sql
SELECT o,
PARTIAL o.{id, number, date, name},
PARTIAL sh.{id, createdAt},
PARTIAL pqr.{id},
c,
a,
(SELECT MAX(osh.createdAt) FROM Sps\Bundle\BaseBundle\Entity\OfferStatusHistory osh WHERE osh.offer = o.id) AS current_state,
PARTIAL p.{id},
PARTIAL pu.{id, username},
PARTIAL pc.{id, firstName, lastName}
FROM Sps\Bundle\BaseBundle\Entity\Offer o
INNER JOIN o.statusHistories sh
LEFT JOIN o.priceQuoteRequest pqr
LEFT JOIN o.customer c
LEFT JOIN c.address a
INNER JOIN o.partner p
INNER JOIN p.user pu
LEFT JOIN p.customer pc
WHERE o.deletedAt IS NULL
AND o.partner = 1
```

The error message I get is:
**An exception has been thrown during the rendering of a template ("Warning: get_class() expects parameter 1 to be object, array given ...) in SonataAdminBundle:CRUD:base_list_field.html.twig at line 12.**

If I understand this correctely this problem occurs because Doctrine will return a `mixed result` from the query since it is returnin an object AND a scalar value for the additional MAX.

Instead of parameter 1 being an object the array result will look something like this:

``` php

array
    [0]
        [0] => Object
        [1] => "some scalar string"
        ['num'] => 42
        // ... more scalar values, either indexed numerically or with a name
    [1]
        [0] => Object
        [1] => "some scalar string"
        ['num'] => 42
        // ... more scalar values, either indexed numerically or with a name
```

http://doctrine-orm.readthedocs.org/en/latest/reference/dql-doctrine-query-language.html#pure-and-mixed-results

I havn't found the responsible Hydration class in the bundle yet but maybe there is a way to change the hydration to check if the query returns the `mixed result` and then check `[0]` for the Object and add the desired `scalar values` to the `listView`?

Related issues:
- https://github.com/sonata-project/SonataAdminBundle/issues/1900
- https://github.com/sonata-project/SonataAdminBundle/issues/2334

**Comment by greg0ire** [comment]
I think a nice solution to this would be to integrate [Doctrine Data Transfer Objects](http://docs.doctrine-project.org/en/latest/reference/dql-doctrine-query-language.html#new-operator-syntax) with sonata. I tried that but encountered an error message because sonata looks for an entity manager for a DTO I created. @webdevilopers have you looked into this ?

**Comment by webdevilopers** [comment]
Thanks for commenting on this @greg0ire .
Actually I came up with a different solution already here:
https://github.com/sonata-project/SonataAdminBundle/issues/2334#issuecomment-66277287

I have no feedback yet from the contrbutors which solution would be best. But I think changing the Pager will be better that depending on an ORM returned result, right?

Maybe @pulzarraider, @Soullivaneuh or @rande could give us a short feedback on this.
I prefer to close this issue / solution and focus on the pager. Unless your *DTO* example could work as well.

**Comment by greg0ire** [comment]
Not completely sure it would work in your use case, but I managed to make it work in mine : 

I have a list of contracts, and want to display transactions that are linked to these contracts.

1. I create a `Contract` DTO
2. I override `Admin::createQuery` with the following :
```php
        $query->select("NEW MedNum\PortalBundle\DTO\Contract(
            $alias.id,
            COUNT(transaction)
        )")
            ->leftJoin("$alias.transactions", 'transaction')
            ->groupBy("$alias.id");

;
```
3. The pager count query breaks because of the group by, adding `$countQuery->resetDQLPart('groupBy')` in `Pager::computeNbResult()` solves the problem
4. To do links, I have to override `Admin::getUrlsafeIdentifier` and `Admin::getNormalizedIdentifier`:
```
    public function getUrlsafeIdentifier($entity)
    {
        return
            $entity instanceof DTOContract ?
            $entity->getId():
            parent::getUrlsafeIdentifier($entity);
    }

    public function getNormalizedIdentifier($entity)
    {
        return
            $entity instanceof DTOContract ?
            $entity->getId():
            parent::getNormalizedIdentifier($entity);
    }
```
I shall try to contribute something to remove the need for 3. and 4.

**Comment by greg0ire** [comment]
I created a specifc issue ( #501 ) if you're interested.

**Comment by maZahaca** [comment]
Do you have guys any update here?
I need to have 
* entity
* count(entity.related)

in the list view, is it possible for now?

**Comment by webdevilopers** [comment]
I switched to using read models without Sonata for list views @maZahaca .
The DTO attempt by @greg0ire in #501 is similar. Maybe it works out for you too.

**Comment by jordisala1991** [comment]
This is related to #501 

Im closing it as a duplicate, in order to centralize information and conversations. If you or @greg0ire think that this is not the same issue, please ping me to reopen or reopen :P
