### ISSUE TITLE
sonata_type_model_list select not working

### ISSUE THREAD

**Issue by sujayjaju** [sonata-project/SonataDoctrineORMAdminBundle#404]
The model pop up "Select" button to select existing entries does not do anything. 

Commenting the following lines in Resources/views/CRUD/edit_orm_many_association_script.html.twig fixes the issue
``` javascript
if (this.nodeName == 'A' && (target.attr('href').length == 0 || target.attr('href')[0] == '#')) {
    Admin.log('[{{ id }}|field_dialog_form_list_link] element is an anchor, skipping action', this);
    return;
}
```

**Comment by pulzarraider** [comment]
Fixed with #428. Thank you for reporting the issue.

**Comment by matlow** [comment]
thx sujayjaju

**Comment by kalouini-ats** [comment]
Any one knows how to fix this with ODM ?
