### ISSUE TITLE
Using array hydration for exports

### ISSUE THREAD

**Issue by uwej711** [sonata-project/SonataDoctrineORMAdminBundle#420]
Currently method getDataSourceIterator of class ModelManager uses object hydration which is a performance killer when exporting larger data sets. Why not use array hydration? 

Just add

```
$query->setHydrationMode(Query::HYDRATE_ARRAY);
```

in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Model/ModelManager.php#L426

before passing the query to the DoctrineORMQuerySourceIterator?

**Comment by rande** [comment]
This can be a solution, but there is another issue, the export does not work for large dataset as the mysql connection is buffered on the PHP side and not on the mysql site. This feature should use a specific mysql connection.
