### ISSUE TITLE
sonata.core.validator.inline

### ISSUE THREAD

**Issue by vvh-empora** [sonata-project/SonataDoctrineORMAdminBundle#421]
missing validator configuration ? here is the failure and the current workaround: 

https://groups.google.com/forum/#!topic/sonata-users/7NbJ_vCP9LY

some words to this failure ?

**Comment by rande** [comment]
@vvh-empora something is missing in the migration to the SonataCoreBundle. See related link @Shine-neko  should fix this issue.

**Comment by seb0zz** [comment]
Had the missing service bug as well. Now after the service is defined I receive the following error message when persisting an object.

    Catchable Fatal Error: Argument 1 passed to Sonata\AdminBundle\Admin\Admin::Sonata\AdminBundle\Admin\{closure}() must be an instance of Sonata\AdminBundle\Validator\ErrorElement, instance of Sonata\CoreBundle\Validator\ErrorElement given

**Comment by rande** [comment]
@seb0zz should be ok now. Thanks for reporting (fix by https://github.com/sonata-project/SonataAdminBundle/commit/fc2219a681f61104cfbc12e90721fffd13296bc0)

**Comment by Shine-neko** [comment]
@rande we update the documentation ?

**Comment by jordisala1991** [comment]
Fixed it seems
