### ISSUE TITLE
Attempted to call method "getPagerType"

### ISSUE THREAD

**Issue by remedge** [sonata-project/SonataDoctrineORMAdminBundle#424]
Hello, i am using symfony 2.6.* version and sonata-project/doctrine-orm-admin-bundle dev-master version.

After recent update i've got strange error - "Attempted to call method "getPagerType" on class "ClassName".

Exploring this gave me this BC-commit - https://github.com/sonata-project/SonataDoctrineORMAdminBundle/commit/c7401c469d63f8784d7c7263d38f9dba70ae96b9#diff-0a3e330ca56d0fe1096ad22b05768627

Quick-solution for me - is using last working version:
sonata-project/doctrine-orm-admin-bundle": "dev-master#e558d797cc8c995a54566ddb38d6042e74b5e674",

**Comment by pulzarraider** [comment]
Please do not mix the stable (`~2.3`) and unstable versions (`dev-master`) of SonataAdminBundle, SonataDoctrineORMAdminBundle, SonataCoreBundle. Use stable (tagged) versions of all bundles or use `dev-master` of SonataAdminBundle, SonataDoctrineORMAdminBundle, SonataCoreBundle if you want to try new features.

**Comment by remedge** [comment]
@pulzarraider thank you for clarification! That fix the problem.
