### ISSUE TITLE
Support for subclasses in sonata_type_model

### ISSUE THREAD

**Issue by lucasgranberg** [sonata-project/SonataDoctrineORMAdminBundle#426]
Having an entity with single table inheritance (or any other inheritance I believe) is currently not supported by the sonata_type_model_widget. The problem is that the "add new" button leads to a link that tries to create a new instance of the underlying abstract class. SonataAdminBundle has this sorted out in the template like this:
https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/Button/create_button.html.twig

To get it to work in my case I overrid the sonata_type_model_widget block and swapped the add button code with:

```twig
                {% if sonata_admin.edit != 'admin' and sonata_admin.field_description.associationadmin.hasRoute('create') and sonata_admin.field_description.associationadmin.isGranted('CREATE') and btn_add %}
                    {% if sonata_admin.field_description.associationadmin.subClasses is empty %}
                        <a  href="{{ sonata_admin.field_description.associationadmin.generateUrl('create', sonata_admin.field_description.getOption('link_parameters', {})) }}"
                                onclick="return start_field_dialog_form_add_{{ id }}(this);"
                                class="btn btn-success btn-sm btn-outline sonata-ba-action"
                                title="{{ btn_add|trans({}, btn_catalogue) }}"
                            >
                            <i class="fa fa-plus-circle"></i>
                            {{ btn_add|trans({}, btn_catalogue) }}
                        </a>
                    {% else %}
                        <div class="dropdown">
                            <button class="btn btn-success btn-sm btn-outline sonata-ba-action dropdown-toggle" type="button" id="sonata-ba-action-add-{{ id }}" data-toggle="dropdown" aria-expanded="true">
                                {{ btn_add|trans({}, btn_catalogue) }}
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="sonata-ba-action-add-{{ id }}">
                                {% for subclass in sonata_admin.field_description.associationadmin.subclasses|keys %}
                                    <li role="presentation">
                                        <a  href="{{ sonata_admin.field_description.associationadmin.generateUrl('create', sonata_admin.field_description.getOption('link_parameters',{})|merge({'subclass': subclass})) }}"
                                            onclick="return start_field_dialog_form_add_{{ id }}(this);"
                                            title="{{ btn_add|trans({}, btn_catalogue) }}"
                                                >
                                            {{ 'link_action_create'|trans({}, 'SonataAdminBundle') }} {{ subclass|trans({}, sonata_admin.field_description.associationadmin.translationdomain) }}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                {% endif %}
```

Original widget is in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Resources/views/CRUD/edit_orm_many_to_one.html.twig.

SonataAdmin has its button template in a separate file for easier reuse. Maybe SonataDoctrineORMAdminBundle could do the same or use some existing code from SonataAdminBundle.

Should I do a PR with the new code? Otherwise I could just leave this here as reference for others facing the same problem.

**Comment by tashanta** [comment]
I remember something i do a long time ago : https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/253
Maybe you can do something with it.

**Comment by lucasgranberg** [comment]
Yes, exactly that. I wonder why it never got merged. Now there is some conflicts but that was exactly what I meant.

**Comment by tashanta** [comment]
I plan to rebase this code if you are interested.

**Comment by lucasgranberg** [comment]
Very much so! I have noticed it wasn't as straight forward as I tought it would be. Especially if you use sonata_type_collection wich relies on jquery to get stuff inserted. Ping me if I can contribute in some way. Maybe I could test it on my project.

**Comment by andrewtch** [comment]
@tashanta , big + on this

**Comment by ixeft** [comment]
@tashanta I'm with you too !

**Comment by digitalkaoz** [comment]
++99 :)

**Comment by tashanta** [comment]
Look at this one sonata-project/SonataAdminBundle#2917. @core23 made something good.

**Comment by lucasgranberg** [comment]
Nice! Can't test it right now but it would probably fix my issue so Ill close this one.
