### ISSUE TITLE
Using Assert to validate Entities breaks creating new objects

### ISSUE THREAD

**Issue by Dragony** [sonata-project/SonataDoctrineORMAdminBundle#429]
Hello!

In my Project I validate my Entites like this:
http://symfony.com/doc/current/book/validation.html#constraint-configuration

Sadly when I create a new entity and the validation fails, the new form that is shown will point to /edit, instead of /create resulting in an error when i try to correct my input and submit again.

I tracked this error back to the following line being commented out. When i remove the comment it works as expected:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Model/ModelManager.php#L330

Versions:
  sonata-project/admin-bundle                2.3.1                MIT
  sonata-project/block-bundle                2.2.13               MIT
  sonata-project/cache                       1.0.4                MIT
  sonata-project/core-bundle                 2.3.0                MIT
  sonata-project/doctrine-orm-admin-bundle   2.3.0                MIT
  sonata-project/exporter                    1.3.4                MIT

A note on the side: Everytime validation fails on my object the Primary Key is auto incremented by one. I'm not sure if this is a Sonata problem or a SQL problem, but it seems unnecessary.

Best Regards

**Comment by Dragony** [comment]
Is now this line:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Model/ModelManager.php#L326

```
        // the entities is not managed
        if (!$entity /*|| !$this->getEntityManager($entity)->getUnitOfWork()->isInIdentityMap($entity) // commented for perfomance concern */) {
            return;
        }
```

**Comment by kunicmarko20** [comment]
Is this still an issue? I never encounterd:

>Sadly when I create a new entity and the validation fails, the new form that is shown will point to /edit, instead of /create resulting in an error when i try to correct my input and submit again.

will close it, if you have more info, ping me and I will reopen.
