### ISSUE TITLE
Attempted to call method "getPagerType"

### ISSUE THREAD

**Issue by Malstrom** [sonata-project/SonataDoctrineORMAdminBundle#430]

**Comment by pulzarraider** [comment]
Duplicate of #424.

Please do not mix the stable (~2.3) and unstable versions (dev-master) of SonataAdminBundle, SonataDoctrineORMAdminBundle, SonataCoreBundle. Use stable (tagged) versions of all bundles or use dev-master of SonataAdminBundle, SonataDoctrineORMAdminBundle, SonataCoreBundle if you want to try new features.
