### ISSUE TITLE
Bypass exception in ORM Form contractor

### ISSUE THREAD

**Issue by AntonioCS** [sonata-project/SonataDoctrineORMAdminBundle#432]
Hey,

I created a new field type and I am trying to use it in sonata. 
In one of my admin classes I have the following:

```
$formMapper
                    ->add('name', 'text')
                    ->add('img_home', new \MyBundle\Form\Type\ImageType(), array(
                        'required' => false,
                        'mapped' => false,
                        'label' => 'home set image',
                        'attr' => array('src' => '/' . $home)
                            )
                    )
```

When I do this on the img_home field I trigger this exception

'Please define a type for field ...'

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Builder/FormContractor.php#L56

If I comment out this exception everything works fine.
How can I fix this without having to change the code?

**Comment by pulzarraider** [comment]
[Create a service](http://symfony.com/doc/current/cookbook/form/create_custom_field_type.html#creating-your-field-type-as-a-service) from your `ImageType` object and use form type name as second parameter.

**Comment by AntonioCS** [comment]
Using the class works but yes I did fix it by passing in the 4th parameter, but the thing is the removing the exception didn't result in any issues when the rest of the code was executed. The file is not mapped so why is this going through the orm?

**Comment by jordisala1991** [comment]
This issue was about creating a field with a wrong type.

It was innitially solved by @pulzarraider with an explanation of how to create new form types. Even though the code is going to the orm, this does not mean you cant use fields not mapped to an entity.

Because of that Im closing this one.

Feel free to open a new issue if you still have a problem with this.
