### ISSUE TITLE
Wrong reference of admin-bundle

### ISSUE THREAD

**Issue by beccha** [sonata-project/SonataDoctrineORMAdminBundle#435]
On commit 4c7770d, in composer.phar:

"sonata-project/admin-bundle": "~2.3@dev"
"sonata-project/admin-bundle": "~2.4@dev",

Am I wrong to say the version ~2.4 of SonataAdmin does not exist? It breaks everything with composer...

**Comment by EmmanuelVella** [comment]
It's an alias for the dev-master branch

**Comment by beccha** [comment]
Ok, I did not see that but then why composer tells me that: 

sonata-project/doctrine-orm-admin-bundle dev-master requires sonata-project/admin-bundle ~2.4@dev -> no matching package found

Thanks.
