### ISSUE TITLE
Admin generator only taking fields but no associations

### ISSUE THREAD

**Issue by soyuka** [sonata-project/SonataDoctrineORMAdminBundle#443]
Hi,

On the admin generator, I was wondering why I had only the entity fields that aren't linked to another entity. 
I dig a bit and found that in the [ModelManager](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Model/ModelManager.php#L437) we have:

```
public function getExportFields($class)
    {
        $metadata = $this->getEntityManager($class)->getClassMetadata($class);
        return $metadata->getFieldNames();
    }
```

I just changed it to:
```
return array_merge($metadata->getFieldNames(), $metadata->getAssociationNames());
``` 

and magic happened. 
Would you like to see a PR on this or is it a wanted behavior?

Thanks!

**Comment by core23** [comment]
That is the expected behavior. You can only export the entities itself. Adding the children would create a hugh list on very complex relations with many associations.
