### ISSUE TITLE
sonata_type_collection inline not working with sonata_type_admin

### ISSUE THREAD

**Issue by alanpoulain** [sonata-project/SonataDoctrineORMAdminBundle#444]
Given the admin ParentAdmin with a field:

``` php
->add('children', 'sonata_type_admin', array(), array())
```

If a field in ChildrenAdmin has:

``` php
->add('grandChildren', 'sonata_type_collection', array(), array('edit' => 'inline'))
```

The POST made by the script in edit_orm_one_association_script.html.twig is:

(...)/core/append-form-field-element?code=(...).admin.parent&elementId=s552b9d322b723_children_grandChildren&uniqid=s552b9d322b723

Which is not working because:
- The admin is not the good one (it should be admin.children)
- The elementId corresponds to nothing in the FormBuilder (and the method appendFormFieldElement in AdminHelper throws an exception because $childFormBuilder is NULL)

**Comment by EnoahNetzach** [comment]
this happens because of a wrong array merge in `SonataDoctrineORMAdminBundle/Resources/views/CRUD/edit_orm_one_association_script.html.twig`
exactly at lines 38-44

```javascript
// the ajax post
jQuery(form).ajaxSubmit({
    url: '{{ url('sonata_admin_append_form_element', {
        'code':      sonata_admin.admin.root.code,
        'elementId': id,
        'objectId':  sonata_admin.admin.root.id(sonata_admin.admin.root.subject),
        'uniqid':    sonata_admin.admin.root.uniqid,
        'subclass': app.request.query.get('subclass'),
    } + sonata_admin.field_description.getOption('link_parameters', {})) }}',
```
where the order of the url arrays should probably be inverse.

**Comment by shaunbokes** [comment]
Up...
