### ISSUE TITLE
sonata_type_collection OneToMany sortable with Gedmo sortable

### ISSUE THREAD

**Issue by cacahouwete** [sonata-project/SonataDoctrineORMAdminBundle#451]
Hi,

I have a probleme when I have gedmo\sortable and when i want have my collection sortable with sonata_type_collection. I found the probleme in edit_orm_one_to_many.html.twig and solve it by an override but if it is possible, can you fix it in release or dev-master version ?

line 151 change jQuery(value).val(index + 1); by jQuery(value).val(index);
juste remove the +1.

(As you can see, my english is not very fluent, if you don't understand, tell me and i will try to say it in an other way)

thx

**Comment by oherzeas** [comment]
I'm having the same issue !

**Comment by caramba1337** [comment]
same issue for me as well

**Comment by OskarStark** [comment]
can someone provide a PR with a fix?
