### ISSUE TITLE
Working with doctrine ORM embeddables.

### ISSUE THREAD

**Issue by ruslan-polutsygan** [sonata-project/SonataDoctrineORMAdminBundle#453]
Hi
How to make `OrmAdminBundle` working with doctrine orm embeddable objects http://doctrine-orm.readthedocs.org/en/latest/tutorials/embeddables.html?
Using dot-notation(`profile.fullName`) triggers an error there - https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Model/ModelManager.php#L80 (since there is no `profile` association)

Any workaround is appreciated.

**Comment by ruslan-polutsygan** [comment]
related https://groups.google.com/forum/#!topic/sonata-users/NMhfd_-yxpY

**Comment by alahtarin** [comment]
Looks like OrmAdminBundle doesn't support embeddable objects. Any timelines on this?

**Comment by greg0ire** [comment]
See MR #483
