### ISSUE TITLE
Filter in Modals not working because of commit 09d2bb4

### ISSUE THREAD

**Issue by n3o77** [sonata-project/SonataDoctrineORMAdminBundle#454]
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/commit/09d2bb40343fb5069fb7a4254b79c31b189de994 from @pulzarraider 

This change leads to the problem that when using "sonata_type_model_list" in the popup the "Filter" dropdown can't be opened anymore and just loads the edit view again in the modal.

Not sure what the best fix for this is because I don't quite understand the problem this commit tries to fix. I reversed it and I still can select items in the list view.

**Comment by pzhuchkov** [comment]
The problem is still there. As he wrote @n3o77 problem file edit_orm_many_association_script.html.twig
```
jQuery('a', field_dialog_{{ id }}).not('.sonata-ba-action').on('click', field_dialog_form_list_link_{{ id }});
```
or
```
jQuery('a:not(".sonata-ba-action")', field_dialog_{{ id }}).on('click', field_dialog_form_list_link_{{ id }});
```

**Comment by Tetdoss** [comment]
I took 2 hours to find the reason of this error and find it comes from :

jQuery('a', field_dialog_{{ id }}).on('click', field_dialog_form_list_link_{{ id }}); in
edit_orm_many_association_script.html.twig

And then I found this issue.

I'll see if there is a more recent commit which fix it

**Comment by kunicmarko20** [comment]
If I understood correctly, you can't use filters when opening `list` option in form type `sonata_type_model_list`, I just tested and It works without a problem:

![screenshot from 2018-02-25 18-16-11](https://user-images.githubusercontent.com/13528674/36644279-03f39c9c-1a58-11e8-92b0-dacbdf9cf8e0.png)

If I didn't understand it well and this is still an issue, ping me and I will reopen.
