### ISSUE TITLE
Composite primary key entity and child admin

### ISSUE THREAD

**Issue by ruslan-polutsygan** [sonata-project/SonataDoctrineORMAdminBundle#455]
Hi,

I've got a problem when tried to use admin for entity with composite primary key as child admin. Specifically - action for create form gets built wrong.
Let's assume I have following entities

``` php
class A
{
    /**
     * @ORM\Id
     */
    protected $id;
}
class B
{
    /**
     * @ORM\Id
     */
    protected $id;
}
class AB
{
    /**
     * @var A
     *
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="A")
     */
    protected $a;

    /**
     * @var B
     *
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="B")
     */
    protected $b;

}
```

and admin classes (`ab` is a child of `a`)

``` php
class AAdmin extends Admin
{

}
class ABAdmin extends Admin
{
    public function getParentAssociationMapping()
    {
        return 'a';
    }
}
```

Form on the page `/admin/app/a/1/ab/create` has wrong action - `/admin/app/a/1/ab/1/edit` instead of `/admin/app/a/1/ab/create`.
Form action url depends on object id - https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/CRUD/base_edit_form.html.twig#L4
Eventually it gets into https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Model/ModelManager.php#L340 and https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Model/ModelManager.php#L283-L310
The problem is that AB instance passed into the form has already pre-set A instance, and therefore `$class->getIdentifierValues($entity)` returns array of one element (`a.id`) => `$identifiers` is not empty => `ModelManager::getNormalizedIdentifier` returns not null. 

In my case as workaround I've overridden `ABAdmin::id` method:

``` php
    public function id($entity)
    {
        if($entity->getA() && $entity->getB()){
            return parent::id($entity);
        }

        return null;
    }
```

But I think that above behavior is wrong. `AB` instance doesn't have primary key set, it is only half-set. And `Admin::id` has to return `null`.

I think it is better to get primary key field names first (`ClassMetadata::getIdentifierFieldNames`), and then to check if all the fields have value (`ClassMetadata::getIdentifierValues`). 
I can send pull request, but I'm not sure if this can impact anything else.

**Comment by Soullivaneuh** [comment]
I and sorry for the late answer.

> I can send pull request, but I'm not sure if this can impact anything else.

It would be great. :+1:

**Comment by jordisala1991** [comment]
Probably related to: https://github.com/sonata-project/SonataAdminBundle/issues/3330

Not closing for now, but there are a lot of issues related to composite primary keys, it would be super nice if someome could unify all the problems in one issue, because then we can see the whole picture at once.

**Comment by Soullivaneuh** [comment]
Was fixed and broken again. See #834 

You can stuck at v3.5 for now.
