### ISSUE TITLE
OrderBy with postgresql

### ISSUE THREAD

**Issue by j-hind** [sonata-project/SonataDoctrineORMAdminBundle#458]
I have a problem while trying to custom the createQuery in my admin class : 

An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT DISTINCT c0_.id AS id0, c0_.id AS id1 FROM crm_product_goodplan c1_ INNER JOIN crm_product_product c0_ ON c1_.id = c0_.id LEFT JOIN crm_product_establishment c2_ ON c0_.establishment_id = c2_.id LEFT JOIN crm_product_agent c3_ ON c0_.advisor_id = c3_.id WHERE c0_.endProductionDate >= ? ORDER BY c0_.endProductionDate ASC, c0_.id ASC LIMIT 32 OFFSET 0' with params ["2015-06-02"]:

SQLSTATE[42P10]: Invalid column reference: 7 ERREUR: pour SELECT DISTINCT, ORDER BY, les expressions doivent apparaître dans la
liste SELECT
LINE 1: ...c3_.id WHERE c0_.endProductionDate >= $1 ORDER BY c0_.endPro...
^") in SonataAdminBundle:CRUD:base_list.html.twig at line 33.

this is my function : 

```
public function createQuery($context = 'list')
{
    $query = parent::createQuery($context);
    $today = new \DateTime(); 
    $query->andWhere('o.endProductionDate >= :today')->setParameter('today', $today->format('Y-m-d'))->orderBy('o.endProductionDate', 'ASC');

    return $query;
}
```

relating to the issue #210

**Comment by j-hind** [comment]
@rande

**Comment by tape88** [comment]
+1

**Comment by axzx** [comment]
in mysql the error also occurs

**Comment by greg0ire** [comment]
Have you tried doing what the error message recommends?
