### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by nicwortel** [sonata-project/SonataDoctrineORMAdminBundle#465]
PR #446 seems to fix deprecation warnings caused by deprecated service configuration. However, no new version of SonataDoctrineORMAdminBundle has been released since the PR has been merged, so I still get those warnings every time I run `composer install` in my project.

Can you please release a new version of the bundle?

**Comment by Soullivaneuh** [comment]
@nicwortel Next release will be a new minor (2.4) and I think is not yet ready.

cc @rande

**Comment by Soullivaneuh** [comment]
Closing as 3.0 (old 2.4) is out now.
