### ISSUE TITLE
Enable translation of related elements e.g. using ManyToMany relation in list view

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataDoctrineORMAdminBundle#468]
Just discovered that my name columns from my entity in a ManyToMany relation are not being translated inside the `listView`.

The related twig extension and method `renderRelationElement` can be found in the `SonataAdminBundle` repo:
https://github.com/sonata-project/SonataAdminBundle/blob/master/Twig/Extension/SonataAdminExtension.php#L284

But I think it is a better practice to the translation inside the template of this bundle:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Resources/views/CRUD/list_orm_many_to_many.html.twig

**Comment by core23** [comment]
Can you provide a PR @webdevilopers ?

**Comment by jordisala1991** [comment]
Hard to understand this issue is.

Closing for now. If you want to reopen, please explain better what is currently wrong, and try to provide an stack trace too.

If any of the @sonata-project/contributors understands this, please reopen and explain if it is still relevant.
