### ISSUE TITLE
SimpleChoiceList class is deprecated

### ISSUE THREAD

**Issue by TheRatG** [sonata-project/SonataDoctrineORMAdminBundle#470]
\Sonata\AdminBundle\Form\ChoiceList\ModelChoiceList - cause this message

"SimpleChoiceList class is deprecated since version 2.7 and will be removed in 3.0. Use Symfony\Component\Form\ChoiceList\ArrayChoiceList instead."

**Comment by Soullivaneuh** [comment]
This issue is not related to DoctrineORMAdminBundle and is already under discussion here: https://github.com/sonata-project/SonataAdminBundle/pull/3022

**Comment by TheRatG** [comment]
Thanks
