### ISSUE TITLE
sonata_type_model_list delete option

### ISSUE THREAD

**Issue by egordanilenko** [sonata-project/SonataDoctrineORMAdminBundle#479]
When associated model not have DELETE route sonata_type_model_list not allow to set value to NULL:
sonata-project/doctrine-orm-admin-bundle/Resources/views/Form/form_admin_fields.html.twig

``` twig
<span class="btn-group">
                {% if sonata_admin.field_description.associationadmin.hasRoute('delete') and sonata_admin.field_description.associationadmin.isGranted('DELETE') and btn_delete %}
                    <a  href=""
                        onclick="return remove_selected_element_{{ id }}(this);"
                        class="btn btn-danger btn-sm sonata-ba-action"
                        title="{{ btn_delete|trans({}, btn_catalogue) }}"
                            >
                        <i class="fa fa-minus-circle"></i>
                        {{ btn_delete|trans({}, btn_catalogue) }}
                    </a>
                {% endif %}
            </span>
```

How relevant are test for the ability to remove at setting to NULL?

In our project we consciously disable remove entity (entity, not association with entity), but the opportunity to remove  association with the entity would leave.

sorry for my english/

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.

**Comment by kunicmarko20** [comment]
If I understood correctly and based on the text form the PR, the problem was that associated entity was not removed because there was no delete route on associated entity admin? Just tested and it works, not sure if this was ever related to us. If I am wrong, ping me and we will open it.
