### ISSUE TITLE
Enable the access of executable Query without execute it in ProxyQuery

### ISSUE THREAD

**Issue by jngermon** [sonata-project/SonataDoctrineORMAdminBundle#491]
To use a custom DataSourceIterator I have to use get the Query of `Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery`. But a `getQuery` on it give an uncomplete query. The complete one is build in the method `Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery:execute' but the Query is immediatly executed after built.
So, I propose this solution to enable the access of executable Query ot ProxyQuery :
```php
    /**
     * {@inheritdoc}
     */
    public function execute(array $params = array(), $hydrationMode = null)
    {
        return $this->getExecutableQuery()->execute($params, $hydrationMode);
    }

    public function getExecutableQuery()
    {
        // always clone the original queryBuilder
        $queryBuilder = clone $this->queryBuilder;

        // todo : check how doctrine behave, potential SQL injection here ...
        if ($this->getSortBy()) {
            $sortBy = $this->getSortBy();
            if (strpos($sortBy, '.') === false) { // add the current alias
                $sortBy = $queryBuilder->getRootAlias() . '.' . $sortBy;
            }
            $queryBuilder->addOrderBy($sortBy, $this->getSortOrder());
        } else {
            $queryBuilder->resetDQLPart('orderBy');
        }

        return $this->getFixedQueryBuilder($queryBuilder)->getQuery();
    }
```
I have just split the method to build the query in separate method (and use this method in `execute' method).

Do you think that it's the right solution ?
Do you want that I do the contribution ?

Thank you

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
