### ISSUE TITLE
stable release for filter autocomplete type

### ISSUE THREAD

**Issue by ElectricMaxxx** [sonata-project/SonataDoctrineORMAdminBundle#493]
Is it possible to put 
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/commit/717fc63467dc1a517a7cdd69760b65d960bb50eb

into a release to use it? Or is it planned for a 2.4 version aligned with sonata-admin main bundle?

**Comment by OskarStark** [comment]
ping @Soullivaneuh I don't know whats the plan for releases currently is

**Comment by ElectricMaxxx** [comment]
if tried to fork the repo and picked the commit on
https://github.com/mayflower/SonataDoctrineORMAdminBundle and tagged
2.3.4 there, but got other problems on missing options (`admin_code`).
So i would be very happy to get your release.

Am 08.10.2015 um 09:38 schrieb Oskar Stark:

**Comment by Soullivaneuh** [comment]
It's planned, but no date for the moment.

**Comment by ElectricMaxxx** [comment]
can't you put that feature in a single minor-release?


Am 08.10.2015 um 09:55 schrieb Sullivan SENECHAL:

**Comment by Soullivaneuh** [comment]
> can't you put that feature in a single minor-release?

Not sure if I understood well, but for the moment, no.

I have some idea to propose in order to push minor releases faster but for the moment, we have to stabilize this before.

If you really need this feature, then use `~2.4@dev`.

**Comment by ElectricMaxxx** [comment]
This would force me to use SonataAdmin in `2.4@dev` which is not production ready, right?

**Comment by ElectricMaxxx** [comment]
@Soullivaneuh do you have a hint for me which commit to use, when i wanna keep SonataAdmin 2.3 and use the auto_complete commit?

**Comment by Soullivaneuh** [comment]
> This would force me to use SonataAdmin in 2.4@dev which is not production ready, right?

Yes.

> @Soullivaneuh do you have a hint for me which commit to use, when i wanna keep SonataAdmin 2.3 and use the auto_complete commit?

I don't know, maybe the commit you put on this ticket.

But you might have huge conflicts because sadly, 2.3 and 2.4 have some BC break changes.

I'll ensure that will be never like this again. :-)

**Comment by ElectricMaxxx** [comment]
yea i feel it now :-(

`` 
        "sonata-project/admin-bundle": "2.3.2 as 2.4.0",
       "sonata-project/doctrine-orm-admin-bundle": "dev-master#4fcec62fab9487c5479519f5d663c3d1d588a10f",
`` 

simply tried not the last commit (the last used the LockInterface), but this one is failing too. 

It will be hard now ...

**Comment by ElectricMaxxx** [comment]
yea ...

I started to simply copy the code from the commit mentioned above to get a autocomplete Filter. But i have got an issue with the formType which is rendered. Unfortuneately the form is rendered as simple   `form_widget` instead of `sonata_model_autocomplete_widget`. Just run the debugger throug the form rendering and realized that the resource match is done by a so called `blockHierarchy`, which is filled by the the `$vars`. 

So can anybody (@OskarStark @Soullivaneuh) give me a hand what is currently wrong?

**Comment by ElectricMaxxx** [comment]
maybe my friend @dbu can give me a hand in here?

**Comment by pulzarraider** [comment]
@ElectricMaxxx 'doctrine_orm_model_autocomplete' cooperate with `sonata_type_model_autocomplete` form type from SonataAdminBundle. In current dev-master of SonataAdminBundle (planed 2.4) was the form type refactored. So if you want to use `doctrine_orm_model_autocomplete`, you should use it with correct version of SonataAdminBundle (or use your fork, too).

In my opinion, the `dev-master` of SonataDoctrineORMAdminBundle is quite stable to use it.

**Comment by ElectricMaxxx** [comment]
@pulzarraider that stable to use it in production with a release in the next 6 weeks?

**Comment by core23** [comment]
We have some stable releases
