### ISSUE TITLE
Incorrect count query for entities with complex primary key.

### ISSUE THREAD

**Issue by skobkin** [sonata-project/SonataDoctrineORMAdminBundle#497]
I've got bad behavior of [`Pager`](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/76100a375997a8151fcb6f436be1f30b3f1c1339/Datagrid/Pager.php#L23) when working with Entities with complex primary key.

[`computeNbResult()`](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/76100a375997a8151fcb6f436be1f30b3f1c1339/Datagrid/Pager.php#L30) method counts table entries only by one `DISTINCT` field.

``` php
$countQuery->select(sprintf('count(DISTINCT %s.%s) as cnt', $countQuery->getRootAlias(), current($this->getCountColumn())));
```

But if this field is not unique attribute of entry, `COUNT()` result will be wrong.

**Comment by till** [comment]
Related: #501 

I think instead of fixing all these edge cases, the framework should support a straight forward way to  inject a custom `Pager`.

**Comment by skobkin** [comment]
It's a good idea I think. It may give an opportunity to inject some less universal but more functional pager which is oriented for some DBMS like PostgreSQL and able to do SELECT DISTINCT on multiple columns.

**Comment by Nadrshin** [comment]
This bug is still relevant. Pager considers only first column from complex primary key https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.13.0/src/Datagrid/Pager.php#L45
