### ISSUE TITLE
Filter Field: doctrine_orm_callback

### ISSUE THREAD

**Issue by sebastianblum** [sonata-project/SonataDoctrineORMAdminBundle#5]
Dear Sonata Team,

I'am working with Admin Bundle and created own Filter Fields using doctrine_orm_callback.

If I follow the instructions on http://sonata-project.org/bundles/admin/master/doc/reference/filter_field_definition.html,
the Filter will be executed every time with the checkbox is checked.

protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
                        ->add('with_open_comments', 'doctrine_orm_callback', array(
                'callback'   => array($this, 'getWithOpenCommentFilter'),  
                'field_type' => 'checkbox'
            ))
        ;
    }

```
public function getWithOpenCommentFilter($queryBuilder, $alias, $field, $value)
{

    // FOR DEBUGGING
    print_r($value);

    if (!$value) {
        return;
    }

    $queryBuilder->leftJoin(sprintf('%s.comments', $alias), 'c');
    $queryBuilder->andWhere('c.status = :status');
    $queryBuilder->setParameter('status', Comment::STATUS_MODERATE);
}
```

---

If you debug the value of $value, you get the following Output:

not checked checkbox:
Array ( [type] => ) 

checked checkbox:
Array ( [type] => [value] => 1 ) 

---

So 
  if (!$value) {
            return;
        }
does not work and the Filter will always been active.

In my opion $value should be null the checkbox is not checked.

**Comment by webdevilopers** [comment]
If you have choices with `0` as option values it is better to use `isset`:
```php
if (!$value['value']) { return; } // will return if value is set to 0 which will be interpreted as false
if (!isset($value['value'])) { return; } // best practice
```

Confirm @pulzarraider ? I will update the docs then.
