### ISSUE TITLE
One-To-Many and sonata_type_collection - not adding related entity

### ISSUE THREAD

**Issue by andrewtch** [sonata-project/SonataDoctrineORMAdminBundle#50]
Hi, I've two entities. connected via one-to-many. Editing 'one' entity I've sonata_type_collection fileds displaying 'Many' entities. Thanks to orphanRemoval and `modifiable => true` I can remove related entitites. When I press '+', I can add 'Many' entities, but Sonata doesn't set parent entitiy (in my case, transaction_id is always NULL). What am I doing wrong?

**Comment by k-alex** [comment]
I did a workaround using prePersist and preUpdate 

class ResultAdmin extends Admin {
//-----stuff------
-----stuff----
---stuff--
//
    protected function configureFormFields(\Sonata\AdminBundle\Form\FormMapper $formMapper) {
$formMapper
//-------stuff-------//
->add('images', 'sonata_type_collection', array(), array(
                    'edit' => 'inline',
                    'inline' => 'table',
                    'sortable' => 'position',
                ))
//-----stuff-----//
}
    public function prePersist($object) {
        $images = $this->getForm()->get('images')->getData();
        foreach ($images as $image) {
            $image->setResult($object);
        }
    }

    public function preUpdate($object) {
..//same//..
    }

**Comment by idchlife** [comment]
Well, guys, in my situation, I had few entities, so I just made ManyToMany and inversedBy on the side, where I previously wrote OneToMany, it worked without any additional tweaks.

**Comment by georgie123** [comment]
Hello

Just adding this in my Admin class controller, under my **configureFormFields** function, has solved:

`<?php
public function preUpdate($object)
    {
        foreach ($object->getAddress() as $address) {
            $address->setCustomer($object);
        }
    }`

Where **getAddress** is my collection from my Customer entity.

Thanks **andrewtch**!
