### ISSUE TITLE
Listings, GROUP BY and DTOs

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataDoctrineORMAdminBundle#501]
At the moment, it seems that adding aggregate fields to a listing line is not
possible / not easy, because of the two following problems:
1. Sonata does not deal with mixed results
2. The pager does not reset the group by part of the query if there is one.

To solve 1. , I have been using
[DTOs](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#new-operator-syntax),
a feature that exists since doctrine 2.4 . DTOs are simple data bags that
should look like a line of the listing. Let's take an example to see how they
can be used.

Let's imagine a `Team` entity, that has Users. Let's imagine we want to have a
listing for the `Team` entity, and we want to display the number of users in
the team along with the name of the team.

We can create the following DTO

``` php
<?php
namespace MyCompany\MyProjectBundle\DTO;

class Team // if you have many fields, extending the Team entity might be a good move…
{
    public $id; // it's a data bag. Let's not worry with encapsulation
    public $name;
    public $userCount;

    public function __construct($teamId, $name, $userCount)
    {
        $this->teamId = $teamId;
        $this->name = $name;
        $this->userCount = $userCount;
    }
}
```

Now, in `TeamAdmin`, let's tweak the listing query to use our newly-created DTO :

``` php
<?php
namespace MyCompany\MyProjectBundle\Admin;

use Sonata\AdminBundle\Admin\Admin;

class TeamAdmin extends Admin
{
    public function createQuery($context = 'list')
    {
        $query = parent::createQuery($context);
        $alias = $query->getRootAliases()[0];

        $query->select("NEW MyCompany\MyProjectBundle\DTO\Team(
            $alias.id,
            $alias.name,
            COUNT(*)
            )")
            ->leftJoin("$alias.users", 'user')
            ->groupBy("$alias.id");
    }

    public function getUrlsafeIdentifier($entity)
    {
        return
            $entity instanceof DTOTeam ?
            $entity->id:
            parent::getUrlsafeIdentifier($entity);
    }

    public function getNormalizedIdentifier($entity)
    {
        return
            $entity instanceof DTOTeam ?
            $entity->id:
            parent::getNormalizedIdentifier($entity);
    }
}
```

Notice how you have to override the two last methods if you want to be able to
generate links to your objects.

To solve 2. … see [this issue](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/297). I did something similar, and reset the group by part of the query.

@rande, @Soullivaneuh , @OskarStark what do you think ? How could this be integrated in Sonata? Tell me, I am ready to contribute that. For starters, I think there could be an interface that DTOs could implement to provide : 
- an url safe identifier
- a normalized identifier (I don't know what the difference is).

Second, maybe the groupby part could be reset every time, regardless of whether it exists or not ?

**Comment by till** [comment]
@greg0ire I had a similar problem with sonata and this effectively helped me get all required values into a row without doing an extra n-queries per result. :) Thank you so much for posting this!

**Comment by greg0ire** [comment]
@till : glad to read that! If this proves useful to many people, it will probably be worth integrating in Sonata. I think DTOs are great as soon as things get complicated like with aggregates. I suppose you had some aggregation function in your query, didn't you ?

**Comment by till** [comment]
@greg0ire Well, I am torn. DTOs seem like yet another layer to hide the actual SQL table but they worked surprisingly well (for a first attempt anyway)! So kudos to you for pointing this out.

After extending my DTO I noticed that this only works to a _certain_ extend. I am doing a count with a join on another table and a group by to aggregate numbers in the list view. I actually wanted to do more but it gets a little crazy. So I am sticking with the single aggregate for now.

Anyway, the Pager somewhere in sonata-doctrine-orm-admin-bundle now fails depending on how I built my query. So in this case, I had an additional `GROUP BY` which caused havoc. In theory the `LEFT JOIN` could also screw things up so I think I just got lucky that the numbers just add up.

The error is a `NonUniqueResultException` which I  managed to solve by e.g. using `resetDQLPart('groupBy')` to on the `$countQuery` in `Pager::computeNbResult()`. 

Related ticket seems closed already: sonata-project/SonataDoctrineORMAdminBundle#297

I think I need to figure out how to inject override the Pager now to perm fix it.

**Comment by greg0ire** [comment]
> I think I need to figure out how to inject override the Pager now to perm fix it.

Yeah I ran into that too (that's what I called problem 2).

At the end of my post, there is [a link](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/297) showing how to do that.

**Comment by till** [comment]
@greg0ire yeah, wrapping my head around xml-based DI as I write this.

I still think there needs to be a more straight forward way to inject a custom pager without building 2-3 objects around it.

Especially given that sonata suggests that users override `createQuery()` to customise data, allowing a custom pager seems straight forward to me also. At least it seems like that a customised `createQuery` leads to all sorts of edge cases and problems with the code inside the `Pager`.

I am also not sure if I want to maintain these wrapper objects and deal with the breakage that comes when I update sonata?

So (TL;DR), not sure if e.g. more `resetDQLPart()` is the way to go or if a `setPager` somewhere would be better. Kind of wondering if I should PR either?

**Comment by greg0ire** [comment]
Not having to override a chain of objects each time you need a different pager would definitely be a plus. About the PR(s) it would be great to have some feedback from the maintainers first. Let's wait…

**Comment by till** [comment]
Okay, so that part worked.

Adding this here as the other issue is already closed and since it seems to have changed a little since others shared their solution there: I added custom `Pager` and `DatagridBuilder` objects into my namespace and extended as little as possible. Last but not least I added the following to my own `services.yml`:

```Yaml
services:
    sonata.admin.builder.orm_datagrid:
        class: MyNamespace\AdminBundle\Builder\DatagridBuilder
        arguments: ["@form.factory", "@sonata.admin.builder.filter.factory", "@sonata.admin.guesser.orm_datagrid_chain", "%form.type_extension.csrf.enabled%"]
```

And now, thinking that when I have `list` adjusted to my liking, the exporter would also use my _customized query_ and DTO, I was wrong. On to the next round to find out what I have to override in order to get that working.

**Comment by greg0ire** [comment]
I had to do that too, and here is how I solved it :

```
<?php
    /**
     * The select clause is overwritten in ModelManager::getDataSourceIterator()
     * and we do not want that. Plus, we cannot use the doctrine iterator because
     * there is a fetch join in the query, and this is not supported for iteration.
     * Luckily there are not so many results and fetching all the data is still
     * performant. This is what DTOSourceIterator does.
     */
    public function getDataSourceIterator()
    {
        $datagrid = $this->getDatagrid();
        $datagrid->buildPager();

        $query = $datagrid->getQuery();


        $query->addOrderBy($query->getSortBy(), $query->getSortOrder());

        $query = $query->getQuery();

        // Override : always export everything, because it is the expected behavior
        $query->setFirstResult(0);
        $query->setMaxResults(null);

        $contracts = $query->execute(null, \Doctrine\ORM\Query::HYDRATE_ARRAY);

        return new DTOSourceIterator($contracts, $this->getTranslator());
    }

namespace MedNum\PortalBundle\Datagrid;

use Exporter\Source\SourceIteratorInterface;
use Sonata\AdminBundle\Admin\FieldDescriptionCollection;
use Symfony\Component\Translation\Translator;

abstract class DataSourceIterator implements SourceIteratorInterface
{
    protected $position = 0;
    protected $query;
    protected $items;
    protected $columns;
    protected $translator;
    protected $pageSize;

    public function __construct(
        ProxyQuery $query,
        FieldDescriptionCollection $columns,
        Translator $translator = null,
        $pageSize = 0
    ) {
        $this->query = $query;
        $this->columns = $columns;
        $this->translator = $translator;
        $this->pageSize = $pageSize;
    }

    abstract protected function buildPage($page);

    public function rewind()
    {
        $this->position = 0;
    }

    public function current()
    {
        $item = $this->getItem($this->position);
        $data = []; // The returned dictionary

        foreach ($this->columns->getElements() as $column) {
            if (isset($this->translator)) {
                $translatedLabel = $this->translator->trans(
                    $column->getLabel(),
                    [],
                    $column->getTranslationDomain()
                );
            } else {
                $translatedLabel = $column->getLabel();
            }

            $data[$translatedLabel] = $column->getValue($item);
        }

        return $data;
    }

    public function key()
    {
        return $this->position;
    }

    public function next()
    {
        ++$this->position;
    }

    public function valid()
    {
        return $this->getItem($this->position) !== null;
    }

    protected function getItem($position)
    {
        if ($this->items === null) {
            $this->items = [];
        }

        if ($this->pageSize > 0) {
            $page = (int) floor($position / $this->pageSize);
            $pagePosition = $position % $this->pageSize;
        } else {
            $page = 0;
            $pagePosition = $position;
        }

        if (!isset($this->items['page_' . $page])) {
            $this->items['page_' . $page] = $this->buildPage($page);
        }

        if (isset($this->items['page_' . $page][$pagePosition])) {
            return $this->items['page_' . $page][$pagePosition];
        }

        return null;
    }
}

```

**Comment by till** [comment]
@greg0ire Thanks, I ended up with this:

```php
    public function getDataSourceIterator()
    {
        $proxyQuery = $this->createQuery('list');

        /** @var \Doctrine\ORM\QueryBuilder $qb */
        $qb = $proxyQuery->getQueryBuilder();

        $qb
            ->setFirstResult(null)
            // no, no, no, no - no, no there's no limit
            ->setMaxResults(null)
        ;

        $query = $qb->getQuery();
        $dtos = $query->execute(null, \Doctrine\ORM\Query::HYDRATE_ARRAY);

        $iterator = new DTOIterator(
            $dtos,
            $this->getExportFields()
        );

        return $iterator;
    }
```

My `DTOIterator` is also very simple (for now), mostly wraps around the array and returns items.

**Comment by greg0ire** [comment]
> // no, no, no, no - no, no there's no limit

I agree : 

> // Override : always export everything, because it is the expected behavior

Why would anyone want to export only the current page ? For performance reasons, maybe ? Anyway, it looks weird that there is no easy option to change from one behavior to another.

As per the iterator, I was wrong, this is not the iterator I'm using, I will update the sample code right away, it is far more simple.

**Comment by till** [comment]
Haha, yeah... I think YMMV basically.

From what I gathered in-house, people always want everything. But there's also a use-case when people trim down a result with a bunch of filters and what not and only want to export the current result maybe?

**Comment by greg0ire** [comment]
Yeah sure. I think it's really not the main use case though, but since it can have performance issues, they probably decided to go with the other use case.

**Comment by till** [comment]
You are probably right!

Anyway. I wonder how we can integrate DTOs into sonata to make this less hack for the next person around. But I am not sure who the contributors are that need to add their thoughts.

**Comment by greg0ire** [comment]
@OskarStark @Soullivaneuh @pulzarraider or @rande I think. Woops, did I just ping them ? :angel:

**Comment by greg0ire** [comment]
Dear maintainers, can you please give us some feedback ? I'm willing to contribute but I'm reluctant to do so without feedback first, just to see if this is something that might be merged.

**Comment by skobkin** [comment]
up?

**Comment by icedevelopment** [comment]
Having proper support for Doctrine DTOs in Sonata would be a **very** interesting feature.

Maintainers can you please give us your opinion on this?

**Comment by greg0ire** [comment]
Related, but even lower level : https://qafoo.com/talks/15_09_symfony_live_london_doctrine2_to_use_or_not_to_use.pdf

**Comment by firestorm23** [comment]
How do you manage to implement DTO in query with Sonata in the first place? I tried doing that, but Sonata asks for Model Manager for that DTO, which I dont have, cause this DTO obvoiusly not mapped with Doctrine.

**Comment by greg0ire** [comment]
@firestorm23 see my first post, there is a detailed implementation.

**Comment by greg0ire** [comment]
@firestorm23 did you implement `getNormalizedIdentifier` properly?

**Comment by Chemaclass** [comment]
up?

**Comment by vytsci** [comment]
Sonata works in so retarded way, that it fetched all fields from entity executing all lazy loads and my simple admin with few joins ends up in a 35k queries.

**Comment by Soullivaneuh** [comment]
> Sonata works in so retarded way

Feel free to contribute and make it less retarded. :+1:

**Comment by vytsci** [comment]
> > Sonata works in so retarded way
> 
> Feel free to contribute and make it less retarded. +1

Yes I will when the right time comes, Im not confident enough to make it better, but I see problems that`s the start. But I have a list of extensions Ive made, I will refine them properly and make a PR.

**Comment by icedevelopment** [comment]
> > Sonata works in so retarded way
> 
> Feel free to contribute and make it less retarded. 👍

@Soullivaneuh While you are here, what are your thoughts regarding @greg0ire 's post on this issue? (see https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/501#issuecomment-158103483)

**Comment by rande** [comment]
@vytsci there is no magic; if you need to display related information; you need to fetch them; either in the main query or let the ORM do what it can. Tools are not here to remove laziness.

**Comment by vytsci** [comment]
> @vytsci there is no magic; if you need to display related information; you need to fetch them; either in the main query or let the ORM do what it can. Tools are not here to remove laziness.

If tools brakes common practices there is magic. Look at Pager code if you can`t see anything wrong there Im very sorry for you and especially that part where Pager gets count of all records. Try passing a query with a group by there - Good Luck!

**Comment by rande** [comment]
Yep, show us what's wrong with the PR by making a PR. Also be polite.
