### ISSUE TITLE
isGranted by element, not value

### ISSUE THREAD

**Issue by MarcelBuian** [sonata-project/SonataDoctrineORMAdminBundle#504]
In list_orm_many_to_many.html.twig, line 19:
<code>{%- if field_description.associationadmin.isGranted(route_role, value) -%}</code>
I think must be element:
<code>{%- if field_description.associationadmin.isGranted(route_role, element) -%}</code>

The second argument for isGranted method must be an object.
<code>public function isGranted($name, $object = null)</code>

**Comment by OskarStark** [comment]
ping @rande 

@MarcelBuian what does the tests say? are there any?

**Comment by MarcelBuian** [comment]
@OskarStark I don't know, but in my project I override this file with only one change: 'element' instead of 'value'

I also see that in this new branch (improve-many-to-many): https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/improve-many-to-many-list/Resources/views/CRUD/list_orm_many_to_many.html.twig

this fix is already done.

The "value" object in list_orm_many_to_many is a collection, and you can't check isGranted to a collection. 
<code>{% for element in value%}</code>
Instead this, "element" into a collection is a Model Entity that can be checked for "isGranted"

**Comment by jordisala1991** [comment]
Fixed in #660
