### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by marvoh** [sonata-project/SonataDoctrineORMAdminBundle#514]
Hi,

I am unable to install this package with the command below:

    composer require sonata-project/doctrine-orm-admin-bundle

However, it's not working and I get the error below

Problem 1
     
     - The requested package symfony/symfony == 3.0.1.0 could not be found.

Anyone who can help?

**Comment by rschumacher** [comment]
How does the content of your composer.json file look like now? There must be an issue with inconsistent require's in it.

**Comment by Soullivaneuh** [comment]
No answer from 6 months, closing.
