### ISSUE TITLE
sonata_type_collection without removeXY loses existing entries

### ISSUE THREAD

**Issue by toooni** [sonata-project/SonataDoctrineORMAdminBundle#520]
When using sonata_type_collection with an entity which does not have a removeXY method for a specific collection, old entries are removed from the DB. This is caused by doctrine as it does not support (since https://github.com/doctrine/doctrine2/commit/1587aac4ff6b0753ddd5f8b8d4558b6b40096057) clearing a collection and re-adding entries from this collection again before persisting/flushing.

Example:
Entity: `Painting` does have a property `colors`. If there is no method `removeColor()` inside the entity, old colors are being deleted when saving the form.

SonataHelper does check if there is an `addColor()` method but doesn't care if there is no `removeColor()`.

**Comment by gremo** [comment]
Same issue here. Thanks for spotting this. Any clue on how to fix this?

**Comment by kunicmarko20** [comment]
Is this maybe related to https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/789 ?
