### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by INHack20** [sonata-project/SonataDoctrineORMAdminBundle#532]
Composer update
Problem 1
    - The requested package sonata-project/admin-bundle ~2.4@dev could not be found.

sonata-project/admin-bundle is now 3.x-dev

**Comment by olix21** [comment]
+1, can we change the dependancies asap?

**Comment by qbbr** [comment]
Composer update:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sonata-project/doctrine-orm-admin-bundle dev-master requires sonata-project/admin-bundle ~2.4@dev -> no matching package found.
    - sonata-project/doctrine-orm-admin-bundle dev-master requires sonata-project/admin-bundle ~2.4@dev -> no matching package found.
    - Installation request for sonata-project/doctrine-orm-admin-bundle dev-master -> satisfiable by sonata-project/doctrine-orm-admin-bundle[dev-master].

**Comment by olix21** [comment]
Yeah, it's seems like the new version of sonata-admin-bundle is the ~3@dev and not the ~2.4@dev. I've done a pull request to use the ~3@dev branche

**Comment by qbbr** [comment]
@olix21 change to ~3.0@dev, not ~3@dev

**Comment by olix21** [comment]
done

**Comment by qbbr** [comment]
#533 pull request

**Comment by kasparsklavins** [comment]
Still some problems with the dependencies
```
 Problem 1
    - sonata-project/doctrine-orm-admin-bundle dev-master requires sonata-project/admin-bundle 3.x-dev@dev -> satisfiable by sonata-project/admin-bundle[3.x-dev].
    - sonata-project/doctrine-orm-admin-bundle dev-master requires sonata-project/admin-bundle 3.x-dev@dev -> satisfiable by sonata-project/admin-bundle[3.x-dev].
    - Conclusion: don't install sonata-project/admin-bundle 3.x-dev
    - Installation request for sonata-project/doctrine-orm-admin-bundle dev-master -> satisfiable by sonata-project/doctrine-orm-admin-bundle[dev-master].
```

**Comment by Soullivaneuh** [comment]
Closed by https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/534.

More info: https://github.com/sonata-project/SonataAdminBundle/issues/3731
