### ISSUE TITLE
Oracle issue with DISTINCT in the queries

### ISSUE THREAD

**Issue by Iman** [sonata-project/SonataDoctrineORMAdminBundle#56]
I am using Oracle database and having an issue when deleting or sorting the content as. I am getting the following errors:  "ORA-00932: inconsistent datatypes: expected - got CLOB " and "ORA-00932: inconsistent datatypes: expected - got LOG"

Apparently use of  DISTINCT is incompatible with LOG and CLOB datatypes in Oracle. According to a blog post by Ramkumar Menon from Oracle "A SELECT returning CLOB values must not use the DISTINCT clause." https://blogs.oracle.com/rammenon/entry/dbadapter_javasqlsqlexception

I was wondering if it would be possible to override the Pager, ProxyQuery and ModelManagers service/classes to remove the DISTINCT clause from the queries or what would be the best practice to resolve this issue and how. many Thanks.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
