### ISSUE TITLE
[MSSQL 2012] A column has been specified more than once in the order by list

### ISSUE THREAD

**Issue by postHawk** [sonata-project/SonataDoctrineORMAdminBundle#565]
| Question       | Answer
|----------------|-------------------------------
| Bundle version | composer show sonata-project/*
> sonata-project/admin-bundle              3.1.0 The missing Symfony Admin G...
> sonata-project/block-bundle              3.0.0 Symfony SonataBlockBundle
> sonata-project/cache                     1.0.7 Cache library
> sonata-project/core-bundle               3.0.0 Symfony SonataCoreBundle
> sonata-project/doctrine-orm-admin-bundle 3.0.1 Symfony Sonata / Integrate ...
> sonata-project/exporter                  1.4.1 Lightweight Exporter library
> sonata-project/formatter-bundle          3.0.1 Symfony SonataFormatterBundle

| Symfony version| composer show symfony/*
> symfony/assetic-bundle     v2.8.0  Integrates Assetic into Symfony2
> symfony/monolog-bundle     2.11.1  Symfony MonologBundle
> symfony/polyfill-apcu      v1.2.0  Symfony polyfill backporting apcu_* fun...
> symfony/polyfill-intl-icu  v1.2.0  Symfony polyfill for intl's ICU-related...
> symfony/polyfill-mbstring  v1.2.0  Symfony polyfill for the Mbstring exten...
> symfony/polyfill-php54     v1.2.0  Symfony polyfill backporting some PHP 5...
> symfony/polyfill-php55     v1.2.0  Symfony polyfill backporting some PHP 5...
> symfony/polyfill-php56     v1.2.0  Symfony polyfill backporting some PHP 5...
> symfony/polyfill-php70     v1.2.0  Symfony polyfill backporting some PHP 7...
> symfony/polyfill-util      v1.2.0  Symfony utilities for portability of PH...
> symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Acces...
> symfony/swiftmailer-bundle v2.3.11 Symfony SwiftmailerBundle
> symfony/symfony            v2.8.6  The Symfony PHP framework
> symfony/var-dumper         v3.0.6  Symfony mechanism for exploring and dum...

| php version    | php --version
> 7.0.5
# Error message

```
SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]A column has been specified more than once in the order by list. Columns in the order by list must be unique.") in SonataAdminBundle:CRUD:base_list.html.twig at line 29.
```

Hi!
This commit 876f09853f3c1ea7699e0e567860d163961932d2 added default sort by. But if method getSortBy() return sorting, "order by" clause will be add twice. This throws critical error in mssql. Maybe move this part in "else" section execute() method?

**Comment by greg0ire** [comment]
Good catch! I introduced this bug, sorry, can you help us fix it? I think a good fix would be to add the order by isn't already there. Could you try `dump($queryBuilder->getDQL('orderby'));die()`, to see how we might do this detection ?

**Comment by greg0ire** [comment]
> Maybe move this part in "else" section execute() method?

This is not the right fix, because the default sort won't be added as soon as we are sorting.

I see two solutions : 

1. Check if `$sortBy` is in `$identifierFields` before adding it.
2. Check if `$identifierField` is in `$queryBuilder->getDQL('orderby')`
