### ISSUE TITLE
Admin creates too many queries

### ISSUE THREAD

**Issue by clytemnestra** [sonata-project/SonataDoctrineORMAdminBundle#584]
Following https://github.com/sonata-project/SonataAdminBundle/issues/3924

| Question | Answer |
| --- | --- |
| Bundle version | composer show sonata-project/* |
|  | sonata-project/admin-bundle              3.x-dev 62c313c    The missing Symfony Admin Generator |
|  | sonata-project/block-bundle              3.x-dev ee778ac    Symfony SonataBlockBundle |
|  | sonata-project/cache                     1.0.7              Cache library |
|  | sonata-project/classification-bundle     3.x-dev aa61d55    Symfony SonataClassificationBundle |
|  | sonata-project/core-bundle               3.x-dev d2f84a6    Symfony SonataCoreBundle |
|  | sonata-project/datagrid-bundle           dev-master 311afa1 Symfony SonataDatagridBundle |
|  | sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions |
|  | sonata-project/doctrine-orm-admin-bundle 3.x-dev 3c85820    Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle |
|  | sonata-project/easy-extends-bundle       2.1.10             Symfony SonataEasyExtendsBundle |
|  | sonata-project/exporter                  1.4.1              Lightweight Exporter library |
|  | sonata-project/intl-bundle               2.2.4              Symfony SonataIntlBundle |
|  | sonata-project/media-bundle              3.x-dev ec413fa    Symfony SonataMediaBundle |
|  | sonata-project/notification-bundle       3.0.0              Symfony SonataNotificationBundle |
| Symfony version | composer show symfony/* |
|  | symfony/assetic-bundle     v2.8.0  Integrates Assetic into Symfony2 |
|  | symfony/monolog-bundle     2.11.1  Symfony MonologBundle |
|  | symfony/polyfill-apcu      v1.2.0  Symfony polyfill backporting apcu_\* functions to lower PHP versions |
|  | symfony/polyfill-intl-icu  v1.2.0  Symfony polyfill for intl's ICU-related data and classes |
|  | symfony/polyfill-mbstring  v1.2.0  Symfony polyfill for the Mbstring extension |
|  | symfony/polyfill-php54     v1.2.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions |
|  | symfony/polyfill-php55     v1.2.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions |
|  | symfony/polyfill-php56     v1.2.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions |
|  | symfony/polyfill-php70     v1.2.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions |
|  | symfony/polyfill-util      v1.2.0  Symfony utilities for portability of PHP codes |
|  | symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List) |
|  | symfony/swiftmailer-bundle v2.3.11 Symfony SwiftmailerBundle |
|  | symfony/symfony            v2.8.6  The Symfony PHP framework |
| php version | php --version |
|  | PHP 5.6.20 (cli) (built: Mar 31 2016 14:56:44) |
|  | Copyright (c) 1997-2016 The PHP Group |
|  | Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies |
# Error message

The SF debug bar shows too many queries on all my admin classes. My admin classes have nothing custom. I played a bit with my entities and found out that if I delete the mappedBy fields from my User class, it doesn't do those queries anymore, but then the entity is not valid anymore, since it needs mappedBy for every inversedBy field.
# Steps to reproduce

The admin's entity

``` php
/**
 * @ORM\Table()
 * @ORM\Entity
 */
class BannedUsers
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(referencedColumnName="id",onDelete="CASCADE")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(referencedColumnName="id",onDelete="CASCADE")
     */
    private $censor;

    /**
     * @ORM\Column(type="string",nullable=true,length=2000)
     */
    private $reason;


    /**
     * @ORM\Column(type="boolean")
     */
    private $isBanActive=true;

    /**
     * @ORM\Column(type="datetime")
     * @Timestampable(on="create")
     */
    private $bannedAt;
```

This is my user class, pretty big but maybe it helps:

``` php
/**
 * @ORM\Entity(repositoryClass="UserRepository")
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    const DEFAULT_PATIENT_CREDIT = 300;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\ManyToMany(targetEntity="MedAppBundle\Entity\Group",inversedBy="users")
     * @ORM\JoinTable(name="fos_user_user_group",
     *      joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id",onDelete="CASCADE")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="group_id", referencedColumnName="id")}
     * )
     */
    protected $groups;


    /**
     * @var string
     * @Assert\NotBlank(message="user.firstname.blank",groups={"Profile"})
     * @ORM\Column(name="firstname", type="string",nullable=true)
     */
    protected $firstname;

    /**
     * @var string
     * @Assert\NotBlank(message="user.lastname.blank",groups={"Profile"})
     * @ORM\Column(name="lastname", type="string",nullable=true)
     */
    protected $lastname;

    /**
     * @var string
     *
     * @ORM\Column(name="phoneno", type="string",nullable=true)
     */
    protected $phoneno;

    /**
     * @var string
     *
     * @ORM\Column(name="registration_ip", type="string",nullable=true)
     */
    protected $registrationIp;

    /**
     * @var string
     *
     * @ORM\Column(name="effects", type="boolean")
     */
    protected $effects = true;
    /**
     *
     * @ORM\Column(name="public_email", type="boolean")
     */
    protected $public_email = true;
    /**
     * @Assert\Valid
     * @ORM\OneToOne(targetEntity="MedAppBundle\Entity\MedicSettings",mappedBy="medic", cascade={"persist"})
     * @Assert\Valid()
     */
    protected $medicinfo;
    /**
     * @ORM\OneToMany(targetEntity="MedAppBundle\Entity\MedicComm",mappedBy="medic")
     */
    protected $mediccomm;

    /**
     * @ORM\OneToOne(targetEntity="PrivateMessageBundle\Entity\MessageSettings",mappedBy="user",cascade={"persist"})
     */
    protected $messageSettings;


    /**
     * @ORM\OneToOne(targetEntity="SupportMessageBundle\Entity\TicketSettings",mappedBy="user",cascade={"persist"})
     */
    protected $ticketSettings;

    /**
     * @ORM\OneToOne(targetEntity="Application\Sonata\MediaBundle\Entity\Media",cascade={"persist"})
     * @ORM\JoinColumn(referencedColumnName="id",onDelete="SET NULL")
     */
    protected $profilepic;

    /**
     * @var Media
     *
     * @ORM\OneToMany(targetEntity="Application\Sonata\MediaBundle\Entity\Media", mappedBy="user")
     * @ORM\JoinColumn(name="images", referencedColumnName="id",nullable=true)
     */
    private $images;

    /**
     * @var Media
     *
     * @ORM\OneToMany(targetEntity="Application\Sonata\MediaBundle\Entity\Gallery", mappedBy="user")
     * @ORM\JoinColumn(name="galleries", referencedColumnName="id",nullable=true)
     */
    private $galleries;



    /**
     * @var float
     *
     * @ORM\Column(name="credit", type="float")
     */
    protected $credit = 0;

    /**
     *
     * @ORM\ManyToOne(targetEntity="MedAppBundle\Entity\User")
     * @ORM\JoinColumn(name="referredBy", referencedColumnName="id",nullable=true,onDelete="SET NULL")
     */
    protected $referredBy;

    /**
     * @var string
     *
     * @ORM\Column(name="locationData", type="string",nullable=true)
     */
    protected $locationData;

    /**
     * @ORM\OneToMany(targetEntity="MedAppBundle\Entity\Stream",mappedBy="streamer")
     * @ORM\JoinColumn(referencedColumnName="id")
     */
    private $streams;

    /**
     * @var string
     *
     * @ORM\Column(name="savedFilters", type="string",nullable=true)
     */
    protected $savedFilters;


    /**
     *
     * @ORM\Column(name="registration_date", type="datetime",nullable=true)
     */
    protected $registrationDate;

    /**
     * @ORM\OneToMany(targetEntity="MedAppBundle\Entity\FavoriteUsers",mappedBy="user")
     * @ORM\JoinColumn(referencedColumnName="id")
     */
    private $favUsers;

    /**
     * @var string
     *
     * @ORM\Column(name="chosen_theme", type="string",nullable=true)
     */
    protected $chosenTheme;

    /**
     * @var string
     *
     * @ORM\Column(name="site_lang", type="string",nullable=true)
     */
    protected $siteLang;

    /**
     * @var integer
     *
     * @ORM\Column(name="total_time_live", type="integer", nullable=true)
     *
     */
    protected $totalTimeLive;

    /**
     *
     * @ORM\ManyToOne(targetEntity="FirmBundle\Entity\Firm",inversedBy="firmAdmins", cascade={"persist"})
     */
    protected $adminOfFirm;

    /**
     * @ORM\OneToMany(targetEntity="MedAppBundle\Entity\EmailList",mappedBy="user")
     * @ORM\JoinColumn(referencedColumnName="id")
     */
    private $emailList;

    /**
     * @ORM\OneToOne(targetEntity="MedAppBundle\Entity\Newsletter",mappedBy="user")
     * @ORM\JoinColumn(referencedColumnName="id")
     */
    private $newsletter;

    /**
     * @var string
     *
     * @ORM\Column(name="folderName", type="string", nullable=true)
     */
    public $folderName;

    /**
     *
     * @ORM\Column(name="bonus_received", type="boolean")
     */
    protected $bonusReceived = false;

    /**
     *
     * @ORM\Column(name="purchase_bonus_eligibility", type="boolean", options={"default" = true }, nullable=true )
     */
    protected $purchaseBonusEligibility;

    /**
     * @ORM\OneToMany(targetEntity="MedAppBundle\Entity\PendingProfileImage",mappedBy="user")
     */
    protected $pendingProfileImages;

    /**
     * @ORM\Column(name="is_validated_phone_no", type="boolean", nullable=true)
     */
    private $isValidatedPhoneNo;

    /**
     * @ORM\Column(name="mobile_validation_pin", type="string", nullable=true)
     */
    private $mobileValidationPin;

    /**
     * @ORM\Column(name="username_token", type="string", nullable=true, options={"default" = true })
     */
    private $usernameToken;




    /**
     * @ORM\OneToOne(targetEntity="MedAppBundle\Entity\AccountDocument", mappedBy="user")
     */
    private $accountDocument;


    /**
     * @ORM\OneToMany(targetEntity="MedAppBundle\Entity\AccountDocument", mappedBy="takenByAdmin")
     * @ORM\JoinColumn(referencedColumnName="id",onDelete="CASCADE")
     */
    private $takenPending;
```
# Expected results

If I delete all the mappedBy fields, the same page on my admin shows less queries, as I want it to be, but invalid entity:

![image](https://cloud.githubusercontent.com/assets/7060048/15884903/147cb570-2d5c-11e6-9cb7-93fe621d242e.png)

Here's the queries table
https://jsfiddle.net/nmxz4j7y/
# Actual results

Here's one of my admin classes's example:

![image](https://cloud.githubusercontent.com/assets/7060048/15884782/69bd14cc-2d5b-11e6-8307-09824e97cc48.png)

Here's the query table:
https://jsfiddle.net/nmxz4j7y/1/

**Comment by Soullivaneuh** [comment]
@clytemnestra Please update your issue body following the template: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/.github/ISSUE_TEMPLATE.md

And with more detail than just a link pointing on a issue with another link.

Thanks.

**Comment by Soullivaneuh** [comment]
Also be warned about playing with the join SQL logic, this does not give performance all the time. Sometime, the reverse happen.

**Comment by clytemnestra** [comment]
Hope it's ok now. Yeah but doing 4 or  more queries per table entry is not ok, neither.

**Comment by Soullivaneuh** [comment]
`composer show sonata-project/*`

The result would be more useful.

> Yeah but doing 4 or more queries per table entry is not ok, neither.

Example: http://stackoverflow.com/a/3742752/1731473

Performing join on very large database could be worse than multiple queries. I talk by experience.

Reading your use case, it's more a problem of "Which data should I fetch" than a join issue.

> Here's the queries table
> https://jsfiddle.net/nmxz4j7y/

Only 5 queries is listed here.

**Comment by clytemnestra** [comment]
But those 5 queries are the expected result.

**Comment by greg0ire** [comment]
Maybe upgrade Composer?

**Comment by clytemnestra** [comment]
Yup, that  fixed it.

**Comment by Soullivaneuh** [comment]
> But those 5 queries are the expected result.

Indeed, sorry for that.

**Comment by clytemnestra** [comment]
I have a small problem, I tried doing something like

```php
    public function createQuery($context = 'list')
    {
        $query = parent::createQuery($context);

        $query
            ->addSelect('User')
            ->leftJoin($query->getRootAlias().'.user', 'user')
        ;

        return $query;
    }
```

because I thought to do it as a temporary solution, but this doesn't change anything. I'm getting the same queries, and this query doesn't even appear in the list. I think it might be because of the aliases. hile here I am aliasing with ``user``, the actual alias used in the query is ``t0``` as seen above.

So not even this works.

**Comment by greg0ire** [comment]
Aren't you supposed to write sth like this : `->addSelect('something.user', 'u')`

**Comment by clytemnestra** [comment]
How come? addSelect() selects all its arguments as aliases.

``
            ->addSelect('user','u')
            ->join($query->getRootAlias().'.user', 'user')
``

would become

``
SELECT o, user, u FROM MedAppBundle\Entity\BannedUsers o INNER JOIN o.user user
``

**Comment by greg0ire** [comment]
Forget what I said, it's wrong.

**Comment by greg0ire** [comment]
But in your case I think you should write `->addSelect('user')`, not `addSelect('User')`

**Comment by clytemnestra** [comment]
Yeah, already fixed that(if I let it uppercase it generates an error), but still doesn't work.

**Comment by greg0ire** [comment]
> t0 as seen above

Ctrl+F t0 yields only one occurence.

**Comment by clytemnestra** [comment]
Try the second jsfiddle from the 'actual results', not expected.

**Comment by greg0ire** [comment]
The jsfiddle shows SQL queries. DQL and SQL queries aliases are different things, I wouldn't expect `user` to show up in an SQL query instead of `t0`

**Comment by clytemnestra** [comment]
Hm, I see. So why isn't my config used, then? I've also deleted cache.

**Comment by greg0ire** [comment]
Try adding something peculiar like an orderBy clause maybe to see if you can find the corresponding sql query…

**Comment by clytemnestra** [comment]
Done. The query is the last one in the query list:

```php
        $query
            ->addSelect('user')
            ->leftJoin($query->getRootAlias().'.user', 'user')
            ->leftJoin($query->getRootAlias().'.censor', 'censor')
            ->orderBy('user.username','ASC');
        ;


        return $query;
```


```php
SELECT b0_.id AS id_0, b0_.reason AS reason_1, b0_.is_ban_active AS is_ban_active_2, b0_.banned_at AS banned_at_3, f1_.username AS username_4, f1_.username_canonical AS username_canonical_5, f1_.email AS email_6, f1_.email_canonical AS email_canonical_7, f1_.enabled AS enabled_8, f1_.salt AS salt_9, f1_.password AS password_10, f1_.last_login AS last_login_11, f1_.locked AS locked_12, f1_.expired AS expired_13, f1_.expires_at AS expires_at_14, f1_.confirmation_token AS confirmation_token_15, f1_.password_requested_at AS password_requested_at_16, f1_.roles AS roles_17, f1_.credentials_expired AS credentials_expired_18, f1_.credentials_expire_at AS credentials_expire_at_19, f1_.id AS id_20, f1_.firstname AS firstname_21, f1_.lastname AS lastname_22, f1_.phoneno AS phoneno_23, f1_.registration_ip AS registration_ip_24, f1_.effects AS effects_25, f1_.public_email AS public_email_26, f1_.credit AS credit_27, f1_.locationData AS locationData_28, f1_.savedFilters AS savedFilters_29, f1_.registration_date AS registration_date_30, f1_.chosen_theme AS chosen_theme_31, f1_.site_lang AS site_lang_32, f1_.total_time_live AS total_time_live_33, f1_.folderName AS folderName_34, f1_.bonus_received AS bonus_received_35, f1_.purchase_bonus_eligibility AS purchase_bonus_eligibility_36, f1_.is_validated_phone_no AS is_validated_phone_no_37, f1_.mobile_validation_pin AS mobile_validation_pin_38, f1_.username_token AS username_token_39, b0_.user_id AS user_id_40, b0_.censor_id AS censor_id_41, f1_.profilepic_id AS profilepic_id_42, f1_.referredBy AS referredBy_43, f1_.admin_of_firm_id AS admin_of_firm_id_44, f1_.newsletter_id AS newsletter_id_45 FROM banned_users b0_ LEFT JOIN fos_user f1_ ON b0_.user_id = f1_.id LEFT JOIN fos_user f2_ ON b0_.censor_id = f2_.id WHERE b0_.id IN (?) ORDER BY f1_.username ASC, b0_.id DESC
Parameters: [[2]]
Hide formatted query    Hide runnable query    Hide query explanation
SELECT 
  b0_.id AS id_0, 
  b0_.reason AS reason_1, 
  b0_.is_ban_active AS is_ban_active_2, 
  b0_.banned_at AS banned_at_3, 
  f1_.username AS username_4, 
  f1_.username_canonical AS username_canonical_5, 
  f1_.email AS email_6, 
  f1_.email_canonical AS email_canonical_7, 
  f1_.enabled AS enabled_8, 
  f1_.salt AS salt_9, 
  f1_.password AS password_10, 
  f1_.last_login AS last_login_11, 
  f1_.locked AS locked_12, 
  f1_.expired AS expired_13, 
  f1_.expires_at AS expires_at_14, 
  f1_.confirmation_token AS confirmation_token_15, 
  f1_.password_requested_at AS password_requested_at_16, 
  f1_.roles AS roles_17, 
  f1_.credentials_expired AS credentials_expired_18, 
  f1_.credentials_expire_at AS credentials_expire_at_19, 
  f1_.id AS id_20, 
  f1_.firstname AS firstname_21, 
  f1_.lastname AS lastname_22, 
  f1_.phoneno AS phoneno_23, 
  f1_.registration_ip AS registration_ip_24, 
  f1_.effects AS effects_25, 
  f1_.public_email AS public_email_26, 
  f1_.credit AS credit_27, 
  f1_.locationData AS locationData_28, 
  f1_.savedFilters AS savedFilters_29, 
  f1_.registration_date AS registration_date_30, 
  f1_.chosen_theme AS chosen_theme_31, 
  f1_.site_lang AS site_lang_32, 
  f1_.total_time_live AS total_time_live_33, 
  f1_.folderName AS folderName_34, 
  f1_.bonus_received AS bonus_received_35, 
  f1_.purchase_bonus_eligibility AS purchase_bonus_eligibility_36, 
  f1_.is_validated_phone_no AS is_validated_phone_no_37, 
  f1_.mobile_validation_pin AS mobile_validation_pin_38, 
  f1_.username_token AS username_token_39, 
  b0_.user_id AS user_id_40, 
  b0_.censor_id AS censor_id_41, 
  f1_.profilepic_id AS profilepic_id_42, 
  f1_.referredBy AS referredBy_43, 
  f1_.admin_of_firm_id AS admin_of_firm_id_44, 
  f1_.newsletter_id AS newsletter_id_45 
FROM 
  banned_users b0_ 
  LEFT JOIN fos_user f1_ ON b0_.user_id = f1_.id 
  LEFT JOIN fos_user f2_ ON b0_.censor_id = f2_.id 
WHERE 
  b0_.id IN (?) 
ORDER BY 
  f1_.username ASC, 
  b0_.id DESC
SELECT b0_.id AS id_0, b0_.reason AS reason_1, b0_.is_ban_active AS is_ban_active_2, b0_.banned_at AS banned_at_3, f1_.username AS username_4, f1_.username_canonical AS username_canonical_5, f1_.email AS email_6, f1_.email_canonical AS email_canonical_7, f1_.enabled AS enabled_8, f1_.salt AS salt_9, f1_.password AS password_10, f1_.last_login AS last_login_11, f1_.locked AS locked_12, f1_.expired AS expired_13, f1_.expires_at AS expires_at_14, f1_.confirmation_token AS confirmation_token_15, f1_.password_requested_at AS password_requested_at_16, f1_.roles AS roles_17, f1_.credentials_expired AS credentials_expired_18, f1_.credentials_expire_at AS credentials_expire_at_19, f1_.id AS id_20, f1_.firstname AS firstname_21, f1_.lastname AS lastname_22, f1_.phoneno AS phoneno_23, f1_.registration_ip AS registration_ip_24, f1_.effects AS effects_25, f1_.public_email AS public_email_26, f1_.credit AS credit_27, f1_.locationData AS locationData_28, f1_.savedFilters AS savedFilters_29, f1_.registration_date AS registration_date_30, f1_.chosen_theme AS chosen_theme_31, f1_.site_lang AS site_lang_32, f1_.total_time_live AS total_time_live_33, f1_.folderName AS folderName_34, f1_.bonus_received AS bonus_received_35, f1_.purchase_bonus_eligibility AS purchase_bonus_eligibility_36, f1_.is_validated_phone_no AS is_validated_phone_no_37, f1_.mobile_validation_pin AS mobile_validation_pin_38, f1_.username_token AS username_token_39, b0_.user_id AS user_id_40, b0_.censor_id AS censor_id_41, f1_.profilepic_id AS profilepic_id_42, f1_.referredBy AS referredBy_43, f1_.admin_of_firm_id AS admin_of_firm_id_44, f1_.newsletter_id AS newsletter_id_45 FROM banned_users b0_ LEFT JOIN fos_user f1_ ON b0_.user_id = f1_.id LEFT JOIN fos_user f2_ ON b0_.censor_id = f2_.id WHERE b0_.id IN (2) ORDER BY f1_.username ASC, b0_.id DESC;
```

**Comment by clytemnestra** [comment]
And this is the one before it:

```php
SELECT DISTINCT b0_.id AS id_0, b0_.id AS id_1 FROM banned_users b0_ LEFT JOIN fos_user f1_ ON b0_.user_id = f1_.id LEFT JOIN fos_user f2_ ON b0_.censor_id = f2_.id ORDER BY f1_.username ASC, b0_.id DESC LIMIT 32 OFFSET 0
Parameters: { }
Hide formatted query    Hide runnable query    Hide query explanation
SELECT 
  DISTINCT b0_.id AS id_0, 
  b0_.id AS id_1 
FROM 
  banned_users b0_ 
  LEFT JOIN fos_user f1_ ON b0_.user_id = f1_.id 
  LEFT JOIN fos_user f2_ ON b0_.censor_id = f2_.id 
ORDER BY 
  f1_.username ASC, 
  b0_.id DESC 
LIMIT 
  32 OFFSET 0
SELECT DISTINCT b0_.id AS id_0, b0_.id AS id_1 FROM banned_users b0_ LEFT JOIN fos_user f1_ ON b0_.user_id = f1_.id LEFT JOIN fos_user f2_ ON b0_.censor_id = f2_.id ORDER BY f1_.username ASC, b0_.id DESC LIMIT 32 OFFSET 0;
```

**Comment by clytemnestra** [comment]
Could the problem be that it's the last one? And why is it?

**Comment by greg0ire** [comment]
One has a LIMIT, the other hasn't… maybe the first one is for a count ?

**Comment by clytemnestra** [comment]
It's for the pagination or something, maybe. Any ideas to make this work?

**Comment by greg0ire** [comment]
Pagination with 32 elements is a bit strange BTW :S

**Comment by greg0ire** [comment]
->addSelect('user.*') ? Also, `User` is a reserved SQL keyword, you might want to avoid it…

**Comment by clytemnestra** [comment]
No, that's the number of elements I display per page: 32. The other options are 16, 64, 128, 192, defaults from sonata admin.

**Comment by greg0ire** [comment]
Powers of 2. Makes sense for IT people I guess…

**Comment by clytemnestra** [comment]
Yup. Changing the user keyword to something else doesn't work, either.

**Comment by greg0ire** [comment]
What about the star?

**Comment by clytemnestra** [comment]
``An exception has been thrown during the rendering of a template ("[Semantical Error] line 0, col 15 near '* FROM MedAppBundle\Entity\BannedUsers': Error: Class MedAppBundle\Entity\User has no field or association named *") in SonataAdminBundle:CRUD:base_list.html.twig at line 30.``

It needs a field, you can't select all the fields as it's done automatically when you do ``->addSelect(user)``

**Comment by greg0ire** [comment]
Ok great… I'm out of ideas, sorry :(

**Comment by greg0ire** [comment]
I would say: try to see the DQL and the SQL just after your modification, to see if the problems lies in what you are writing, or if there is something else that removes the user fields from the select (if this is the problem, not sure I understood).

**Comment by clytemnestra** [comment]
The SQL runs without problem if I run it in phpMyAdmin:

```php
            ->addSelect('user')
            ->leftJoin($query->getRootAlias().'.user', 'user')
```

Dumped ```$query->getQuery()->getSql()```

```sql
SELECT b0_.id AS id_0, b0_.reason AS reason_1, b0_.is_ban_active AS is_ban_active_2, b0_.banned_at AS banned_at_3, f1_.username AS username_4, f1_.username_canonical AS username_canonical_5, f1_.email AS email_6, f1_.email_canonical AS email_canonical_7, f1_.enabled AS enabled_8, f1_.salt AS salt_9, f1_.password AS password_10, f1_.last_login AS last_login_11, f1_.locked AS locked_12, f1_.expired AS expired_13, f1_.expires_at AS expires_at_14, f1_.confirmation_token AS confirmation_token_15, f1_.password_requested_at AS password_requested_at_16, f1_.roles AS roles_17, f1_.credentials_expired AS credentials_expired_18, f1_.credentials_expire_at AS credentials_expire_at_19, f1_.id AS id_20, f1_.firstname AS firstname_21, f1_.lastname AS lastname_22, f1_.phoneno AS phoneno_23, f1_.registration_ip AS registration_ip_24, f1_.effects AS effects_25, f1_.public_email AS public_email_26, f1_.credit AS credit_27, f1_.locationData AS locationData_28, f1_.savedFilters AS savedFilters_29, f1_.registration_date AS registration_date_30, f1_.chosen_theme AS chosen_theme_31, f1_.site_lang AS site_lang_32, f1_.total_time_live AS total_time_live_33, f1_.folderName AS folderName_34, f1_.bonus_received AS bonus_received_35, f1_.purchase_bonus_eligibility AS purchase_bonus_eligibility_36, f1_.is_validated_phone_no AS is_validated_phone_no_37, f1_.mobile_validation_pin AS mobile_validation_pin_38, f1_.username_token AS username_token_39, b0_.user_id AS user_id_40, b0_.censor_id AS censor_id_41, f1_.profilepic_id AS profilepic_id_42, f1_.referredBy AS referredBy_43, f1_.admin_of_firm_id AS admin_of_firm_id_44, f1_.newsletter_id AS newsletter_id_45 FROM banned_users b0_ LEFT JOIN fos_user f1_ ON b0_.user_id = f1_.id ```

**Comment by greg0ire** [comment]
>  this is the problem, not sure I understood

To make sure I understand :  the problem is doctrine making other queries for related fields anyway, even though you already have them hydrated by `createQuery()`, right ? Because the first SQL query you show me is fine, isn't it?

**Comment by clytemnestra** [comment]
Yeah, that's my thinking. I could be wrong, but it doesn't make too much sense for the query to be the last in the queries list, and for it to be completely ignored.

**Comment by greg0ire** [comment]
Oh right. Doesn't make sense indeed. You can try throwing an exception in `createQuery()` it will show you the stack trace and you will know when it is executed. Then try to do the same for the other queries if you can find where they are executed.

**Comment by clytemnestra** [comment]
Does this help?

```php
    at n/a
        in C:\htdocs\medapp\src\Application\Sonata\AdminBundle\Admin\BannedUsersAdmin.php line 25

    at Application\Sonata\AdminBundle\Admin\BannedUsersAdmin->createQuery()
        in C:\htdocs\medapp\vendor\sonata-project\doctrine-orm-admin-bundle\Builder\DatagridBuilder.php line 163

    at Sonata\DoctrineORMAdminBundle\Builder\DatagridBuilder->getBaseDatagrid(object(BannedUsersAdmin), array('_sort_order' => 'ASC', '_sort_by' => object(FieldDescription), '_page' => '1', '_per_page' => '32'))
        in C:\htdocs\medapp\app\cache\dev\classes.php line 3675

    at Sonata\AdminBundle\Admin\AbstractAdmin->buildDatagrid()
        in C:\htdocs\medapp\app\cache\dev\classes.php line 3979

    at Sonata\AdminBundle\Admin\AbstractAdmin->getDatagrid()
        in C:\htdocs\medapp\vendor\sonata-project\admin-bundle\Controller\CRUDController.php line 104

    at Sonata\AdminBundle\Controller\CRUDController->listAction()
        in  line 

    at call_user_func_array(array(object(BannedUsersAdminController), 'listAction'), array())
        in C:\htdocs\medapp\app\bootstrap.php.cache line 3215

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), '1')
        in C:\htdocs\medapp\app\bootstrap.php.cache line 3177

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), '1', true)
        in C:\htdocs\medapp\app\bootstrap.php.cache line 3328

    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Request), '1', true)
        in C:\htdocs\medapp\app\bootstrap.php.cache line 2518

    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in C:\htdocs\medapp\web\app_dev.php line 28
```

**Comment by greg0ire** [comment]
> Then try to do the same for the other queries if you can find where they are executed.

Only if you do this

**Comment by clytemnestra** [comment]
Which other queries, more exactly? I got lost in so many. I believe it will always crash when trying to build the datagrid from the admin's query. So I went into the ``getDatagrid()`` after it's using the query and dumped ``$this->datagrid->getQuery()->getQuery()`` and it's still returing my query's DQL.

**Comment by clytemnestra** [comment]
Actually, in ``CRUDController::listAction()``, if I dump ``$datagrid->getQuery()->getQuery()`` I still get my DQL query.

**Comment by clytemnestra** [comment]
Ok, I might be on to something here. I found out that if I delete ``user,censor`` from my ``configureDatagridFilters()``, all those big queries disappear. Could it do something funny [https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Admin/AbstractAdmin.php#L817](here) ?

**Comment by clytemnestra** [comment]
OK! 

Nevermind today's discussion. 

My createQuery() DOES WORK, but for the listFields. The HUGE number of queries are done because of the filters. If I remove all the filters, or all the filters that point to a related entity(join), then the huge queries appear. 

Now, I'm asking if this is normal, and how to make the filters use the createQuery() function. Or, if it's something else they use?

**Comment by evancauwenberg** [comment]
Any news on this topic? I have the same issue when i add the filters or custom fields

**Comment by v03adk** [comment]
the same here

**Comment by StudioMaX** [comment]
Same too. After some investigation I found that this is because of Doctrine, not Sonata
http://docs.doctrine-project.org/en/latest/reference/faq.html#why-is-an-extra-sql-query-executed-every-time-i-fetch-an-entity-with-a-one-to-one-relation

To fix this we need to switch the mappedBy and inversedBy in our One-To-One relations (and also in the database)
**or**
to change these relations to Many-To-One and create some helper method like
```php
public function getUserProfile() {
    $userProfiles = $this->getUserProfiles();
    if ($userProfiles->count()) {
        return $userProfiles->first();
    }

    return null;
}
```

**Comment by lukepass** [comment]
Hello, I have the same problem with backend pages making more than 100 queries.

I created this issue:
https://github.com/sonata-project/SonataAdminBundle/issues/5038

My entites have nothing special except from OneToMany or ManyToOne relationships.
The problem seems related to the DatagridMapper, if I comment it all the queries go away. Why is it filtering the entities even if there are no filters specified?

Thanks.

**Comment by vytsci** [comment]
I have a table that joins with other huge table, but that table has EXTRA_LAZY and is not used anywhere on admin. My admin page ends up with 3k queries rather than 6 and all the credit goes to filters. People be careful with filters.

**Comment by OskarStark** [comment]
This comment isn't quite helpful and feels more like a rant @vytsci ... 😢

**Comment by jjsmclaughlin** [comment]
I had the same problem. I found that it was solved by using a doctrine_orm_model_autocomplete as my requested Doctrine ORM filter type on the datagrid:

`$datagridMapper->add('my_foreign_key_property', 'doctrine_orm_model_autocomplete', [], null, ['property'=>'a_field_on_my_foreign_key_entity'])`

This seems to stop Doctrine from trying to populate the datagrid in advance with all those queries. In my case, it was tens of thousands.

**Comment by th-lange** [comment]
I happened to stumble over this, trying to solve an unusable admin panel in a live environment.

This direly needs to be reflected in the documentation! Most people will have links between Entities, making tables referring to large data sets almost unusable.

This should even be a warning! If you refer to large sets of entities, be wary that the filter will fetch and hydrate those entities! (Hydrating for us took more than 1min).

**Comment by phansys** [comment]
In case you need to provide the available choices manually, you can also give a try to [`CallbackChoiceLoader`](https://symfony.com/blog/new-in-symfony-3-2-lazy-loading-of-form-choices). This should help to keep a reduced set of queries, even for the global search (which by default performs a `LIKE` comparison with every text filter in your admin instances).

**Comment by kirya-dev** [comment]
Im have same problem

**Comment by VincentLanglet** [comment]
This seems to be a normal behavior.
The filter are always on the page, just hidden if not used.
If a filter has a lot of choices, it lead to a lot of query, and in this case an autocomplete should be preferred in order to lazy load. I would say that this is the basic behavior of Symfony form.
