### ISSUE TITLE
4.x branch requires admin-bundle ^3.1

### ISSUE THREAD

**Issue by ju1ius** [sonata-project/SonataDoctrineORMAdminBundle#589]
# Steps to reproduce
```sh
$ composer require sonata-project/admin-bundle 4.x-dev
$ composer require sonata-project/doctrine-orm-admin-bundle 4.x-dev
```

# Expected results
Both bundles should install in 4.x branch

# Actual results

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: sonata-project/admin-bundle[3.x-dev, 4.x-dev].
    - Can only install one of: sonata-project/admin-bundle[4.x-dev, 3.x-dev].
    - Can only install one of: sonata-project/admin-bundle[3.x-dev, 4.x-dev].
    - sonata-project/doctrine-orm-admin-bundle 4.x-dev requires sonata-project/admin-bundle ^3.1 -> satisfiable by sonata-project/admin-bundle[3.x-dev].
    - Installation request for sonata-project/doctrine-orm-admin-bundle 4.x-dev -> satisfiable by sonata-project/doctrine-orm-admin-bundle[4.x-dev].
    - Installation request for sonata-project/admin-bundle 4.x-dev -> satisfiable by sonata-project/admin-bundle[4.x-dev].
```

**Comment by Soullivaneuh** [comment]
> Both bundles should install in 4.x branch

And why? cc @greg0ire

**Comment by greg0ire** [comment]
As discussed the other day, no bundle should depend on an unstable version if a stable one is out. If you want to test things out, you have to edit your Composer manifest locally.

**Comment by ju1ius** [comment]
@greg0ire With the old branching system, I used to do this:

```json
{
  "repositories": [
    {
      "type": "git",
      "url": "git@github.com:ju1ius/SonataAdminBundle.git"
    },
    {
      "type": "git",
      "url": "git@github.com:ju1ius/SonataDoctrineORMAdminBundle.git"
    }
  ],
  "require": {
    "sonata-project/admin-bundle": "dev-mybranch as 2.4.x-dev",
    "sonata-project/doctrine-orm-admin-bundle": "dev-mybranch as 2.4.x-dev"
  }
}
```
then
```sh
$ composer update --prefer-source sonata-project/admin-bundle sonata-project/doctrine-orm-admin-bundle
```

What do you recommend for the new way ?
If I want to work on a feature for next major, should I base on 3.x or 4.x ?

**Comment by Soullivaneuh** [comment]
> With the old branching system

You said that, the **old** one. :wink: 

> If I want to work on a feature for next major, should I base on 3.x or 4.x ?

A feature should always be on next **minor**, not minor. If this is BC break, try to make it BC.

New feature on major is done if we have absolutely not choice.

**Comment by greg0ire** [comment]
> minor, not minor

-___-

**Comment by ju1ius** [comment]
> New feature on major is done if we have absolutely not choice.

So, if I'm 100% sure I have no other choice, how shall I do ? base on 3.x or 4.x ?

**Comment by Soullivaneuh** [comment]
@ju1ius `4.x`.

But if this can be BC, the PR can be refused.

**Comment by Soullivaneuh** [comment]
@ju1ius Also just read the contributing guide: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/CONTRIBUTING.md#the-base-branch

**Comment by ju1ius** [comment]
@Soullivaneuh I'm starting to rework this one https://github.com/sonata-project/SonataAdminBundle/pull/3647 by splitting it into many small PRs as stated in the last PR comment. The first part is to move all form association templates back into the admin bundle, so it will touch all persistence bundles + the admin bundle. So it will likely not be BC, unless I have a team of 7 slaves working on it for me :laughing: 

Can you confirm I should base my work on all bundles master branch ?

**Comment by Soullivaneuh** [comment]
> Can you confirm I should base my work on all bundles master branch ?

If you have no choice for BC break yes. But I suggest you to start only one PR first, so we can confirm if this can be done on a BC way or not.
