### ISSUE TITLE
How disable trim string in field?

### ISSUE THREAD

**Issue by Slavenin** [sonata-project/SonataDoctrineORMAdminBundle#594]
Hi! I need to save string data with spaces in end, but service doctrine_orm_string trimmed my string!
I try add model or view transformer, but string already trimmed. How i can save data with spaces in end of string?

**Comment by Soullivaneuh** [comment]
For question, please use StackOverflow.

If you think it's a bug, re-open another issue and fill the **issue template**.

See also: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/CONTRIBUTING.md#issues
