### ISSUE TITLE
sonata_admin_orm_*_to_*_widget label rendering

### ISSUE THREAD

**Issue by fbourigault** [sonata-project/SonataDoctrineORMAdminBundle#601]
Hi, I'm hacking a little on sonata and I'm wondering why collection form templates are not using `form_label` to render the labels but `nested_field.vars['sonata_admin'].admin.trans(nested_field.vars.label)` ?

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/Resources/views/CRUD/edit_orm_one_to_many.html.twig#L30

Is it harfmul to use `form_label` here ? It allows to override form label  with \* when the field is required or to add a tip about a translatable field.

**Comment by greg0ire** [comment]
I might be wrong, but I think it might be in order to benefit from the `AbstractAdmin::trans` logic.
