### ISSUE TITLE
Distinct on primary auto increment key

### ISSUE THREAD

**Issue by TimoFrenzel** [sonata-project/SonataDoctrineORMAdminBundle#619]
Sonata\DoctrineORMAdminBundle\Datagrid\Pager

We have several million records in the table.
It noticed that the ListView needs more than 3 minutes to open the page.

This file is the problem.
It is made a count (distinct id).
However, the id is always an autoincrement primary key.
This slows the whole considerably.

And here too: Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery

**Comment by greg0ire** [comment]
Why are you creating duplicate issues?

**Comment by TimoFrenzel** [comment]
because this is in two bundles... one issue in the right bundle.
Its wrong? Its my first time, that i report a issue.

**Comment by jordisala1991** [comment]
Duplicated of #473 

Closing
