### ISSUE TITLE
Filtered entity field: cannot use sonata_type_collection_widget

### ISSUE THREAD

**Issue by fzan** [sonata-project/SonataDoctrineORMAdminBundle#643]
## Subject

Custom entity field with no metadata: cannot use sonata_type_collection_widget

## Steps to reproduce

let's make an Entity (Tavoli) with oneToMany relation (operazioni), then make a custom field for filtering the results:

```
/**
 * Tavoli
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class Tavoli
{
    /* Many getters and setters here */

    /**
     * @ORM\OneToMany(targetEntity="Operazioni", mappedBy="otherField")
     */
    private $operazioni;

    /* Many getters and setters here */

     /**
     * @return mixed
     */
    public function getOperazioniEseguite() {
     
        $result =$this->getOperazioni->filter(function($operazione) {
            return $operazione->isStato();
        });

        return $result;
    }

   /* Many getters and setters here */
}
```

In the Admin, i want to edit inline the data, so i'm using sonata_type_collection (with sonata_type_model the problem is the same)

Admin method configureFormField:

```
 /**
     * @param FormMapper $formMapper
     */
    protected function configureFormFields(FormMapper $formMapper)
    {
        /* setters here */
$formMapper
        ->add('operazioniEseguite','sonata_type_collection', array(
            'label'=>false,
            'btn_add' => false,
            'type_options' => array('delete' => false),
            'by_reference' => false,
            'required'=>false
        ), array(
            'admin_code'=>'myAdmin',
            'expanded'=>false,
            'edit' => 'inline',
            'inline' => 'table',
            'class'=>'MyBundle:Operazioni'
        ))->end();

    }
```

## Expected results

Correct widget visualization

## Actual results

you will get INVALID MODE.

That's because in views/Form/form_admin_fields.html.twig you check for **sonata_admin.field_description.mappingtype**. Obviously the _operazioniEseguite_ is not mapped, (it's only a service method to filter the result for the one_to_many widget) so the mappingtype is null.

as i can see, in comments

```
 This is not the best way to do if
        TODO : improve this part
```

So, i'm asking:
1) It's possible to override the sonata_admin.field_description.mappingtype only for this field? i don't think so, but if it's possible... how?
2) why not allow another field_description.options variable with an OR in the ifs, forcing the type of the widget? it could cover other cases as well and in the model_list_widget it's already used.

thanks :)

**Comment by fzan** [comment]
Suggesting:

in form_admin_fields.html.twig, add

`or sonata_admin.field_description.options.mappingtype=="onetomany"`

(or another constant of your choice :) )

in the admin class, configureFormFields, $formMapper->add 4 array(options) :

`'mappingtype'=>"onetomany",`

I actually have overriden the template via 

```
sonata_doctrine_orm_admin:
    templates:
        form:
            - MyBundle:Default:form_admin_fields.html.twig
```

and it is working. 
Maybe with some cleaning it could be a PR? it's BC and maybe it's useful :)

However, if i have reinvented the weel, please tell me the actual correct way to do ;)

**Comment by greg0ire** [comment]
Can you please link to the relevant piece of code? I'm reviewing this on my phone right now.

**Comment by fzan** [comment]
yup, there is

[form_admin_fields.html.twig](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/Resources/views/Form/form_admin_fields.html.twig#L150-L157)

**Comment by greg0ire** [comment]
Wow. [This error handling](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/Resources/views/Form/form_admin_fields.html.twig#L156) is… somewhat peculiar :sweat_smile:

> in the model_list_widget it's already used.

Please add a link for this too.

> the mappingtype is null.

This one would deserve a link… where is it set to null? Because that's probably where you could act to make a PR.

**Comment by fzan** [comment]
Sorry for the delay.

As you can see, [here](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/Resources/views/Form/form_admin_fields.html.twig#L64) you are using options associated to the field_description  to, obviously, decorate the rendering of an element. You cannot however define what type of element the widget is rendering by force the type (that is inferred via classmetadatainfo, which you obviously define in another property...).

the fact the mappingtype is null is about that we are using a custom property not decorated with metadata. Maybe it's possible to decorate the element without actually add it to the database and i'm wrong about the example? i don't know :)
