### ISSUE TITLE
Catchable Fatal Error: Object of class DateTime could not be converted to string

### ISSUE THREAD

**Issue by Vesax** [sonata-project/SonataDoctrineORMAdminBundle#652]
## Subject

> Catchable Fatal Error: Object of class DateTime could not be converted to string

Caused by `vendor/sonata-project/doctrine-orm-admin-bundle/Datagrid/Pager.php` at line 70

## Steps to reproduce

Go to `/admin/sonata/page/page/list?filter%5Bsite%5D%5Bvalue%5D=1` - List view in Sonata Page Bundle

## Expected results

List of pages

Works properly in release 449d97b83661918a9a9a1469370d7ddb086061dc

## Actual results

```
DBALException: An exception occurred while executing 'SELECT count(DISTINCT p0_.id) AS sclr_0 FROM page__page p0_ LEFT JOIN page__site p1_ ON p0_.site_id = p1_.id LEFT JOIN page__page p2_ ON p0_.parent_id = p2_.id WHERE p1_.id IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) AND p0_.route_name = ?' with params [1, true, {"date":"2016-12-07 12:49:35.000000","timezone_type":3,"timezone":"Europe\/Moscow"}, {"date":"2016-12-07 12:49:35.000000","timezone_type":3,"timezone":"Europe\/Moscow"}, "foo", "bar", "", {"date":"2016-12-07 12:49:31.000000","timezone_type":3,"timezone":"Europe\/Moscow"}, null, true, false, null, null, null, null, "page_slug"]:

Catchable Fatal Error: Object of class DateTime could not be converted to string
```

**Comment by greg0ire** [comment]
Can you please provide a full stack trace

**Comment by greg0ire** [comment]
Also if you feel like it, bisect between 449d97b and the current commit to find the bad commit.

**Comment by Romashka** [comment]
This bug was introduced in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/650/commits/d3ff260c8faa4bf86aa84581f6a7c7355feb76db

**Comment by OskarStark** [comment]
@samuel4x4 can you help?

**Comment by samuel4x4** [comment]
@OskarStark sure, I'll check it today

**Comment by samuel4x4** [comment]
@Romashka I checked many times the subset of changes you indicated, I can't see something wrong and linked to the reported issue.

@Vesax I'm trying to understand your query but this condition "WHERE p1_.id IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)" with doesn't seems to receive the right parameters. I supposed they should all be integers but I see there are strings, dates, etc. Do I miss maybe something?

**Comment by Romashka** [comment]
@samuel4x4 the object in `$data['value']` is being converted to array, so the produced array contains public and protected properties of that object

**Comment by samuel4x4** [comment]
@Romashka this means that we can fix it this way:

```php
$data['value'] = (array)$data['value'];
```
replaced with

```php
$data['value'] = array($data['value']);
```

Am I right? I will open a PR to fix this.

**Comment by OskarStark** [comment]
Sounds good, please add a test for the new PR, too 👍
