### ISSUE TITLE
add select and having to createQuery in admin class

### ISSUE THREAD

**Issue by safwanghamrawi** [sonata-project/SonataDoctrineORMAdminBundle#655]
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              dev-develop 4565bdc The missing Symfony Admin Generator (forked from 3.10.2)
sonata-project/block-bundle              3.2.0               Symfony SonataBlockBundle
sonata-project/cache                     1.0.7               Cache library
sonata-project/core-bundle               3.1.2               Symfony SonataCoreBundle
sonata-project/doctrine-orm-admin-bundle 3.1.2               Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.7.0               Lightweight Exporter library
```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/monolog-bundle     3.0.1  Symfony MonologBundle
symfony/phpunit-bridge     v3.2.1 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.3.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.4.0 Symfony SwiftmailerBundle
symfony/symfony            v3.2.1 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 5.6.22-1~dotdeb+7.1 (cli) (built: May 26 2016 22:11:02)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with blackfire v1.13.0, https://blackfire.io, by Blackfireio Inc.
```

## Subject

Adding have clause to query in createQuery of my admin class

## Steps to reproduce
```php
    public function createQuery($context = 'list')
    {
        $query = parent::createQuery($context);
        $alias = $query->getRootAlias();
        $query
            ->addSelect("CASE WHEN (ord.idOrder > 0) THEN 1 ELSE 0 END AS HIDDEN chps14")
            ->leftJoin($alias.'.order', 'ord')
            ->andWhere($query->expr()->like($alias.'.entete', ':transaction'))
            ->setParameter('transaction', 'TRANSACTION')
            ->andWhere($query->expr()->gte($alias.'.paymentDate', ':date'))
            ->setParameter('date', '2016-12-09')
            ->having($query->expr()->eq('chps14', 0))
            ->andHaving($query->expr()->orX(
                $query->expr()->eq($alias.'.responseCode', ':code00'),
                $query->expr()->andX(
                    $query->expr()->eq($alias.'.responseCode', ':code24'),
                    $query->expr()->in($alias.".cardTypeIdx", array('ACCORD_3X','ACCORD_4X'))
                )
            ))
            ->setParameter('code00', '00')
            ->setParameter('code24', '24')
            ->orderBy($alias.'.paymentDate')
            ->addOrderBy($alias.'.paymentTime')
        ;

        return $query;
    }
````

## Expected results
I must have the list of entities but I got an SQL Error.
After hours spent, I got that the problem come from the function **getFixedQueryBuilder** in **sonata-project\doctrine-orm-admin-bundle\Datagrid\ProxyQuery.php** at ligne 331 when execute the queryBuilderId.

Thanks for your help
## Actual results
[1] Doctrine\ORM\Query\QueryException: [Semantical Error] line 0, col 180 near 'chps14 = 0 AND': Error: 'chps14' is not defined.
    at n/a
        in /var/www/sites/bazarchicbo/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63

    at Doctrine\ORM\Query\QueryException::semanticalError('line 0, col 180 near \'chps14 = 0 AND\': Error: \'chps14\' is not defined.', object(QueryException))
        in /var/www/sites/bazarchicbo/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php line 483

    at Doctrine\ORM\Query\Parser->semanticalError('\'chps14\' is not defined.', array('value' => 'chps14', 'type' => 100, 'position' => 180))
        in /var/www/sites/bazarchicbo/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php line 586

    at Doctrine\ORM\Query\Parser->processDeferredIdentificationVariables()
        in /var/www/sites/bazarchicbo/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php line 272

    at Doctrine\ORM\Query\Parser->getAST()
        in /var/www/sites/bazarchicbo/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php line 351

    at Doctrine\ORM\Query\Parser->parse()
        in /var/www/sites/bazarchicbo/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php line 281

    at Doctrine\ORM\Query->_parse()
        in /var/www/sites/bazarchicbo/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php line 293

    at Doctrine\ORM\Query->_doExecute()
        in /var/www/sites/bazarchicbo/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php line 969

    at Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(array(), 2)
        in /var/www/sites/bazarchicbo/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php line 924

    at Doctrine\ORM\AbstractQuery->execute(array(), 2)
        in /var/www/sites/bazarchicbo/vendor/sonata-project/doctrine-orm-admin-bundle/Datagrid/ProxyQuery.php line 332

    at Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery->getFixedQueryBuilder(object(QueryBuilder))
        in /var/www/sites/bazarchicbo/vendor/sonata-project/doctrine-orm-admin-bundle/Datagrid/ProxyQuery.php line 135

    at Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery->execute(array(), null)
        in /var/www/sites/bazarchicbo/vendor/sonata-project/admin-bundle/Datagrid/SimplePager.php line 81

    at Sonata\AdminBundle\Datagrid\SimplePager->getResults()
        in /var/www/sites/bazarchicbo/var/cache/dev/classes.php line 6077

    at Sonata\AdminBundle\Datagrid\Pager->initializeIterator()
        in /var/www/sites/bazarchicbo/vendor/sonata-project/admin-bundle/Datagrid/SimplePager.php line 130

    at Sonata\AdminBundle\Datagrid\SimplePager->init()
        in /var/www/sites/bazarchicbo/var/cache/dev/classes.php line 5535

    at Sonata\AdminBundle\Datagrid\Datagrid->buildPager()
        in /var/www/sites/bazarchicbo/var/cache/dev/classes.php line 5600

    at Sonata\AdminBundle\Datagrid\Datagrid->getForm()
        in /var/www/sites/bazarchicbo/vendor/sonata-project/admin-bundle/Controller/CRUDController.php line 106

    at Sonata\AdminBundle\Controller\CRUDController->listAction()
        in  line 

    at call_user_func_array(array(object(CRUDController), 'listAction'), array())
        in /var/www/sites/bazarchicbo/var/cache/dev/classes.php line 16006

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
        in /var/www/sites/bazarchicbo/var/cache/dev/classes.php line 15961

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
        in /var/www/sites/bazarchicbo/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 168

    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in /var/www/sites/bazarchicbo/web/app_dev.php line 28

[2] Doctrine\ORM\Query\QueryException: SELECT DISTINCT o.id, o.id AS __order_by FROM Bzc\CommonBundle\Entity\SipsLogTransaction o LEFT JOIN o.order ord WHERE o.entete LIKE :transaction AND o.paymentDate >= :date HAVING chps14 = 0 AND (o.responseCode = :code00 OR (o.responseCode = :code24 AND o.cardTypeIdx IN('ACCORD_3X', 'ACCORD_4X'))) ORDER BY o.paymentDate ASC, o.paymentTime ASC, o.id ASC
    at n/a
        in /var/www/sites/bazarchicbo/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 41

    at Doctrine\ORM\Query\QueryException::dqlError('SELECT DISTINCT o.id, o.id AS __order_by FROM Bzc\\CommonBundle\\Entity\\SipsLogTransaction o LEFT JOIN o.order ord WHERE o.entete LIKE :transaction AND o.paymentDate >= :date HAVING chps14 = 0 AND (o.responseCode = :code00 OR (o.responseCode = :code24 AND o.cardTypeIdx IN(\'ACCORD_3X\', \'ACCORD_4X\'))) ORDER BY o.paymentDate ASC, o.paymentTime ASC, o.id ASC')
        in /var/www/sites/bazarchicbo/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php line 483

    at Doctrine\ORM\Query\Parser->semanticalError('\'chps14\' is not defined.', array('value' => 'chps14', 'type' => 100, 'position' => 180))
        in /var/www/sites/bazarchicbo/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php line 586

    at Doctrine\ORM\Query\Parser->processDeferredIdentificationVariables()
        in /var/www/sites/bazarchicbo/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php line 272

    at Doctrine\ORM\Query\Parser->getAST()
        in /var/www/sites/bazarchicbo/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php line 351

    at Doctrine\ORM\Query\Parser->parse()
        in /var/www/sites/bazarchicbo/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php line 281

    at Doctrine\ORM\Query->_parse()
        in /var/www/sites/bazarchicbo/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php line 293

    at Doctrine\ORM\Query->_doExecute()
        in /var/www/sites/bazarchicbo/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php line 969

    at Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(array(), 2)
        in /var/www/sites/bazarchicbo/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php line 924

    at Doctrine\ORM\AbstractQuery->execute(array(), 2)
        in /var/www/sites/bazarchicbo/vendor/sonata-project/doctrine-orm-admin-bundle/Datagrid/ProxyQuery.php line 332

    at Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery->getFixedQueryBuilder(object(QueryBuilder))
        in /var/www/sites/bazarchicbo/vendor/sonata-project/doctrine-orm-admin-bundle/Datagrid/ProxyQuery.php line 135

    at Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery->execute(array(), null)
        in /var/www/sites/bazarchicbo/vendor/sonata-project/admin-bundle/Datagrid/SimplePager.php line 81

    at Sonata\AdminBundle\Datagrid\SimplePager->getResults()
        in /var/www/sites/bazarchicbo/var/cache/dev/classes.php line 6077

    at Sonata\AdminBundle\Datagrid\Pager->initializeIterator()
        in /var/www/sites/bazarchicbo/vendor/sonata-project/admin-bundle/Datagrid/SimplePager.php line 130

    at Sonata\AdminBundle\Datagrid\SimplePager->init()
        in /var/www/sites/bazarchicbo/var/cache/dev/classes.php line 5535

    at Sonata\AdminBundle\Datagrid\Datagrid->buildPager()
        in /var/www/sites/bazarchicbo/var/cache/dev/classes.php line 5600

    at Sonata\AdminBundle\Datagrid\Datagrid->getForm()
        in /var/www/sites/bazarchicbo/vendor/sonata-project/admin-bundle/Controller/CRUDController.php line 106

    at Sonata\AdminBundle\Controller\CRUDController->listAction()
        in  line 

    at call_user_func_array(array(object(CRUDController), 'listAction'), array())
        in /var/www/sites/bazarchicbo/var/cache/dev/classes.php line 16006

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
        in /var/www/sites/bazarchicbo/var/cache/dev/classes.php line 15961

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
        in /var/www/sites/bazarchicbo/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 168

    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in /var/www/sites/bazarchicbo/web/app_dev.php line 28

**Comment by greg0ire** [comment]
See that "Stack Trace (Plain Text) part at the end? That's what you should copy instead of your image. Indexing robots don't care about images. Plus it's hard to read.

**Comment by safwanghamrawi** [comment]
What I did:
I commented these two lines (312, 313):
`

        $queryBuilderId->resetDQLPart('select');
        $queryBuilderId->add('select', 'DISTINCT '.$idxSelect);`
and I add a try catch line 340:
`

        foreach ($results as $id) {
            foreach ($idNames as $idName) {
                // Convert ids to database value in case of custom type, if provided.
                $fieldType = $metadata->getTypeOfField($idName);
                try {
                    $idxMatrix[$idName][] = $fieldType && Type::hasType($fieldType)
                        ? Type::getType($fieldType)->convertToDatabaseValue($id[$idName], $platform)
                        : $id[$idName];
                } catch (\Exception $e) {
                    $current = reset($id);
                    $idxMatrix[$idName][] = $current[$idName];
                }

            }
        }
`

I hope that there is better solution.

Thanks

**Comment by greg0ire** [comment]
Why not `WHERE ord.idOrder > 0` or `HAVING ord.idOrder > 0` directly? Doesn't it work?

**Comment by safwanghamrawi** [comment]
Doesn't work, the problem is when I add having clause :)

**Comment by greg0ire** [comment]
Why would you use "having" rather than "where" here?

**Comment by safwanghamrawi** [comment]
I tried but I don't have the same results :)
I don't know why results are differents, but that's why I have to use "having"

**Comment by safwanghamrawi** [comment]
Finally, I forked the bundle and I have modified the function getFixedQueryBuilder in Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery:
`

    /**
     * This method alters the query to return a clean set of object with a working
     * set of Object.
     *
     * @param QueryBuilder $queryBuilder
     *
     * @return QueryBuilder
     */
    protected function getFixedQueryBuilder(QueryBuilder $queryBuilder)
    {
        $queryBuilderId = clone $queryBuilder;
        $rootAlias = current($queryBuilderId->getRootAliases());

        // step 1 : retrieve the targeted class
        $from = $queryBuilderId->getDQLPart('from');
        $class = $from[0]->getFrom();
        $metadata = $queryBuilderId->getEntityManager()->getMetadataFactory()->getMetadataFor($class);

        // step 2 : retrieve identifier columns
        $idNames = $metadata->getIdentifierFieldNames();

        // step 3 : retrieve the different subjects ids
        $selects = array();
        $idxSelect = '';
        foreach ($idNames as $idName) {
            $select = sprintf('%s.%s', $rootAlias, $idName);
            // Put the ID select on this array to use it on results QB
            $selects[$idName] = $select;
            // Use IDENTITY if id is a relation too. See: http://doctrine-orm.readthedocs.org/en/latest/reference/dql-doctrine-query-language.html
            // Should work only with doctrine/orm: ~2.2
            $idSelect = $select;
            if ($metadata->hasAssociation($idName)) {
                $idSelect = sprintf('IDENTITY(%s) as %s', $idSelect, $idName);
            }
            $idxSelect .= ($idxSelect !== '' ? ', ' : '').$idSelect;
        }
        if ($queryBuilder->getDQLPart('having') === null) {
            $queryBuilderId->resetDQLPart('select');
            $queryBuilderId->add('select', 'DISTINCT '.$idxSelect);
        }


        // for SELECT DISTINCT, ORDER BY expressions must appear in idxSelect list
        /* Consider
            SELECT DISTINCT x FROM tab ORDER BY y;
        For any particular x-value in the table there might be many different y
        values.  Which one will you use to sort that x-value in the output?
        */
        // todo : check how doctrine behave, potential SQL injection here ...
        if ($this->getSortBy()) {
            $sortBy = $this->getSortBy();
            if (strpos($sortBy, '.') === false) { // add the current alias
                $sortBy = $rootAlias.'.'.$sortBy;
            }
            $sortBy .= ' AS __order_by';
            $queryBuilderId->addSelect($sortBy);
        }

        $results = $queryBuilderId->getQuery()->execute(array(), Query::HYDRATE_ARRAY);
        $platform = $queryBuilderId->getEntityManager()->getConnection()->getDatabasePlatform();
        $idxMatrix = array();

        foreach ($results as $id) {
            foreach ($idNames as $idName) {
                // Convert ids to database value in case of custom type, if provided.
                $fieldType = $metadata->getTypeOfField($idName);
                $current = reset($id);
                if (is_array($current) && array_key_exists($idName, $current)) {
                    $idxMatrix[$idName][] = $current[$idName];
                } else {
                    $idxMatrix[$idName][] = $fieldType && Type::hasType($fieldType)
                        ? Type::getType($fieldType)->convertToDatabaseValue($id[$idName], $platform)
                        : $id[$idName];
                }
            }
        }

        // step 4 : alter the query to match the targeted ids
        foreach ($idxMatrix as $idName => $idx) {
            if (count($idx) > 0) {
                $idxParamName = sprintf('%s_idx', $idName);
                $idxParamName = preg_replace('/[^\w]+/', '_', $idxParamName);
                $queryBuilder->andWhere(sprintf('%s IN (:%s)', $selects[$idName], $idxParamName));
                $queryBuilder->setParameter($idxParamName, $idx);
                $queryBuilder->setMaxResults(null);
                $queryBuilder->setFirstResult(null);
            }
        }

        return $queryBuilder;
    }`

I added an if before resetDQLPart
`

    if ($queryBuilder->getDQLPart('having') === null) {
        $queryBuilderId->resetDQLPart('select');
        $queryBuilderId->add('select', 'DISTINCT '.$idxSelect);
    }`

And added another if in foreachResults:
`


    if (is_array($current) && array_key_exists($idName, $current)) {
        $idxMatrix[$idName][] = $current[$idName];
    } else {
        $idxMatrix[$idName][] = $fieldType && Type::hasType($fieldType)
            ? Type::getType($fieldType)->convertToDatabaseValue($id[$idName], $platform)
            : $id[$idName];
    }`
