### ISSUE TITLE
sonata_type_model_list needs a query/query_builder option

### ISSUE THREAD

**Issue by andrewmy** [sonata-project/SonataDoctrineORMAdminBundle#686]
## Subject

Not sure if it's a bug or a feature request. There seems to be no way to filter the list when using a `sonata_type_model_list` field.

This is achievable with `sonata_type_model` or `EntityType`, but not the full-featured list.

Looking at the AJAX call, the child list doesn't even know the parent subject's ID, just the admin's uniqid which is not helpful.

**Comment by kunicmarko20** [comment]
Will you be able to provide a PR for this?
