### ISSUE TITLE
ChoiceList deprecated in Symfony 3+

### ISSUE THREAD

**Issue by fliespl** [sonata-project/SonataDoctrineORMAdminBundle#691]
## Steps to reproduce
Use symfony 3.2. Create class with discriminator column. Set subclasses on admin class. Add filter to admin class:

`
 ->add('badge_type', 'doctrine_orm_class', array('sub_classes' => $this->getSubClasses()))
`

## Expected results
No error.

## Actual results
Error with importing `Symfony\Component\Form\ChoiceList\ChoiceList`. I twas removed in symfony 3.0.

Should be replaced with `Symfony\Component\Form\ChoiceList\ArrayChoiceList`.

File: ClassFilter.php

```
Attempted to load class "ChoiceList" from namespace "Symfony\Component\Form\Extension\Core\ChoiceList".
Did you forget a "use" statement for another namespace?
```

**Comment by OskarStark** [comment]
which versions are you using?

**Comment by fliespl** [comment]
"sonata-project/admin-bundle": "3.10.0",
        "sonata-project/doctrine-orm-admin-bundle": "3.1.1",

**Comment by OskarStark** [comment]
can you try to upgrade admin bundle?

**Comment by fliespl** [comment]
```
composer update sonata-project/doctrine-orm-admin-bundle sonata-project/admin-bundle
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
```

Yet problem lies in ClassFilter inside Doctrine ORM Admin Bundle `Sonata\DoctrineORMAdminBundle\Filter\ClassFilter`. Rewriting getFIeldOptions method to below example works:

```
    /**
     * {@inheritdoc}
     */
    public function getFieldOptions()
    {
        return $this->getOption('choices', array(
            'required' => false,
            'choices' => $this->getOption('sub_classes')
        ));
    }
```

**Comment by OskarStark** [comment]
hmm, but admin-bundle 3.18.2 is currently the latest release

**Comment by fliespl** [comment]
Same happens with such versions:

        "sonata-project/admin-bundle": "3.18.2",
        "sonata-project/doctrine-orm-admin-bundle": "3.1.1",

**Comment by Jeace** [comment]
I can confirm this problem with :

> "name": "sonata-project/admin-bundle",
> "version": "3.18.2",

and

> "name": "sonata-project/doctrine-orm-admin-bundle",
> "version": "3.1.4",

**Comment by greg0ire** [comment]
Link to the offending line for the lazy : https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/Filter/ClassFilter.php#L71

**Comment by greg0ire** [comment]
@Jeace @fliespl  would you please provide a PR for this ?

**Comment by eugenekurasov** [comment]
Hi, 
For PR we need to change dependency of symfony/form. 
Maybe, we need to remove non-supported versions?

**Comment by jlamur** [comment]
@eugenekurasov It's not needed. Please check https://github.com/sonata-project/SonataAdminBundle/pull/4529.

**Comment by jlamur** [comment]
@eugenekurasov To elaborate: you can check if `ArrayChoiceList` exists (with `class_exists`), and if not, fallback to using `ChoiceList`. Don't forget to add `NEXT_MAJOR` comments to remove the check you add (because the next major will support SF 2.8+).
