### ISSUE TITLE
configureDatagridFilters doesn't recognize fields from a trait

### ISSUE THREAD

**Issue by blixit** [sonata-project/SonataDoctrineORMAdminBundle#695]
Original issue : [https://github.com/sonata-project/SonataAdminBundle/issues/4524](https://github.com/sonata-project/SonataAdminBundle/issues/4524)
@jlamur suggested me to reopen the issue in this repository.

### Environment
Linux

#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.19.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.4.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.1.5  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.7.1  Lightweight Exporter library
```

#### Symfony packages

```bash
$ composer show symfony/*
 symfony/monolog-bundle     v3.1.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.3.2 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.4.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.4.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.4.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.4.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.4.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.4.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.2 Symfony SwiftmailerBundle
symfony/symfony            v3.3.2 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

## Subject

I have an entity 'Examen' which use a trait with 2 fields (costHt and costTtc).
These fields work fine in the methods (configureListFields, configureFormFields, configureShowFields) of ExamenAdmin but raise an error while used in configureDatagridFilters().

```php
protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('id')->add('value')->add('certificated')
            ->add('costHt')->add('costTtc');    // <-- raises error
    }
protected function configureShowFields(ShowMapper $showMapper)
    {
        $showMapper
            ->add('id')->add('parameter')->add('value')->add('certificated')
            ->add('costHt')->add('costTtc')  // <-- works fine
        ;
    }
```

## Steps to reproduce

Create an entity 'Entity'
Create a trait 'Able' with doctrine fields
Use the trait 'Able' in the entity 'Entity'
Create EntityAdmin class
Configure DatagridFilters with 'Able' fields

## Expected results

I expect required fields added to filter

## Actual results

**Notice: Undefined index: costHt**
Here is the stacktrace after error detection.

-in vendor/sonata-project/doctrine-orm-admin-bundle/Guesser/FilterTypeGuesser.php (line 69)
FilterTypeGuesser->guessType('AppBundle\\Entity\\Examen', 'costHt', object(ModelManager))
-in vendor/sonata-project/admin-bundle/Guesser/TypeGuesserChain.php (line 55)
TypeGuesserChain->Sonata\AdminBundle\Guesser\{closure}(object(FilterTypeGuesser))
-in vendor/sonata-project/admin-bundle/Guesser/TypeGuesserChain.php (line 73)
TypeGuesserChain->guess(object(Closure))
-in vendor/sonata-project/admin-bundle/Guesser/TypeGuesserChain.php (line 56)
TypeGuesserChain->guessType('AppBundle\\Entity\\Examen', 'costHt', object(ModelManager))
-in vendor/sonata-project/doctrine-orm-admin-bundle/Builder/DatagridBuilder.php (line 105)
DatagridBuilder->addFilter(object(Datagrid), null, object(FieldDescription), object(ExamenAdmin))
-in vendor/sonata-project/admin-bundle/Datagrid/DatagridMapper.php (line 89)
DatagridMapper->add('costHt')
-in src/AdminBundle/Admin/ExamenAdmin.php (line 23)

For more, please follow the discussion [https://github.com/sonata-project/SonataAdminBundle/issues/4524](https://github.com/sonata-project/SonataAdminBundle/issues/4524 )

**Comment by jlamur** [comment]
Here is a copy/paste of suggested fixes related with this issue:

> - The exception must be more verbose (something like No mapping found for field 'costHt'),
> - The DatagridMapper/Builder should be consistent with other Builders by accepting entity field names (and not column names).

@blixit Can you try to write a PR?

**Comment by jlamur** [comment]
@blixit The error (undefined index) is raised here : 
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/Guesser/FilterTypeGuesser.php#L69

You could fix it by calling this function [Doctrine\ORM\Mapping\ClassMetadataInfo::hasField($fieldName)](http://www.doctrine-project.org/api/orm/2.5/class-Doctrine.ORM.Mapping.ClassMetadataInfo.html#_hasField), and then throw a better exception.

**Comment by blixit** [comment]
I did the change on my vendor directory (temporarly) and the new exception message is better. Thanks.

Before to start writing which could be my first real PR I really do need clarifications. 

> * The DatagridMapper/Builder should be consistent with other Builders by accepting entity field names (and not column names).

I agree. To solve this I read the files which appear in the stacktrace and  the class FilterTypeGuesser in particular. I checked that the metadata returned by **Sonata\AdminBundle\Model\ModelManagerInterface->getParentMetadataForProperty()**  contain informations from the Doctrine annotations of my trait. 

This is what I did. I replaced the line 69 with : 

```php
if( ! $metadata->hasField($propertyName)){
  $columnName = $metadata->getColumnName($propertyName);
  if(empty($columnName))
    throw new \RuntimeException("No mapping found for field '$propertyName' in $class");
  else
    $options['field_name'] = $columnName; // I force use of column name
}else{
  // default behavior
  $options['field_name'] = $metadata->fieldMappings[$propertyName]['fieldName'];
}
```
The error described in the issue is solved with this code but another one is opened. 
Actually, if I try to use the filter by submitting a value, I get a semantical error :
```
[Semantical Error] 
line 0, col 74 near 'cost_ttc LIKE': Error: Class AppBundle\Entity\Examen 
has no field or association named cost_ttc
```
This last error is a false positive since my class 'Examen' uses a trait which contains that field declaration. Here is a part of my trait definition : 
```php
trait PricesableTrait{
//...
/**
* @var float $costTtc
* @Column(name="cost_ttc", type="float", nullable=false, options={"default":0})
*/
 private $costTtc = 0;
//...
```

What should I do now ? Write a partial PR to just add the verbose mode or wait to have more informations about the issue ?

**Comment by jlamur** [comment]
> What should I do now ? Write a partial PR to just add the verbose mode

Yes you should.

I'm trying to reproduce the column name issue to help you.

**Comment by blixit** [comment]
Ok. It's done. I sent a PR !

**Comment by OskarStark** [comment]
@blixit i currently have not much time, you can support this PR https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/676 if you could write some tests

**Comment by OskarStark** [comment]
I closed the #599

**Comment by jlamur** [comment]
@blixit I can't reproduce the column name bug.

Did you really try this on a brand new project?

> Create an entity 'Entity'
Create a trait 'Able' with doctrine fields
Use the trait 'Able' in the entity 'Entity'
Create EntityAdmin class
Configure DatagridFilters with 'Able' fields

**Comment by blixit** [comment]
> @blixit i currently have not much time, you can support this PR #676 if you could write some tests

@OskarStark I will try on my free time.

> Did you really try this on a brand new project?

@jlamur you're right, I didn't. I've  given what seemed to be the minimal requirement for reproducing the bug since. I will try that on a new project

**Comment by OskarStark** [comment]
> @OskarStark I will try on my free time.

tests are already done @blixit
