### ISSUE TITLE
DoctrineORMAdmin 3.1.6 (from PR#676) breaks boolean filters on env=prod

### ISSUE THREAD

**Issue by BigBadBassMan** [sonata-project/SonataDoctrineORMAdminBundle#701]
Refs #676

### Environment
Linux/Apache/MariaDB

#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.20.1             The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2              Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              Cache library
sonata-project/core-bundle               3.4.0              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1              Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.1.5              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.x-dev 7e7fec9    Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1              Lightweight Exporter library
sonata-project/intl-bundle               dev-master d2eab1c Symfony SonataIntlBundle
```
#### Symfony packages

```bash
$ composer show symfony/*
# Put the result here.
symfony/assetic-bundle     v2.8.1 Integrates Assetic into Symfony2
symfony/monolog-bundle     v3.1.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.3.4 Symfony PHPUnit Bridge
symfony/polyfill-intl-icu  v1.4.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.4.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.4.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.4.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.4.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.2 Symfony SwiftmailerBundle
symfony/symfony            v3.3.4 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.0.20 (cli) (built: Jun  7 2017 04:59:25) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.20, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

## Subject
Properly defined and working admin and entity (verified on numerous releases up to DoctrineORMBundle 3.1.5) with valid doctrine mapping, and at least one filter on a bool field (according to Symfony code style bool was used instead of boolean). Admin works as expected, when in dev-env, but not from prod.

cache:clear makes no difference.

Entity (excerpt, much longer but not relevant):
```php
/**
 * Course
 *
 * @ORM\Table(name="lehrangebot")
 * @ORM\Entity(repositoryClass="Namespace\Bundlename\Repository\CourseRepository")
 */
class Course
{

    /**
     *
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     *
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=100, nullable=false)
     */
    private $title;

    /**
     *
     * @var bool
     *
     * @ORM\Column(name="winterterm", type="boolean", nullable=true)
     */
    private $winterterm;

    /**
     *
     * @var bool
     *
     * @ORM\Column(name="summerterm", type="boolean", nullable=true)
     */
    private $summerterm;
}
```

Admins filter setup:
```php
    protected function configureDatagridFilters(DatagridMapper $filter)
    {
        $filter->add('title')
            ->add('winterterm')
            ->add('summerterm')
    }
```

## Steps to reproduce
Call admin from prod env (this is important, for some reason, "dev" works fine!)

## Expected results
Admin shows and is completely usable.

## Actual results
Browser: Error 500

Log:
(Paths and Bundlenames have been altered to preserve privacy.)
```
request.INFO: Matched route "bundlename_course-admin_list". {"route":"bundlename_course-admin_list","route_parameters":{"_controller":"Namespace\\Bundle\\Controller\\CourseAdminController::listAction","_sonata_admin":"bundlename.admin.course","_sonata_name":"bundlename_course-admin_list","_route":"bundlename_course-admin_list"},"request_uri":"http://localhost/admin/course/list","method":"GET"} []
[2017-07-07 10:13:45] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-07-07 10:13:45] request.CRITICAL: Uncaught PHP Exception Sonata\DoctrineORMAdminBundle\Model\MissingPropertyMetadataException: "No metadata found for property `Namespace\Bundlename\Entity\Course::$summerterm`. Please make sure your Doctrine mapping is properly configured." at /pathtoproject/vendor/sonata-project/doctrine-orm-admin-bundle/Guesser/FilterTypeGuesser.php line 71 {"exception":"[object] (Sonata\\DoctrineORMAdminBundle\\Model\\MissingPropertyMetadataException(code: 0): No metadata found for property `Namespace\\Bundlename\\Entity\\Course::$summerterm`. Please make sure your Doctrine mapping is properly configured. at /pathtoproject/vendor/sonata-project/doctrine-orm-admin-bundle/Guesser/FilterTypeGuesser.php:71)"} []
```

**Comment by OskarStark** [comment]
But `winterterm` is working? They look similar

**Comment by OskarStark** [comment]
> Call admin from prod env (this is important, for some reason, "dev" works fine!)

This would crash on `dev`, too. Did you added the new field? Did you added setters/getters and updated the schema on `prod`?

**Comment by BigBadBassMan** [comment]
The Model and admin where complete defined, and working fully. Getters/Setters do exist, schema is in sync on both dev and prod.
I did not change a single line, but just updated my bundles via composer update - bam!
I do not know, why it keeps complaining about this specific property, maybe because it comes first, when ordered aplhabetically...

**Comment by OskarStark** [comment]
you executed composer update on prod, but not on dev?

can you please post the output of `composer show | grep sonata-project` (dev and prod please)

**Comment by BigBadBassMan** [comment]
Nope, sorry for the misunderstanding.
I'm working on the same project (and directory structure), just using different controllers or parameters to access `prod/dev` databases and environments.

composer show gives this, when I'm on DoctrineORMAdmin 3.1.6:
```
sonata-project/admin-bundle              3.20.1             The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2              Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              Cache library
sonata-project/core-bundle               3.4.0              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1              Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.1.6              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.x-dev 7e7fec9    Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1              Lightweight Exporter library
sonata-project/intl-bundle               dev-master d2eab1c Symfony SonataIntlBundle
```
downgrading to 3.1.5 fixes the problem, and lets me acces my admin on `prod` and `dev`, switching to 3.1.6 breaks prod.

**Comment by eugenekurasov** [comment]
Hi, did you try manually removed folder with prod cache? 
For symfony ~3 - var/cache/prod
For symfony ~2 - app/cache/prod

**Comment by BigBadBassMan** [comment]
I used the cache:clear (with and without cache:warmup afterwards) commands.
Just tried `rm -rf``ing the cache folders, no difference. Browser gets HTTP/500, log message same as above.

I had a hunch, that the boolean and nullable nature of the fields could be the problem, changed definition to `@ORM\Column(name="summerterm", type="boolean", nullable=false, options={"default": false})` and made sure my data did not contain `null` values, no change in behaviour.

The `$summerterm` field is defined exactly the same way as `$winterterm`, but the FieldTypeGuesser is not able to figure it out.

Noticed something strange with v3.1.5 tough:

- defining the `List view`without a field type, SonataAdmin guesses $winterterm correctly, but fails on $summerterm, displays an empty column instead
- defining the field type as `'sonata_type_boolean'` gives the beautiful `green/red yes/no` badges with the correct values!

Will create a separate project with just the bare minimum to narrow down this issue...

**Comment by eugenekurasov** [comment]
1) 'cache:clear' run with warmup by default
https://github.com/symfony/symfony/blob/3.3/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php
2) Can you give your example of use cache:clear command?

**Comment by eugenekurasov** [comment]
Can you also try run `doctrine:cache:clear-metadata --env=prod --no-debug`?

**Comment by BigBadBassMan** [comment]
Okay, this is getting deep....

I usually use: `bin/console cache:clear --env=prod` but since sf3.3 I lean to 
```
bin/console cache:clear --no-warmup --env=prod
bin/console cache:warmup
```
`doctrine:cache:clear-metadata --env=prod --no-debug` failed because of me using APC, so I did the sf3.3 commands above, and added `apcu_clear_cache ();` to my `prod`-controller.

Now's the thing: The Admin loads fine without problems.! 
APCu was not correctly cleared, and fed false data to symfony/sonata...
