### ISSUE TITLE
sonata_type_model_list dialog edit button

### ISSUE THREAD

**Issue by kunicmarko20** [sonata-project/SonataDoctrineORMAdminBundle#707]
Hi all,

I guess this is a question or a feature request.
Why we can't replace add button with dialog edit button if an object is already set in sonata_type_model_list.

by replacing lines 85-94 from [here](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/Resources/views/Form/form_admin_fields.html.twig#L85).

with something like:

```jinja
{% if sonata_admin.field_description.associationadmin.hasroute('create') and sonata_admin.field_description.associationadmin.isGranted('CREATE') and btn_add and sonata_admin.value == null %}
    <a  href="{{ sonata_admin.field_description.associationadmin.generateUrl('create') }}"
                        onclick="return start_field_dialog_form_add_{{ id }}(this);"
                        class="btn btn-success btn-sm sonata-ba-action"
                        title="{{ btn_add|trans({}, btn_catalogue) }}"
    >
        <i class="fa fa-plus-circle"></i>
        {{ btn_add|trans({}, btn_catalogue) }}
    </a>
{% elseif sonata_admin.field_description.associationadmin.hasroute('edit') and sonata_admin.field_description.associationadmin.isGranted('EDIT') and btn_edit and sonata_admin.value != null %}
    <a  href="{{ sonata_admin.field_description.associationadmin.generateUrl('edit', {'id' : sonata_admin.value.id}) }}"
                        onclick="return start_field_dialog_form_add_{{ id }}(this);"
                        class="btn btn-warning btn-sm sonata-ba-action"
                        title="{{ btn_edit|trans({}, btn_catalogue) }}"
    >
        <i class="fa fa-pencil"></i>
        {{ btn_edit|trans({}, btn_catalogue) }}
    </a>
{% endif %}
```

we would get edit button that opens edit in dialog instead of add, but then [ModelListType](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Form/Type/ModelListType.php) in SonataAdminBundle
would need to support `btn_edit` option and maybe instead of using `onclick="return start_field_dialog_form_add_{{ id }}(this);` for edit and add, that function could be renamed or we could add new javascript function for edit.

This looks like a simple thing to change is there maybe something I am missing and not taking into consideration?

**Comment by jlamur** [comment]
Hello @kunicmarko20.

In my opinion such feature would be appreciated.
Could you please open a PR for it? It is the best way for everyone to see if you are *"missing something"* anyway :)
