### ISSUE TITLE
DatagridFilters use "doctrine_orm_model_autocomplete" will be very slow when in Large Datasets

### ISSUE THREAD

**Issue by askuiop** [sonata-project/SonataDoctrineORMAdminBundle#799]
sonata-admin DatagridFilters entity use "doctrine_orm_model_autocomplete" will be very slow when in Large Datasets:

The problem SQL is :

309.11 ms
SELECT DISTINCT p0_.id AS id_0, p0_.id AS id_1
FROM project p0_
LEFT JOIN company c1_
ON p0_.company_id = c1_.id
ORDER BY p0_.id DESC LIMIT 11 OFFSET 0

**Comment by jordisala1991** [comment]
Duplicated of https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/473

Closing
