### ISSUE TITLE
Deprecation notice about "sonata.admin.audit.orm.reader service is private"

### ISSUE THREAD

**Issue by valkars** [sonata-project/SonataDoctrineORMAdminBundle#801]
### Environment
Any
#### Sonata packages
sonata-project/admin-bundle              3.31.0 3.31.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.11.0 3.11.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.9.0  3.9.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.4.1  3.4.1  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.8.0  1.8.0  Lightweight Exporter library
sonata-project/intl-bundle               2.4.0  2.4.0  Symfony SonataIntlBundle
#### Symfony packages
symfony/symfony                             v3.4.3
simplethings/entity-audit-bundle   v1.0.6
#### PHP version
7.2.1
## Subject
Symfony 3.4, SimpleThingsEntityAuditBundle + Sonata bundles. After opening of "Show revisions" (e.g. /app/admin/1/history) - there is deprecation notice:
`User Deprecated: The "sonata.admin.audit.orm.reader" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.
{▼
vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:275 {▶}
vendor/sonata-project/admin-bundle/src/Model/AuditManager.php:61 {▶}
vendor/sonata-project/admin-bundle/src/Controller/CRUDController.php:709 {▶}
vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151 {▶`

I guess that the easiest solution is to add public="true" to https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Resources/config/audit.xml#L4
Or maybe to change the whole concept.
## Steps to reproduce
Open "Show revisions" on any audited entity
## Expected results
No deprecations
## Actual results
User Deprecated: The "sonata.admin.audit.orm.reader" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0

**Comment by core23** [comment]
Can you provide a PR please

**Comment by valkars** [comment]
Done, my 1st try 😟
