### ISSUE TITLE
Incorrect count query when entity have composite key

### ISSUE THREAD

**Issue by lainosantos** [sonata-project/SonataDoctrineORMAdminBundle#821]
The count query doesn't get all colluns of entity keys, this cause incorrect result in composite key.

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/af162590f204fd94ac0a6e05150cbc1940470ef5/src/Datagrid/Pager.php#L39-L43

**Comment by jordisala1991** [comment]
This is a duplicate of #497 

Closing
