### ISSUE TITLE
Symfony 3.4: Services are private by default and ACLs

### ISSUE THREAD

**Issue by Warxcell** [sonata-project/SonataDoctrineORMAdminBundle#846]
sonata-project/admin-bundle: 3.38.3
sonata-project/doctrine-orm-admin-bundle 3.6.1

Today I setup ACLs for Objects, then I ran command: 

`bin/console sonata:admin:generate-object-acl` to generate ACLs for objects so far.

But I got bunch of 
`Admin class is using a manager type that has no manipulator implemented : ignoring`.

When I make `<service id="sonata.admin.manipulator.acl.object.orm" class="%sonata.admin.manipulator.acl.object.orm.class%"/>`

public this fixes the issue. 

https://symfony.com/blog/new-in-symfony-3-4-services-are-private-by-default

**Comment by Warxcell** [comment]
I guess the easiest way is to make service public.

**Comment by kunicmarko20** [comment]
@warxcell can you provide a PR, please?
