### ISSUE TITLE
Logical bug in ModelManager::getIdentifierValues()

### ISSUE THREAD

**Issue by stefanides** [sonata-project/SonataDoctrineORMAdminBundle#866]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.40.2 3.42.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1 3.13.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.11.2 3.12.0 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.4.0  2.4.0  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.6.2  3.6.3  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.9.1  1.9.1  Lightweight Exporter library
sonata-project/intl-bundle               2.5.0  2.5.0  Symfony SonataIntlBundle
```
Same code is present in the recent master (https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/src/Model/ModelManager.php), so above versions are not important for the report. 

#### Symfony packages

```
v4.1.6
```

#### PHP version

```
$ php -v
PHP 7.2.2
```
## Subject

Hello, 

for few hours I am already facing the strange behaviour when using composite primary key in admin. Now I see that the `getIdentifierValues()` method of `ModelManager` class contains a logical error (copying and commenting just the relevant code): 
```
class ModelManager
{
....
 public function getIdentifierValues($entity)
 {
        $metadata = $this->getMetadata($class); // get entity's metadata
        ...
        ...
        foreach ($metadata->getIdentifierValues($entity) as $name => $value) {
            ...
            $fieldType = $metadata->getTypeOfField($name, true);
            $type = $fieldType ....
            if ($type) { // if simple type, continue
                ...
                continue;
            }
            // if not simple type, try to load its class and metadata
            $metadata = $this->getMetadata(ClassUtils::getClass($value));
            // but what - the original $metadata gets overwritten here!? 
            // so the next foreach the call $metadata->getTypeOfField() will return incorrect value!
            ....
        }
  }
```

## Steps to reproduce
Reproducible only if one entity's Id attribute is entity and the following Id is of simple type. (Primary keys in the other order work OK)

## Expected results
`$metadata `remains unchanged until foreach loop ends = variable inside foreach requires a different  name(!)

## Actual results
The original `$metadata` gets overwritten and the next foreach the call `$metadata->getTypeOfField()` does not work correctly.

**Comment by stefanides** [comment]
The bug is still there in the latest version. It can be reproduced only when listing fields in order object first, then plain value. Opposite order works OK (unless $metadata gets rewritten with object field). 

To continue I would just need to check it by someone with more bundle's knowledge - whether this is a real bug or it may be some intention behind? Then I can try PR to fix it :-)

**Comment by VincentLanglet** [comment]
@stefanides What is the error message you get ? Did you try to modify the code in your vendor ? Does it fix the bug ? 

You welcome to make a PR and add a test about this, that's the best way to confirm it works.

**Comment by stefanides** [comment]
The error message does not lead to the reason, in my case (in simple list action in Admin class) it reports `No entity manager defined for class DateTime2string` (class is not an Entity - EM cannot be used). If the second key is not a class, the error message differs. 

The example of Entity follows
```
class Statistic
{       
    /**
     * @var Webring
     *
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="NONE")
     * @ORM\ManyToOne(targetEntity="App\Entity\Webring")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="UIDWebring", referencedColumnName="UID", nullable=false)
     * })
     */
    private $webring;

    /**
     * @var DateTime2string
     *
     * @ORM\Column(name="DT", type="date2string", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="NONE")
     */
    private $dt;
...
}
```

When `ModelManager::getIdentifierValues()` method goes through the `@ORM\Id` keys, then if `$webring` is first, it overwrites `$metadata` value. One solution/workaround is to swap order of `$webring` and `$dt` in the Entity. Then you do not need to change files in /vendor - unless you meet the same condition with composite key elsewhere. The other solution is to fix the `getIdentifierValues()` and yes, to rename second `$metadata` in the loop works :)

PR for the fix is easy, but probably I am not able to make a test (until study all requirements and related classes around that, which could take me several hours :( )

**Comment by VincentLanglet** [comment]
> PR for the fix is easy, but probably I am not able to make a test (until study all requirements and related classes around that, which could take me several hours :( )

@stefanides Do you mind opening a PR with the fix ? We'll see together if a test is possible.

**Comment by stefanides** [comment]
This looks to be already fixed in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/commit/6d028b764df40786426cd19203542b7493411044 :-)
