### ISSUE TITLE
oneToMany relations without a join table don't persist

### ISSUE THREAD

**Issue by arnaugm** [sonata-project/SonataDoctrineORMAdminBundle#9]
I would like to add the oneToMany relations in the entities edit screens.

I have, for example, these admin classes:
PhoneTypeAdmin
PhoneNumberAdmin
and one PhoneType has many PhoneNumbers, so the PhoneNumber class has the foreing key pointing the PhoneType.

The PhoneTypeAdmin configureFormFields function looks like this:
<pre>
public function configureFormFields(FormMapper $formMapper)
{
	$formMapper
		// fields
		->add('name')
		// oneToMany
		->add('phoneNumbers', null, array(
			'required' => false
		))
	;
}
</pre>
With this, what I see in the PhoneType edit screen is a multiple select box with the list of PhoneNumbers, which is great.
The problem is that if I click a PhoneNumber and press the Update button, the relation is not persisted.

I have read about the owner and inversed roles in doctrine's relations and I think my ".orm.yml" files are correct.

The doctrine definitions are:
<pre>
#ExamplesExampleBundle/src/Examples/ExampleBundle/Resources/config/doctrine/PhoneType.orm.yml
Examples\ExampleBundle\Entity\PhoneType:
  type: entity
  table: phone_types
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: SEQUENCE
    name:
      type: string
      length: null
      fixed: false
      nullable: false
  oneToMany:
    phoneNumbers:
      targetEntity: PhoneNumber
      mappedBy: phoneType
  lifecycleCallbacks: {  }
</pre>
<pre>
#ExamplesExampleBundle/src/Examples/ExampleBundle/Resources/config/doctrine/PhoneNumber.orm.yml
Examples\ExampleBundle\Entity\PhoneNumber:
  type: entity
  table: phone_numbers
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: SEQUENCE
    phoneNumber:
      type: string
      length: null
      fixed: false
      nullable: false
      column: phone_number
  manyToOne:
    phoneType:
      targetEntity: PhoneType
      inversedBy: phoneNumbers
      joinColumns:
        phone_type_id:
          referencedColumnName: id
  lifecycleCallbacks: {  }
</pre>
Any idea of what I'm missing?

Thanks

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
