### ISSUE TITLE
Support doctrine/doctrine-bundle 2.0?

### ISSUE THREAD

**Issue by dmaicher** [sonata-project/SonataDoctrineORMAdminBundle#947]
## Feature Request

Since `doctrine/doctrine-bundle` 2.0 will be released soon: Are there any plans supporting it?

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/composer.json#L27
https://github.com/doctrine/DoctrineBundle/releases/tag/2.0.0-Beta1

**Comment by core23** [comment]
There is no concrete plan, but you can provide a PR that adds support 👍
